import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const status=JSON.parse(fs.readFileSync(path.join(root,'status.json'),'utf8'));
const rows=fs.readFileSync(path.join(root,'events.jsonl'),'utf8').trim().split('\n').map(JSON.parse);
const terminal=rows.filter(x=>x.type==='result');
if(terminal.length!==1)throw Error('Expected one terminal result; do not fabricate verdict');
const result=terminal[0];
const init=rows.find(x=>x.type==='system'&&x.subtype==='init');
const summary={status,session_id:result.session_id??init?.session_id,requestedModel:'claude-fable-5-1[1m]',reportedModel:init?.model,requestedEffort:'high',is_error:result.is_error,stop_reason:result.stop_reason??null,total_cost_usd:result.total_cost_usd??null,structured_output:result.structured_output??null,result:result.result??null,acceptedTerminal:status.status===0&&result.is_error===false};
fs.writeFileSync(path.join(root,'result.json'),JSON.stringify(summary,null,2)+'\n',{flag:'wx'});
fs.writeFileSync(path.join(root,'findings.md'),String(result.structured_output?.answer??result.result??'No substantive result')+'\n',{flag:'wx'});
const names=fs.readdirSync(root).filter(n=>n!=='manifest.sha256').sort();
const digest=b=>crypto.createHash('sha256').update(b).digest('hex');
const manifest=names.map(n=>`${digest(fs.readFileSync(path.join(root,n)))}  ${n}`).join('\n')+'\n';
fs.writeFileSync(path.join(root,'manifest.sha256'),manifest,{flag:'wx'});
console.log(JSON.stringify({files:names.length,manifest:digest(manifest),...summary},null,2));
