import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const cwd='/Users/aristotle/Documents/Projects/ts-drp-1';
const out=path.dirname(fileURLToPath(import.meta.url));
const command=['zsh','-f','-c',"alias claude-phel='CLAUDE_CONFIG_DIR=/Users/aristotle/.claude-phel claude'\neval 'claude-phel -p --restricted --strict-mcp-config --tools Read,Glob,Grep,Bash --allowedTools Read,Glob,Grep,Bash --model \"claude-fable-5-1[1m]\" --effort high --output-format stream-json --verbose'"];
const write=(n,v)=>fs.writeFileSync(path.join(out,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const stdout=fs.openSync(path.join(out,'events.jsonl'),'wx');
const stderr=fs.openSync(path.join(out,'stderr.log'),'wx');
const start=new Date().toISOString();
const child=spawn(command[0],command.slice(1),{cwd,stdio:['pipe',stdout,stderr]});
write('start.json',{command,cwd,start,pid:child.pid,requestedModel:'claude-fable-5-1[1m]',requestedEffort:'high',purpose:'one-off user-authorized timeout investigation'});
console.log(JSON.stringify({pid:child.pid,start}));
child.stdin.end(fs.readFileSync(path.join(out,'prompt.md')));
child.on('error',e=>write('spawn-error.json',{message:e.message}));
child.on('close',(status,signal)=>{fs.closeSync(stdout);fs.closeSync(stderr);write('status.json',{status,signal,start,finish:new Date().toISOString()});console.log(JSON.stringify({status,signal}));process.exitCode=status??1;});
