import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const git=(...a)=>execFileSync('git',['-C',root,...a],{encoding:'utf8',maxBuffer:128*1024*1024});
const custody=JSON.parse(fs.readFileSync(path.join(out,'custody-stopped.json'))),results=JSON.parse(fs.readFileSync(path.join(out,'complete-retained-results.json')));
if(git('rev-parse','HEAD').trim()!==custody.head)throw Error('HEAD drift');
for(const [f,h]of Object.entries(custody.ownerHashes))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Owner drift');
const runtime=JSON.parse(fs.readFileSync(path.join(out,'runtime-test-custody-after.json')));
for(const [f,h]of Object.entries(runtime.testHashes))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Test drift');
for(const [f,r]of Object.entries(runtime.built))if(hash(fs.readFileSync(path.join(root,f)))!==r.sha256)throw Error('Runtime drift');
if(runtime.guardEnvironment.TS_DRP_PHASE_3A1B_P4_NODE_DEATH!==null)throw Error('Unexpected long environment flag');
if(JSON.stringify(results.fullReporterTotals)!==JSON.stringify({total:881,passed:845,failed:31,pending:5})||!results.exactActiveMultiset)throw Error('Totals differ');
const patch=git('diff','--binary','--full-index','--',...Object.keys(custody.ownerHashes));
if(hash(patch)!=='245c2b251c5dfc9389c9732319c8e1b474cf2740252dff3d107320121e6564ed')throw Error('Patch drift');
const write=(f,s)=>fs.writeFileSync(path.join(out,f),s,{flag:'wx'});
write('partial-production.patch',patch);write('partial-production.patch.sha256',hash(patch)+'  partial-production.patch\n');
write('seal-summary.json',JSON.stringify({head:custody.head,signature:git('log','-1','--format=%G?').trim(),patchSha256:hash(patch),owners:Object.keys(custody.ownerHashes),productionChanged:false,testChanged:false,retained:results.fullReporterTotals,current:results.thisContinuationTotals,priorCovered:results.priorPassingCoverage,selectedActive:876,fullParentControl:{total:45,passed:45,failed:0,skipped:0},protectedPaths:86522,stashes:27,suiteErrors:0,browserExecuted:false,staticExecuted:false,isolatedExecuted:false,committed:false,closed:false},null,2)+'\n');
const collect=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?collect(path.join(dir,e.name)):[path.join(dir,e.name)]);
const files=collect(out).filter(f=>path.basename(f)!=='manifest.sha256').sort();
write('manifest.sha256',files.map(f=>hash(fs.readFileSync(f))+'  '+path.relative(out,f)).join('\n')+'\n');
for(const f of files)if(!fs.existsSync(f))throw Error('Missing entry');
console.log(JSON.stringify({entries:files.length,manifestSha256:hash(fs.readFileSync(path.join(out,'manifest.sha256'))),patchSha256:hash(patch),retained:results.fullReporterTotals}));
