import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const main='/Users/aristotle/Documents/Projects/ts-drp-1',root=fs.realpathSync('/tmp/d110c-f5b-green-fixture-exit-dtM3XF/checkout'),out=path.dirname(new URL(import.meta.url).pathname),parent=path.dirname(out),stage=process.argv[2],hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(f)),git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:128*1024*1024}).trim(),roster=read(path.join(parent,'runtime-roster.json')),mainCustody=read(path.join(parent,'custody-after.json')),head='8336eb777e775263d4983a76ffea8a699b8faf60';
if(git('rev-parse','HEAD')!==head||git('log','-1','--format=%G?')!=='G')throw Error('Signed isolated identity');
const expected={...mainCustody.ownerHashes,...mainCustody.testHashes},sourceHashes={};for(const[f,h]of Object.entries(expected)){const actual=hash(fs.readFileSync(path.join(root,f)));if(actual!==h)throw Error('Isolated source differs from main '+f);sourceHashes[f]=actual;if(!Object.hasOwn(mainCustody.ownerHashes,f)&&hash(execFileSync('git',['show',head+':'+f],{cwd:root,maxBuffer:128*1024*1024}))!==h)throw Error('Nonproduction differs from signed tree '+f);}
const patch=execFileSync('git',['diff','--binary','--full-index','--',...Object.keys(mainCustody.ownerHashes)],{cwd:root,maxBuffer:128*1024*1024});if(hash(patch)!==mainCustody.patchSha256)throw Error('Exact isolated parent patch mismatch');
const changed=git('diff','--name-only').split('\n').sort();if(JSON.stringify(changed)!==JSON.stringify(Object.keys(mainCustody.ownerHashes).sort())||git('diff','--cached','--name-only'))throw Error('Outside overlay change');
const dependencies={};for(const name of ['typescript','vite','vitest']){const p=fs.realpathSync(path.join(root,'node_modules',name));if(!p.startsWith(root+'/'))throw Error('Shared host dependency');dependencies[name]=p;}
const configs={};for(const f of ['pnpm-lock.yaml','package.json','vite.config.mts','.npmrc','scripts/ensure-native-deps.mjs']){const b=fs.readFileSync(path.join(root,f));if(!b.equals(execFileSync('git',['show',head+':'+f],{cwd:root})))throw Error('Config drift');configs[f]=hash(b);}
let runtimes={};if(stage==='prepared'){for(const f of Object.keys(mainCustody.built))if(fs.existsSync(path.join(root,f)))throw Error('Compiled owner present before fresh build');}else{for(const[f,h]of Object.entries(mainCustody.built)){const p=fs.realpathSync(path.join(root,f));if(!p.startsWith(root+'/'))throw Error('Shared runtime');const actual=hash(fs.readFileSync(p));if(actual!==h)throw Error('Fresh runtime differs from frozen main owner '+f);runtimes[f]={path:p,sha256:actual};}const native=read(path.join(out,'native-target.json'));for(const f of [native.native,...Object.keys(native.inputHashes).map(f=>path.join(root,f))])if(!fs.realpathSync(f).startsWith(root+'/'))throw Error('Native identity outside checkout');const artifacts=read(path.join(out,'native-artifacts.json'));for(const a of Object.values(artifacts.artifacts))if(hash(fs.readFileSync(a.source))!==a.sha256||hash(fs.readFileSync(path.join(out,a.retained)))!==a.sha256)throw Error('Native artifact drift');for(const[f,h]of Object.entries(native.inputHashes))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Native installer input drift');}
if(stage!=='prepared'){const prior=read(path.join(out,'custody-'+(stage==='after'?'before':'prepared')+'.json'));if(JSON.stringify(sourceHashes)!==JSON.stringify(prior.sourceHashes)||JSON.stringify(configs)!==JSON.stringify(prior.configs))throw Error('Isolated source/config drift');if(stage==='after'&&JSON.stringify(runtimes)!==JSON.stringify(prior.runtimes))throw Error('Isolated runtime drift');}
for(const[f,h]of Object.entries(expected))if(hash(fs.readFileSync(path.join(main,f)))!==h)throw Error('Main source changed during isolation '+f);for(const[f,h]of Object.entries(mainCustody.built))if(hash(fs.readFileSync(path.join(main,f)))!==h)throw Error('Main built drift');
const data={stage,root,head,signature:'G',trackedStatus:git('status','--short','--untracked-files=no'),sourceHashes,configs,dependencies,runtimes,parentPatchSha256:hash(patch),parentOverlayExact:true,overlayArtifact:'.logs/d110c-0c1f5b-green-room-guard-db8a8615/partial-production.patch',compiledInitiallyAbsent:stage==='prepared',ownFrozenInstall:true,noCopiedDist:true,noSharedNodeModules:true};fs.writeFileSync(path.join(out,'custody-'+stage+'.json'),JSON.stringify(data,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({stage,root,head,parentPatchSha256:hash(patch),sources:Object.keys(sourceHashes).length,runtimes:Object.keys(runtimes).length}));
