import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import ts from '/private/tmp/d110c-f5b-green-fixture-exit-dtM3XF/checkout/node_modules/typescript/lib/typescript.js';
const root='/private/tmp/d110c-f5b-green-fixture-exit-dtM3XF/checkout',out=path.dirname(new URL(import.meta.url).pathname),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),frozen=JSON.parse(fs.readFileSync(path.join(path.dirname(out),'frozen-scope.json'))),parse=(f,s)=>{const u=ts.createSourceFile(f,s,ts.ScriptTarget.Latest,true);if(u.parseDiagnostics.length)throw Error('Parse '+f);return u},visit=(n,f)=>{f(n);ts.forEachChild(n,c=>visit(c,f))},tokens=n=>{const a=[];function walk(c){const kids=c.getChildren();if(kids.length)kids.forEach(walk);else a.push([c.kind,c.getText()])}walk(n);return JSON.stringify(a)},same=(a,b,label)=>{if(JSON.stringify(a)!==JSON.stringify(b))throw Error(label)},emit=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const expectedTypes={certificate:'Readonly<{exactCanonicalCertifiedGenesisCertificateBytes:Uint8Array;exactCanonicalGenesisAnchorPreimageBytes:Uint8Array;exactCanonicalProfileBytes:Uint8Array;exactCanonicalSignerSetBytes:Uint8Array;pinnedGenesisAnchorDigest:string;}>',room:'readonlyReadonly<{readonlyoperation:Readonly<Record<string,unknown>>}>[]',trace:'Omit<ItfTrace,"states">&{readonlystates:ItfTrace["states"][number][];}'},results=[],allNewSpans=[];
for(const row of frozen.sourceRows){const before=fs.readFileSync(path.join(path.dirname(out),row.snapshot),'utf8'),after=fs.readFileSync(path.join(root,row.file),'utf8'),old=parse(row.file,before),unit=parse(row.file,after),originalSpans=frozen.spans.filter(s=>s.file===row.file),newSpans=[];if(hash(before)!==row.sha256)throw Error('Frozen snapshot hash');let newKey,oldKey;
 visit(unit,n=>{
  if(row.file.endsWith('/certified-genesis-contract.ts')&&ts.isFunctionDeclaration(n)&&n.name?.text==='installInput'){same(n.type.getText().replace(/\s/gu,''),expectedTypes.certificate,'Exact anonymous five-field return');newSpans.push({start:n.type.getStart(),end:n.type.end,kind:'type'});}
  if(row.file==='tests/phase-3g-v3-room-rebase-red.test.ts'&&ts.isPropertySignature(n)&&n.name?.getText()==='currentEpochOperations'){same(n.type.getText().replace(/\s/gu,''),expectedTypes.room,'Exact callback row type');newSpans.push({start:n.type.getStart(),end:n.type.end,kind:'type'});}
  if(row.file==='tests/genesis-profile.test.ts'&&ts.isCallExpression(n)&&n.expression.getText()==='ed25519.verify'){same(n.arguments[2].getText(),'Uint8Array.from(Buffer.from(row.publicKey, "hex"))','Only same-key byte conversion');newKey=n.arguments[2];newSpans.push({start:newKey.getStart(),end:newKey.end,kind:'key-representation'});}
  if(row.file==='tests/phase-5d-pacemaker-red.test.ts'&&ts.isVariableDeclaration(n)&&n.name.getText()==='mutant'&&n.initializer&&ts.isAsExpression(n.initializer)&&n.initializer.expression.getText()==='structuredClone(trace)'){same(n.initializer.type.getText().replace(/\s/gu,''),expectedTypes.trace,'Exact detached clone type');newSpans.push({start:n.initializer.getStart(),end:n.initializer.end,kind:'type'});}
 });
 visit(old,n=>{if(row.file==='tests/genesis-profile.test.ts'&&ts.isCallExpression(n)&&n.expression.getText()==='ed25519.verify')oldKey=n.arguments[2]});
 same(newSpans.length,originalSpans.length,'Exact span count '+row.file);newSpans.sort((a,b)=>a.start-b.start);originalSpans.sort((a,b)=>a.start-b.start);let restored=after;for(let i=newSpans.length-1;i>=0;i--){const s=newSpans[i];restored=restored.slice(0,s.start)+originalSpans[i].text+restored.slice(s.end)}same(tokens(parse(row.file,restored)),tokens(old),'Exact remaining source tokens '+row.file);
 let runtimeNormalized=after;if(newKey)runtimeNormalized=after.slice(0,newKey.getStart())+oldKey.getText()+after.slice(newKey.end);same(tokens(parse(row.file,emit(runtimeNormalized))),tokens(parse(row.file,emit(before))),'All runtime JS outside one key argument '+row.file);
 const tree=n=>{if(n===newKey)return tree(oldKey);const kids=n.getChildren();return{kind:ts.SyntaxKind[n.kind],leaf:kids.length===0?n.getText():undefined,children:kids.map(tree)}},capture=u=>{const a=[];visit(u,n=>{if(ts.isExpressionStatement(n)&&/^(?:await )?(?:expect|assert)/u.test(n.getText()))a.push(tree(n))});return a},originalAssertions=capture(old),currentAssertions=capture(unit);same(originalAssertions,row.assertionStatements.map(s=>s.tree),'Signed frozen assertion trees '+row.file);same(currentAssertions,originalAssertions,'Assertion predicates unchanged except key representation '+row.file);
 const oldFunctions=old.statements.filter(ts.isFunctionDeclaration).map(n=>n.name?.text),newFunctions=unit.statements.filter(ts.isFunctionDeclaration).map(n=>n.name?.text);same(oldFunctions,newFunctions,'No helper added');
 results.push({file:row.file,beforeSha256:hash(before),afterSha256:hash(after),authorizedSpans:newSpans.length,assertions:currentAssertions.length,sourceOutsideFrozenSpansEqual:true,typeErasedJavaScriptEqualExceptSingleGenesisKeyArgument:true,wholeAssertionByteIdentityClaimed:!newKey,explicitKeyRepresentationCorrection:Boolean(newKey)});allNewSpans.push(...newSpans.map(s=>({file:row.file,...s})));
}
same(allNewSpans.length,5,'Five spans total');const changed=results.filter(r=>r.beforeSha256!==r.afterSha256).map(r=>r.file).sort();same(changed,[...frozen.owners].sort(),'Exactly four owners');
fs.writeFileSync(path.join(out,'equivalence.json'),JSON.stringify({valid:true,changedPaths:changed,spanCount:5,files:results,allAssertionPredicatesPreservedExceptExplicitKeyRepresentation:true,canonicalBytesAndZip215FalseAndTrueAssertionUnchanged:true,detachedCloneAndDurableRevisionMinusOneAndTraceStateMismatchUnchanged:true,sharedTraceTypesParsersHashesAndMutantsUnchanged:true,noNewRuntimeInstrumentation:true},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({valid:true,changedOwners:changed.length,spans:5,assertions:results.reduce((a,r)=>a+r.assertions,0),runtimeException:'one same-key hex-to-bytes verify argument'}));
