import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
import ts from '/private/tmp/d110c-f5b-green-fixture-exit-dtM3XF/checkout/node_modules/typescript/lib/typescript.js';
const root='/private/tmp/d110c-f5b-green-fixture-exit-dtM3XF/checkout',out=path.dirname(new URL(import.meta.url).pathname),dir=path.join(out,'runtime-49'),head='8336eb777e775263d4983a76ffea8a699b8faf60',hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(f==='frozen-scope.json'?path.dirname(out):out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:128*1024*1024}).trim();
function custody(){if(git('rev-parse','HEAD')!==head||git('log','-1','--format=%G?')!=='G')throw Error('HEAD drift');const c=read('custody-before.json'),main=JSON.parse(fs.readFileSync(path.join(path.dirname(out),'custody-after.json')));for(const[f,h]of Object.entries(c.sourceHashes))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Source drift '+f);for(const[f,v]of Object.entries(c.runtimes))if(hash(fs.readFileSync(path.join(root,f)))!==v.sha256)throw Error('Runtime drift '+f);const patch=execFileSync('git',['diff','--binary','--full-index','--',...Object.keys(main.ownerHashes)],{cwd:root,maxBuffer:128*1024*1024});if(hash(patch)!==main.patchSha256)throw Error('Parent patch drift');return main.testHashes;}
function processes(){const result=spawnSync('pgrep',['-f','(vitest|quint|apalache|heap-prof|cpu-prof)'],{encoding:'utf8'});if(![0,1].includes(result.status))throw Error('PID query failed');const pids=result.stdout.trim().split(/\s/u).filter(s=>/^\d+$/u.test(s)).map(Number).filter(p=>p!==process.pid&&p!==process.ppid),rows=[];for(const pid of pids){const state=spawnSync('ps',['-p',String(pid),'-o','pid=,ppid=,stat='],{encoding:'utf8'});if(state.status===1)continue;if(state.status!==0)throw Error('PID status failure');const cwd=spawnSync('lsof',['-a','-p',String(pid),'-d','cwd','-Fn'],{encoding:'utf8'}),paths=cwd.stdout.split('\n').filter(s=>s.startsWith('n')).map(s=>s.slice(1)),relevant=paths.some(p=>p===root||p.startsWith(root+'/')||/^\/(?:private\/)?tmp\/d110c-f5b-/u.test(p));rows.push({pid,status:state.stdout.trim(),taskRelevantCwd:relevant});if(relevant)throw Error('Competing task runtime PID '+pid);}return{numericOnly:true,noArgvOrComm:true,candidates:rows,taskCompetitors:0,unrelatedProcessesDoNotBlock:true};}
if(process.argv[2]==='freeze'){
 const testHashes=custody();for(const label of ['install','custody-prepared','native-preparation','native-prebuild','native-addon-import','build','node-root-import','custody-before','graph-comparison','format','lint','diff','matrix-validator','equivalence'])if(read(label+'/status.json').code!==0)throw Error('Static gate '+label);if(read('compiler-green/status.json').code!==1||!read('matrix-validation.json').valid)throw Error('Expected grid-only compiler disposition');
 const frozen=read('frozen-scope.json'),genesis='tests/genesis-profile.test.ts',text=fs.readFileSync(path.join(root,genesis),'utf8'),unit=ts.createSourceFile(genesis,text,ts.ScriptTarget.Latest,true),genesisEntries=[];function base(n){if(ts.isIdentifier(n))return n.text;if(ts.isPropertyAccessExpression(n)||ts.isCallExpression(n))return base(n.expression);return '';}function scan(n,ancestors=[]){if(ts.isCallExpression(n)&&n.arguments[0]&&ts.isStringLiteral(n.arguments[0])){const kind=base(n.expression),title=n.arguments[0].text;if(kind==='describe'){for(const a of n.arguments.slice(1))scan(a,[...ancestors,title]);return;}if(kind==='it'){genesisEntries.push({file:genesis,title,ancestorTitles:ancestors,fullName:[...ancestors,title].join(' '),origin:'source-derived-with-signed-closure-no-invented-prior-reporter'});return;}}ts.forEachChild(n,c=>scan(c,ancestors));}scan(unit);
 if(genesisEntries.length!==9||JSON.stringify(genesisEntries.map(e=>e.title).sort())!==JSON.stringify(frozen.entries.filter(e=>e.file===genesis).map(e=>e.title).sort()))throw Error('Genesis source roster');const entries=frozen.entries.map(e=>e.file===genesis?genesisEntries.find(g=>g.title===e.title):e),files=[...new Set(entries.map(e=>e.file))];if(entries.length!==49||files.length!==4)throw Error('49 roster');const safety=processes();fs.mkdirSync(dir);write('process-readiness.json',safety);
 write('runtime-roster.json',{head,files,entries,testHashes,sourceSnapshots:6,collectionRepeated:false,expected:{total:49,passed:49,failed:0,skipped:0},compilerDisposition:'exit1 exact unchanged grid-only diagnostic; matrix0',command:['pnpm','exec','vitest','run',...files,'--no-file-parallelism','--coverage.enabled=false','--reporter=default','--reporter=json','--outputFile='+path.join(dir,'focused.json')]});console.log(JSON.stringify({frozen:true,files:4,cases:49,taskCompetitors:0,effectiveTestHashes:Object.keys(testHashes).length}));
}else if(process.argv[2]==='run'){
 custody();const roster=read('runtime-roster.json');write('runtime-49/execution-start.json',{head,pid:process.pid,startedAt:new Date().toISOString()});write('runtime-49/command.json',{cwd:root,command:roster.command});console.log(JSON.stringify({recorderPid:process.pid,soleIsolatedRuntime:true,cases:49}));const stdout=fs.openSync(path.join(dir,'stdout.log'),'wx'),stderr=fs.openSync(path.join(dir,'stderr.log'),'wx'),result=spawnSync(roster.command[0],roster.command.slice(1),{cwd:root,env:process.env,stdio:['ignore',stdout,stderr]});fs.closeSync(stdout);fs.closeSync(stderr);write('runtime-49/status.json',{status:result.status,signal:result.signal,error:result.error?.message,endedAt:new Date().toISOString()});
 const report=read('runtime-49/focused.json'),assertions=report.testResults.flatMap(s=>s.assertionResults.map(a=>({file:path.relative(root,s.name),...a}))),identity=a=>JSON.stringify([a.file,a.title,a.ancestorTitles,a.fullName]),actual=assertions.map(identity).sort(),expected=roster.entries.map(identity).sort(),exactNames=JSON.stringify(actual)===JSON.stringify(expected),exactFiles=JSON.stringify(report.testResults.map(s=>path.relative(root,s.name)).sort())===JSON.stringify([...roster.files].sort()),valid=result.status===0&&report.success===true&&exactNames&&exactFiles&&report.numTotalTests===49&&report.numPassedTests===49&&report.numFailedTests===0&&report.numPendingTests===0&&!report.numRuntimeErrorTestSuites&&!report.numUnhandledErrors&&!(report.unhandledErrors?.length)&&report.testResults.every(s=>!s.message&&!s.testExecError)&&assertions.every(a=>a.status==='passed'&&a.failureMessages.length===0);
 write('runtime-49/validation.json',{valid,exactNames,exactFiles,success:report.success,total:report.numTotalTests,passed:report.numPassedTests,failed:report.numFailedTests,skipped:report.numPendingTests,numRuntimeErrorTestSuites:report.numRuntimeErrorTestSuites??null,numUnhandledErrors:report.numUnhandledErrors??null,unhandledErrors:report.unhandledErrors??[],suites:report.testResults.map(s=>({file:s.name,message:s.message,testExecError:s.testExecError??null})),assertions,reporterSha256:hash(fs.readFileSync(path.join(dir,'focused.json')))});console.log(JSON.stringify({valid,total:report.numTotalTests,passed:report.numPassedTests,failed:report.numFailedTests,skipped:report.numPendingTests}));if(!valid)process.exitCode=1;
}else throw Error('Unknown mode');
