import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync,execFileSync} from 'node:child_process';
const root=process.cwd(),out=path.dirname(new URL(import.meta.url).pathname),read=n=>JSON.parse(fs.readFileSync(path.join(out,n),'utf8')),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),write=(n,d)=>fs.writeFileSync(path.join(out,n),JSON.stringify(d,null,2)+'\n',{flag:'wx'}),git=(...a)=>execFileSync('git',a,{encoding:'utf8'}).trim();
if(fs.existsSync(path.join(out,'execution-start.json')))throw Error('Sole execution consumed');
const matrix=read('matrix.json'),frozen=read('focused-command.json'),head=git('rev-parse','HEAD'),remote=git('ls-remote','https://github.com/Faolain/ts-drp-1','refs/heads/codex/phase3a1b-p6-golden-path').split(/\s+/u)[0];
if(head!=='da874b52ab99e7143911f1ce8c018c29f826db3c'||remote!==head||git('log','-1','--format=%G?')!=='G'||git('diff','--name-only')||git('diff','--cached','--name-only')||frozen.cwd!==root)throw Error('Signed pushed clean identity');
for(const[f,d]of Object.entries(matrix.fileHashes))if(hash(fs.readFileSync(f))!==d)throw Error('Frozen source drift');
for(const label of ['isolated-install','native-preparation','native-prebuild','native-addon-import','isolated-build','isolated-node-root-import','fixture-validation-corrected','isolated-preflight'])if(read(label+'/status.json').code!==0)throw Error('Prerequisite failed '+label);
const command=['pnpm','exec','vitest','run',...matrix.files,'--no-file-parallelism','--coverage.enabled=false','--reporter=json','--outputFile='+path.join(out,'focused.json')];if(JSON.stringify(command)!==JSON.stringify(frozen.command))throw Error('Command drift');
write('execution-start.json',{head,remote,signature:'G',command,matrixSha256:hash(fs.readFileSync(path.join(out,'matrix.json'))),executionCount:1,startedAt:new Date().toISOString()});
const result=spawnSync(command[0],command.slice(1),{encoding:'utf8',maxBuffer:32*1024*1024});
fs.writeFileSync(path.join(out,'stdout.log'),result.stdout??'',{flag:'wx'});fs.writeFileSync(path.join(out,'stderr.log'),result.stderr??'',{flag:'wx'});
const report=fs.existsSync(path.join(out,'focused.json'))?read('focused.json'):null,outcomes=report?.testResults.flatMap(s=>s.assertionResults.map(r=>({file:path.relative(root,s.name),name:[...r.ancestorTitles,r.title].join(' > '),status:r.status,duration:r.duration,failureMessages:r.failureMessages??[]})))??[],topLevel=[...(report?.unhandledErrors??[]),...(report?.testResults.flatMap(s=>[s.message,s.testExecError].filter(Boolean))??[])],violations=[];
const canonical=rows=>rows.map(r=>({file:r.file,name:r.name,status:r.status??r.expectedStatus})).sort((a,b)=>a.name.localeCompare(b.name));
if(result.status!==1||result.signal||report?.success!==false||report?.testResults.length!==1||report?.numTotalTests!==13||report?.numPassedTests!==11||report?.numFailedTests!==2||outcomes.length!==13||topLevel.length||JSON.stringify(canonical(outcomes))!==JSON.stringify(canonical(matrix.entries)))violations.push('Exact13/11/2 matrix mismatch');
const observationLines=(result.stdout??'').split('\n').map(l=>l.trim()).filter(l=>l.startsWith('{"kind":"F5B_ROOM_GUARD_OBSERVATIONS"')),observations=observationLines.length===1?JSON.parse(observationLines[0]).observations:[],expectedKeys=[];
for(const profileId of ['creator-trusted-v1','creator-trusted-settlement-v1'])for(const composition of ['factory','rebase','signer','declaration-only'])expectedKeys.push({profileId,composition});
const observedKeys=observations.map(({profileId,composition})=>({profileId,composition}));
if(observations.length!==8||JSON.stringify(observedKeys)!==JSON.stringify(expectedKeys)||observations.some(r=>r.detail!=='D.108e2b application authority was read'||JSON.stringify(r.reads)!==JSON.stringify({application:1,signer:0,store:0,transport:0})))violations.push('Exact eight observations mismatch');
const classified=observations.map(r=>({...r,permitted:r.composition==='declaration-only'||(r.composition==='signer'&&r.profileId==='creator-trusted-settlement-v1')}));
const forbidden=classified.filter(r=>!r.permitted),controls=classified.filter(r=>r.permitted);
if(forbidden.length!==5||controls.length!==3)violations.push('Five forbidden/three controls mismatch');
if(outcomes.some(r=>r.failureMessages.some(m=>/timed out|F5B_ROOM_GUARD_FIXTURE_|Cannot find module|Failed to load/u.test(m))))violations.push('Noncausal fixture/loader/timeout anomaly');
const newCase=outcomes.find(r=>r.name==='classifies complete legacy and settlement successor compositions before reading room authorities');if(!newCase?.failureMessages.some(m=>m.includes('F5B_ROOM_GUARD_PROFILE_AUTHORITY_READ_ORDER')))violations.push('Changed probe token');
write('observations.json',{rawObservationCount:observationLines.length,observations:classified,forbiddenViolations:forbidden.length,permittedControls:controls.length});
write('result.json',{classification:violations.length?'UNEXPECTED_MATRIX_STOP_NO_RERUN':'CAUSAL_ROOM_AUTHORITY_READ_ORDER_RED',executionCount:1,head,runnerStatus:result.status,signal:result.signal,total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,intentionallyFiltered:outcomes.filter(r=>r.status==='pending'||r.status==='skipped').length,topLevel,violations,outcomes,forbiddenViolations:forbidden.length,permittedControls:controls.length,finishedAt:new Date().toISOString(),noParentRuntimeRun:true,pendingGreenGateStillRequired:true});
console.log(JSON.stringify({total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,forbiddenViolations:forbidden.length,permittedControls:controls.length,violations}));process.exitCode=violations.length?2:0;
