import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const root=process.cwd(),out=path.dirname(new URL(import.meta.url).pathname),read=n=>JSON.parse(fs.readFileSync(path.join(out,n),'utf8')),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),git=(...a)=>execFileSync('git',a,{encoding:'utf8'}).trim();
if(fs.existsSync(path.join(out,'manifest.sha256')))throw Error('Already sealed');
if(git('rev-parse','HEAD')!=='da874b52ab99e7143911f1ce8c018c29f826db3c'||git('log','-1','--format=%G?')!=='G'||git('ls-remote','origin','refs/heads/codex/phase3a1b-p6-golden-path').split(/\s+/u)[0]!=='da874b52ab99e7143911f1ce8c018c29f826db3c')throw Error('Signed pushed identity');
for(const f of ['execution-start.json','focused.json','result.json','observations.json','matrix.json'])if(fs.existsSync(path.join(out,f)))throw Error('Unexpected runtime/frozen matrix artifact');
for(const label of ['isolated-clone','isolated-sparse','isolated-checkout','isolated-install','native-preparation','native-prebuild','native-addon-import','isolated-build','isolated-node-root-import','fixture-validation-corrected','typecheck-baseline-comparison','final-evidence-check'])if(read(label+'/status.json').code!==0)throw Error('Preparation status '+label);
if(read('fixture-validation/status.json').code!==1||read('isolated-preflight/status.json').code!==1)throw Error('Stop statuses');
const dx=read('typecheck.json'),comparison=read('typecheck-baseline-comparison.json'),before=read('custody-before.json'),after=read('custody-after.json'),ib=read('isolation-before.json'),ia=read('isolation-after.json');
if(dx.targetDiagnostics.length!==1||dx.externalDiagnostics.length!==41||!comparison.externalExactlyEqual||comparison.externalCount!==41||comparison.baselineTargetCount!==0||comparison.currentTargetCount!==1||comparison.newTargetDiagnostic[0].token!=='"guard"')throw Error('Static attribution');
if(read('list.json').length!==13||read('preflight-commands.json').some(c=>c.status!==0)||!read('fixture-validation-corrected.json').allVerified)throw Error('Preparation gates');
for(const key of ['productionHashes','retainedHashes','built','originalBodyHashes','testSha256'])if(JSON.stringify(before[key])!==JSON.stringify(after[key]))throw Error('Custody differs '+key);
if(Object.keys(after.productionHashes).length!==8||Object.keys(after.built).length!==7||Object.keys(after.retainedHashes).length!==78||after.protectedPaths!==86522||after.stashCount!==27||!after.allProtectedPathsExist||!after.allOriginalNonImportBytesIdentical)throw Error('Custody counts');
for(const key of ['sourceHashes','runtimes'])if(JSON.stringify(ib[key])!==JSON.stringify(ia[key]))throw Error('Isolated drift');
for(const[f,d]of Object.entries(after.productionHashes))if(hash(fs.readFileSync(path.join(root,f)))!==d)throw Error('Live production drift');
for(const[f,d]of Object.entries(ia.sourceHashes))if(hash(fs.readFileSync(path.join(ia.root,f)))!==d)throw Error('Isolated source drift');
for(const[f,d]of Object.entries(ia.runtimes))if(hash(fs.readFileSync(path.join(ia.root,f)))!==d.sha256)throw Error('Isolated runtime drift');
for(const[name,a]of Object.entries(read('native-artifacts.json').artifacts))for(const f of [a.source,path.join(out,a.retained)])if(hash(fs.readFileSync(f))!==a.sha256)throw Error('Native artifact drift '+name);
const validation={classification:'STOPPED_NEW_TARGET_TYPE_DIAGNOSTIC_BEFORE_RUNTIME',testCommit:'da874b52ab99e7143911f1ce8c018c29f826db3c',signature:'G',pushed:true,runtimeExecutions:0,constructorProbeExecutions:0,expectedRuntimeUnproved:{total:13,passed:11,failed:2,forbiddenViolations:5,permittedControls:3},listCount:13,originalBodiesByteIdentical:12,fixtureSignaturesVerified:2,initialDiagnosticLoaderFailurePreserved:true,correctedDiagnosticLoaderPassed:true,newTargetDiagnostics:1,baselineTargetDiagnostics:0,externalDiagnostics:41,externalBaselineExactlyEqual:true,typecheckPassed:false,sourceBuildPassed:true,productionPreserved:true,protectedPaths:86522,stashCount:27,rootContinuationRequired:true};
fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(validation,null,2)+'\n',{flag:'wx'});
const files=[];function walk(dir){for(const row of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,row.name);if(row.isDirectory())walk(full);else if(row.isFile())files.push(path.relative(out,full));else throw Error('Link')}}walk(out);files.sort();
const manifest=files.map(f=>hash(fs.readFileSync(path.join(out,f)))+'  '+f).join('\n')+'\n';fs.writeFileSync(path.join(out,'manifest.sha256'),manifest,{flag:'wx'});console.log(JSON.stringify({entries:files.length,manifestSha256:hash(manifest),classification:validation.classification}));
