import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
const root = '/Users/aristotle/Documents/Projects/ts-drp-1';
const out = path.dirname(new URL(import.meta.url).pathname);
const hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const read = file => JSON.parse(fs.readFileSync(path.join(root, file)));
const write = (file, value) => fs.writeFileSync(path.join(out, file), JSON.stringify(value, null, 2) + '\n', { flag: 'wx' });
const git = (...args) => execFileSync('git', ['-C', root, ...args], { encoding: 'utf8', maxBuffer: 128 * 1024 * 1024 }).trim();
const head = git('rev-parse', 'HEAD');
if (head !== '0994db2904c942b1b744f5e46b8a8a98a0f7c35f' || git('log', '-1', '--format=%G?') !== 'G' || git('diff', '--cached', '--name-only') || git('ls-remote', 'origin', 'refs/heads/codex/phase3a1b-p6-golden-path').split(/\s+/u)[0] !== head) throw Error('Signed pushed custody');
const before = read('.logs/d110c-0c1f5b-snapshot-fixture-green-dc2f8dc2/custody-final.json');
for (const map of [before.ownerHashes, before.built, before.testHashes, before.fixtureHashes]) for (const [file, expected] of Object.entries(map)) if (hash(fs.readFileSync(path.join(root, file))) !== expected) throw Error('Source/runtime drift ' + file);
const original = read('.logs/d110c-0c1f5b-green-57834387/custody-before.json');
if (git('stash', 'list', '--format=%H %gd %gs') !== original.stashes.trim()) throw Error('Stashes');
for (const file of original.untracked) if (!fs.existsSync(path.join(root, file))) throw Error('Protected path');
const raw = fs.readFileSync(path.join(out, 'fable/events.jsonl'), 'utf8');
const events = raw.trimEnd().split('\n').map(line => JSON.parse(line));
const terminal = events.at(-1);
const status = JSON.parse(fs.readFileSync(path.join(out, 'fable/status.json')));
if (terminal.type !== 'result' || terminal.is_error || terminal.subtype !== 'success' || status.code !== 0 || status.signal) throw Error('Consultation terminal');
const usedTools = [...new Set(events.flatMap(e => e.message?.content ?? []).filter(c => c.type === 'tool_use').map(c => c.name))];
if (usedTools.some(tool => !['Read', 'Glob', 'Grep'].includes(tool))) throw Error('Unexpected consultation tool');
const result = terminal.structured_output ?? terminal.result;
if (typeof result !== 'string' || !result.includes('Recommendation')) throw Error('Missing substantive answer');
fs.writeFileSync(path.join(out, 'fable/result.md'), result + '\n', { flag: 'wx' });
write('validation.json', { head, signature: 'G', originExact: true, indexEmpty: true, sourceRuntimeUnchanged: true, productionOwners: 8, builtOwners: 7, stashes: 27, protectedPaths: original.untracked.length, sessionId: terminal.session_id, is_error: terminal.is_error, stop_reason: terminal.stop_reason, total_cost_usd: terminal.total_cost_usd, tools: usedTools, model: 'claude-fable-5-1[1m]', effort: 'high', advisoryOnly: true, noFormalAcceptance: true, noWorkloadExecuted: true, sourceEdits: false });
const walk = dir => fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => entry.isDirectory() ? walk(path.join(dir, entry.name)) : [path.relative(out, path.join(dir, entry.name))]);
if (fs.existsSync(path.join(out, 'manifest.sha256'))) throw Error('Already sealed');
const files = walk(out).sort();
const manifest = files.map(file => hash(fs.readFileSync(path.join(out, file))) + '  ' + file + '\n').join('');
fs.writeFileSync(path.join(out, 'manifest.sha256'), manifest, { flag: 'wx' });
console.log(JSON.stringify({ files: files.length, manifestSha256: hash(manifest), advisoryOnly: true }));
