import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const root=process.cwd(),out=path.dirname(new URL(import.meta.url).pathname);
const read=name=>JSON.parse(fs.readFileSync(path.join(out,name),'utf8'));
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const git=(...args)=>execFileSync('git',args,{encoding:'utf8'}).trim();
if(fs.existsSync(path.join(out,'manifest.sha256')))throw Error('Already sealed');
if(git('rev-parse','HEAD')!=='de961884d9d3204f2c67561e96434995c6f0fafe'||git('log','-1','--format=%G?')!=='G'||git('ls-remote','origin','refs/heads/codex/phase3a1b-p6-golden-path').split(/\s+/u)[0]!=='de961884d9d3204f2c67561e96434995c6f0fafe')throw Error('Signed pushed tests identity differs');
const result=read('result.json'),matrix=read('matrix.json'),before=read('custody-before.json'),after=read('custody-after.json'),ib=read('isolation-before.json'),ia=read('isolation-after.json');
if(result.classification!=='ACCEPTED_RETAINED_SETTLEMENT_CODEC_BASELINE'||result.total!==4||result.passed!==4||result.failed!==0||result.intentionallyFiltered!==0||result.violations.length||result.executionCount!==1)throw Error('Exact baseline failed');
for(const label of ['main-lint','main-format','tests-diff-check','isolated-clone','isolated-sparse','isolated-checkout','isolated-pristine','isolated-install','isolated-build','isolated-preflight','evidence-script-syntax'])if(read(label+'/status.json').code!==0)throw Error('Static/source gate failed '+label);
if(read('typecheck.json').targetDiagnostics.length||read('typecheck.json').externalDiagnostics.length)throw Error('Target/external diagnostics');
if(JSON.stringify(before.built)!==JSON.stringify(after.built)||Object.keys(after.built).length!==7||Object.keys(after.retainedHashes).length!==76)throw Error('Built/retained custody differs');
if(read('final-evidence-check/status.json').code!==0)throw Error('Evidence syntax/whitespace check failed');
if(after.protectedPaths!==86522||after.stashCount!==27||!after.allOutsideAuthorizedSpansPreserved||!after.allProtectedPathsExist||after.syntaxDiagnostics!==0||JSON.stringify(before.productionHashes)!==JSON.stringify(after.productionHashes)||JSON.stringify(before.retainedHashes)!==JSON.stringify(after.retainedHashes))throw Error('Main custody differs');
if(JSON.stringify(ib.sourceHashes)!==JSON.stringify(ia.sourceHashes)||JSON.stringify(ib.runtimes)!==JSON.stringify(ia.runtimes)||ia.trackedStatus!=='')throw Error('Isolated custody differs');
for(const[f,h]of Object.entries(matrix.fileHashes))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Frozen test/fixture drift');
if(JSON.stringify(read('focused-command.json').command)!==JSON.stringify(read('execution-start.json').command))throw Error('Frozen command differs');
fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify({tests:'de961884d9d3204f2c67561e96434995c6f0fafe',signature:'G',pushed:true,classification:result.classification,executionCount:1,total:4,passed:4,failed:0,allOtherAssertionsUnchanged:true,parentTestsUnchanged:true,productionPreserved:true,isolatedSourceRuntimePreserved:true,targetDiagnostics:0,externalDiagnostics:read('typecheck.json').externalDiagnostics.length,packageWideTypecheckClaimedGreen:false,protectedPaths:86522,stashCount:27,authorizedSpans:after.spans,retainedHashes:after.retainedHashes,immutable:after.immutable,notNewCausalRed:true,pendingGreenGateStillRequired:true},null,2)+'\n',{flag:'wx'});
const files=[];function walk(dir){for(const row of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,row.name);if(row.isDirectory())walk(full);else if(row.isFile())files.push(path.relative(out,full));else throw Error('Unexpected link');}}walk(out);files.sort();
const manifest=files.map(f=>hash(fs.readFileSync(path.join(out,f)))+'  '+f).join('\n')+'\n';
fs.writeFileSync(path.join(out,'manifest.sha256'),manifest,{flag:'wx'});
console.log(JSON.stringify({entries:files.length,manifestSha256:hash(manifest),classification:result.classification}));
