import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
import ts from '/Users/aristotle/Documents/Projects/ts-drp-1/node_modules/typescript/lib/typescript.js';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),dir=path.join(out,'main-45'),head=JSON.parse(fs.readFileSync(path.join(out,'signed-source.json'))).head,hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:128*1024*1024}).trim();
function custody(){if(git('rev-parse','HEAD')!==head||git('log','-1','--format=%G?')!=='G')throw Error('HEAD drift');const c=read('custody-before.json'),eq=read('equivalence.json'),updated={...c.testHashes,...Object.fromEntries(eq.files.map(f=>[f.file,f.afterSha256]))};for(const map of [c.ownerHashes,c.built,updated])for(const[f,h]of Object.entries(map))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Source/runtime drift '+f);const patch=execFileSync('git',['diff','--binary','--full-index','--',...Object.keys(c.ownerHashes)],{cwd:root,maxBuffer:128*1024*1024});if(hash(patch)!==c.patchSha256)throw Error('Parent patch drift');return updated;}
function processes(){const result=spawnSync('pgrep',['-f','(vitest|quint|apalache|heap-prof|cpu-prof)'],{encoding:'utf8'});if(![0,1].includes(result.status))throw Error('PID query failed');const pids=result.stdout.trim().split(/\s/u).filter(s=>/^\d+$/u.test(s)).map(Number).filter(p=>p!==process.pid&&p!==process.ppid),rows=[];for(const pid of pids){const state=spawnSync('ps',['-p',String(pid),'-o','pid=,ppid=,stat='],{encoding:'utf8'});if(state.status===1)continue;if(state.status!==0)throw Error('PID status failure');const cwd=spawnSync('lsof',['-a','-p',String(pid),'-d','cwd','-Fn'],{encoding:'utf8'}),paths=cwd.stdout.split('\n').filter(s=>s.startsWith('n')).map(s=>s.slice(1)),relevant=paths.some(p=>p===root||p.startsWith(root+'/')||/^\/(?:private\/)?tmp\/d110c-f5b-/u.test(p));rows.push({pid,status:state.stdout.trim(),taskRelevantCwd:relevant});if(relevant)throw Error('Competing task runtime PID '+pid);}return{numericOnly:true,noArgvOrComm:true,candidates:rows,taskCompetitors:0,unrelatedProcessesDoNotBlock:true};}
if(process.argv[2]==='freeze'){
 const testHashes=custody();for(const label of ['format','lint','diff','typecheck-matrix','equivalence','signed-source'])if(read(label+'/status.json').code!==0)throw Error('Static gate '+label);if(read('typecheck/status.json').code!==1||!read('typecheck-matrix.json').valid)throw Error('Known three snapshot diagnostic disposition');
 const baselinePath=path.join(root,'.logs/d110c-0c1f5b-green-71bca5d5/retained-71/result.json'),baseline=JSON.parse(fs.readFileSync(baselinePath)),entries=baseline.testResults.flatMap(s=>s.assertionResults.map(a=>({file:path.relative(root,s.name),title:a.title,ancestorTitles:a.ancestorTitles,fullName:a.fullName}))),files=baseline.testResults.map(s=>path.relative(root,s.name));if(entries.length!==45||files.length!==2)throw Error('Exact parent45 baseline');const safety=processes();fs.mkdirSync(dir);write('process-readiness.json',safety);write('runtime-roster.json',{head,files,entries,testHashes,baselinePath,baselineSha256:hash(fs.readFileSync(baselinePath)),collectionRepeated:false,expected:{total:45,passed:45,failed:0,skipped:0},command:['pnpm','exec','vitest','run',...files,'--no-file-parallelism','--coverage.enabled=false','--reporter=default','--reporter=json','--outputFile='+path.join(dir,'focused.json')]});console.log(JSON.stringify({frozen:true,files:2,cases:45,taskCompetitors:0,effectiveTestHashes:Object.keys(testHashes).length}));
}else if(process.argv[2]==='run'){
 custody();const roster=read('runtime-roster.json');write('main-45/execution-start.json',{head,pid:process.pid,startedAt:new Date().toISOString()});write('main-45/command.json',{cwd:root,command:roster.command});console.log(JSON.stringify({recorderPid:process.pid,soleMainRuntime:true,cases:45}));const stdout=fs.openSync(path.join(dir,'stdout.log'),'wx'),stderr=fs.openSync(path.join(dir,'stderr.log'),'wx'),result=spawnSync(roster.command[0],roster.command.slice(1),{cwd:root,env:process.env,stdio:['ignore',stdout,stderr]});fs.closeSync(stdout);fs.closeSync(stderr);write('main-45/status.json',{status:result.status,signal:result.signal,error:result.error?.message,endedAt:new Date().toISOString()});
 const report=read('main-45/focused.json'),assertions=report.testResults.flatMap(s=>s.assertionResults.map(a=>({file:path.relative(root,s.name),...a}))),identity=a=>JSON.stringify([a.file,a.title,a.ancestorTitles,a.fullName]),actual=assertions.map(identity).sort(),expected=roster.entries.map(identity).sort(),exactNames=JSON.stringify(actual)===JSON.stringify(expected),exactFiles=JSON.stringify(report.testResults.map(s=>path.relative(root,s.name)).sort())===JSON.stringify([...roster.files].sort()),valid=result.status===0&&report.success===true&&exactNames&&exactFiles&&report.numTotalTests===45&&report.numPassedTests===45&&report.numFailedTests===0&&report.numPendingTests===0&&!report.numRuntimeErrorTestSuites&&!report.numUnhandledErrors&&!(report.unhandledErrors?.length)&&report.testResults.every(s=>!s.message&&!s.testExecError)&&assertions.every(a=>a.status==='passed'&&a.failureMessages.length===0);
 write('main-45/validation.json',{valid,exactNames,exactFiles,success:report.success,total:report.numTotalTests,passed:report.numPassedTests,failed:report.numFailedTests,skipped:report.numPendingTests,numRuntimeErrorTestSuites:report.numRuntimeErrorTestSuites??null,numUnhandledErrors:report.numUnhandledErrors??null,unhandledErrors:report.unhandledErrors??[],suites:report.testResults.map(s=>({file:s.name,message:s.message,testExecError:s.testExecError??null})),assertions,reporterSha256:hash(fs.readFileSync(path.join(dir,'focused.json')))});console.log(JSON.stringify({valid,total:report.numTotalTests,passed:report.numPassedTests,failed:report.numFailedTests,skipped:report.numPendingTests}));if(!valid)process.exitCode=1;
}else throw Error('Unknown mode');
