import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const out=path.dirname(new URL(import.meta.url).pathname);
const git=(...args)=>execFileSync('git',args,{encoding:'utf8',maxBuffer:128*1024*1024}).trimEnd();
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const write=(name,bytes)=>fs.writeFileSync(path.join(out,name),bytes,{flag:'wx'});
const before=JSON.parse(fs.readFileSync(path.join(out,'custody-before.json'),'utf8'));
const changed=Object.entries(before.files).filter(([file,digest])=>hash(fs.readFileSync(file))!==digest).map(([file])=>file);
const untracked=new Set(git('ls-files','--others','--exclude-standard','-z').split('\0').filter(Boolean));
const missingUntracked=before.untracked.filter(file=>!untracked.has(file));
const stashes=git('stash','list','--format=%H %gd %gs');
const diff=git('diff');
const result={head:git('rev-parse','HEAD'),changedSinceResume:changed,productionPatchUnchanged:diff===before.diff,stashesUnchanged:stashes===before.stashes,stashCount:stashes.split('\n').length,missingUntracked,staged:git('diff','--cached'),priorManifestHashes:Object.fromEntries(['79743f98','f031b166'].map(anchor=>[anchor,hash(fs.readFileSync('.logs/d110c-0c1f5b-green-'+anchor+'/manifest.sha256'))]))};
if(changed.length||!result.productionPatchUnchanged||!result.stashesUnchanged||missingUntracked.length||result.staged)throw new Error(JSON.stringify(result));
write('partial-production.patch',diff+'\n');
write('custody-after.json',JSON.stringify(result,null,2)+'\n');
write('manifest.sha256',fs.readdirSync(out).filter(name=>name!=='manifest.sha256').sort().map(name=>hash(fs.readFileSync(path.join(out,name)))+'  '+name).join('\n')+'\n');
console.log(JSON.stringify({...result,manifestHash:hash(fs.readFileSync(path.join(out,'manifest.sha256')))},null,2));
