import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
const out=path.dirname(new URL(import.meta.url).pathname);
const [stage,kind,validationOnly]=process.argv.slice(2),root=fs.realpathSync(process.cwd());
const focused=['tests/phase-6b-d110c-0c1f5b0z-maintenance-discovery-red.test.ts'];
const retained=['tests/phase-6b-ahe-reclamation-red.test.ts','packages/storage-node/tests/phase-6b-ahe-reclamation-red.test.ts','tests/phase-6b-runtime-reclamation-red.test.ts','tests/phase-6b-cleanup-eligibility-red.test.ts','tests/phase-6b-issuance-retention-red.test.ts','packages/storage-node/tests/phase-6b-issuance-retention-red.test.ts','tests/phase-6b-d110c-0c1f5b0d-reclamation-red.test.ts'];
const files=kind==='focused'?focused:kind==='retained'?retained:['tests/phase-6b-d110c-0c1f5b0d-corrective-red.test.ts'];
const label=`${stage}-${kind}`,reporter=path.join(out,`${label}.json`);
const args=['exec','vitest','run',...files,'--coverage.enabled=false','--reporter=json','--outputFile='+reporter];
if(!validationOnly)fs.writeFileSync(path.join(out,`${label}-frozen.json`),JSON.stringify({frozenAt:new Date().toISOString(),root,command:['pnpm',...args],files,expectedFiles:files.length,expectedTotal:kind==='focused'?16:null,expectedFailures:0,expectedSkipped:0,expectedTopLevelErrors:0,unchangedThresholds:true},null,2)+'\n',{flag:'wx'});
const run=validationOnly?{status:JSON.parse(fs.readFileSync(path.join(out,label,'status.json'),'utf8')).code}:spawnSync(process.execPath,[path.join(out,'run.mjs'),label,root,'pnpm',...args],{encoding:'utf8',maxBuffer:1024*1024});
process.stdout.write(run.stdout??'');process.stderr.write(run.stderr??'');
const report=fs.existsSync(reporter)?JSON.parse(fs.readFileSync(reporter,'utf8')):null;
const assertions=report?.testResults?.flatMap(file=>file.assertionResults.map(row=>({file:path.relative(root,file.name),...row})))??[];
const violations=[];
if(run.status!==0)violations.push('Runner nonzero');
if(!report||report.success!==true)violations.push('Reporter unsuccessful or absent');
if(report?.testResults.length!==files.length)violations.push('File count mismatch');
if(kind==='focused'&&assertions.length!==16)violations.push('Focused count mismatch');
if(assertions.some(row=>row.status!=='passed'||row.failureMessages.length!==0))violations.push('Nonpassing selected assertion');
if(report?.numFailedTests!==0||report?.numPendingTests!==0||report?.numTodoTests!==0||(report?.numRuntimeErrorTestSuites??0)!==0||report?.numFailedTestSuites!==0||report?.numPendingTestSuites!==0)violations.push('Failure skip todo or runtime error');
if(report?.testResults.some(row=>row.status!=='passed'||row.message||row.testExecError))violations.push('Top-level file error');
if(report?.errors?.length||report?.unhandledErrors?.length)violations.push('Top-level runtime errors');
if(report?.testResults.some(row=>!files.includes(path.relative(root,row.name))))violations.push('Unexpected file selection');
fs.writeFileSync(path.join(out,`${label}-validation${validationOnly?'-corrected':''}.json`),JSON.stringify({kind,root,status:run.status,total:assertions.length,files:report?.testResults.length,passed:assertions.filter(row=>row.status==='passed').length,violations,assertions},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({label,total:assertions.length,violations}));
if(violations.length)process.exitCode=1;
