import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const out=path.dirname(new URL(import.meta.url).pathname),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
if(fs.existsSync(path.join(out,'manifest.sha256')))throw Error('Already sealed');
const r=read('wide-only/validation.json'),c=read('custody-final.json'),p=read('profile-inventory.json'),analysis=read('root-profile-analysis.json'),failures=r.assertions.filter(a=>a.status==='failed');if(!r.diagnosticValid||!r.exactSelection||r.total!==24||r.passed!==0||r.failed!==1||r.filtered!==23||r.recordCount!==3151||r.fulfilledOrdinaryIssues!==192||r.callbackSettled||!r.cleanupCompleted||r.incompletePhases.length!==129||failures.length!==1||!failures[0].failureMessages[0].startsWith('Error: Test timed out in 70000ms.'))throw Error('Exact diagnostic stop');if(!p.available||p.profiles.length!==2||analysis.profiles.length!==2)throw Error('Profiles unavailable');for(const v of p.profiles){if(!v.valid||hash(fs.readFileSync(path.join(out,v.file)))!==v.sha256||!analysis.profiles.some(a=>a.sha256===v.sha256&&a.pid===v.pid))throw Error('Profile identity');}
if(read('custody-final/status.json').code!==0||!read('wide-only/status.json').quiescent)throw Error('Final custody/quiescence');const execution=read('wide-only/execution-start.json'),pids=[execution.recorderPid,execution.childPid,...p.profiles.map(v=>v.pid)];for(const pid of new Set(pids)){const state=spawnSync('ps',['-p',String(pid),'-o','pid=,stat='],{encoding:'utf8'});if(![0,1].includes(state.status)||state.stdout.trim())throw Error('Owned runtime active');}
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]),statuses=walk(out).filter(f=>path.basename(f)==='status.json').sort().map(f=>({file:path.relative(out,f),...JSON.parse(fs.readFileSync(f))})),nonzero=statuses.filter(s=>(s.status??s.code)!==0).map(s=>({file:s.file,status:s.status??s.code}));if(JSON.stringify(nonzero)!==JSON.stringify([{file:'diagnostic-runtime/status.json',status:1},{file:'wide-only/status.json',status:1}]))throw Error('Unexpected captured status');
write('command-status-inventory.json',statuses);write('seal-summary.json',{stopped:true,diagnosticValid:true,profilesAvailable:true,semanticPass:false,parentClosed:false,head:c.head,total:24,passed:0,failed:1,filtered:23,reporterSha256:r.reporterSha256,records:r.recordCount,fulfilledOrdinaryIssues:r.fulfilledOrdinaryIssues,callbackSettled:false,cleanupCompleted:true,unmatched:129,profiles:p.profiles.map(({file,sha256,pid,role,sampleCount,timeDeltaSumMicros})=>({file,sha256,pid,role,sampleCount,timeDeltaSumMicros})),rootAnalysisSha256:hash(fs.readFileSync(path.join(out,'root-profile-analysis.json'))),capturedStatuses:statuses.length,nonzero,noRetry:true,noSourceChanges:true,priorStaticCreditedAtIdenticalBytes:true,wholeProgramStaticPass:false,knownExternalSnapshotDiagnostics:3,gridAndFourRegistryW0FailuresRemainOpen:true,custody:'custody-final.json',effectiveHashes:85,stashes:27,protectedPaths:86522,parentPatchSha256:c.patchSha256,ownedRuntimePidsAbsent:[...new Set(pids)]});
const files=walk(out).sort(),manifest=files.map(f=>hash(fs.readFileSync(f))+'  '+path.relative(out,f)).join('\n')+'\n';fs.writeFileSync(path.join(out,'manifest.sha256'),manifest,{flag:'wx'});console.log(JSON.stringify({entries:files.length,manifestSha256:hash(manifest),capturedStatuses:statuses.length,nonzero,stopped:true,profilesAvailable:true}));
