import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),dir=path.join(out,'wide-only'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),roster=read('runtime-roster.json'),status=read('wide-only/status.json'),errors=[],records=[],pairs=[],pending=new Map();
const stdout=fs.readFileSync(path.join(dir,'stdout.log'),'utf8');for(const line of stdout.split('\n'))if(line.includes('F5B_WIDE_DIAGNOSTIC')){try{const r=JSON.parse(line);if(r.kind!=='F5B_WIDE_DIAGNOSTIC')throw Error('Kind');records.push(r);}catch{errors.push('Malformed diagnostic JSON');}}
let issued=0,last;for(const r of records){if(r.sequence!==records.indexOf(r)+1||r.sequence>4096||r.writeFailures!==0||r.phase==='diagnostic-overflow')errors.push('Sequence/cap/write failure');for(const key of ['elapsedMs','cpuUserMicros','cpuSystemMicros','deltaUserMicros','deltaSystemMicros','eventLoopIdleMs','eventLoopActiveMs','eventLoopUtilization'])if(!Number.isFinite(r[key])||r[key]<0)errors.push('Invalid measurement '+key);if(r.eventLoopUtilization>1)errors.push('Invalid ELU');if(last&&['elapsedMs','cpuUserMicros','cpuSystemMicros','eventLoopIdleMs','eventLoopActiveMs'].some(k=>r[k]<last[k]))errors.push('Nonmonotonic measurement');if(r.phase==='ordinary-issue'&&r.edge==='end')issued++;if(r.completedOrdinaryIssues!==issued)errors.push('Fulfilled issue counter mismatch');const key=JSON.stringify([r.phase,r.peer]),queue=pending.get(key)??[];if(r.edge==='begin'){queue.push(r);pending.set(key,queue);}else if(r.edge==='end'||r.edge==='settled'){const begin=queue.shift();if(!begin)errors.push('End without begin '+key);else pairs.push({phase:r.phase,peer:r.peer,beginEpoch:begin.epoch,endEpoch:r.epoch,beginSequence:begin.sequence,endSequence:r.sequence,wallMs:r.elapsedMs-begin.elapsedMs,processUserMicros:r.cpuUserMicros-begin.cpuUserMicros,processSystemMicros:r.cpuSystemMicros-begin.cpuSystemMicros,eventLoopIdleMs:r.eventLoopIdleMs-begin.eventLoopIdleMs,eventLoopActiveMs:r.eventLoopActiveMs-begin.eventLoopActiveMs});}else errors.push('Unknown edge');last=r;}
if(!records.length||records[0].phase!=='callback'||records[0].edge!=='begin')errors.push('Missing callback start');
let report,assertions=[],reporterError;try{report=read('wide-only/focused.json');assertions=report.testResults.flatMap(s=>s.assertionResults.map(a=>({file:path.relative(root,s.name),...a})));}catch(e){reporterError=String(e);errors.push('Missing/broken complete reporter');}
const identity=a=>JSON.stringify([a.file,a.title,a.ancestorTitles,a.fullName]),exactNames=JSON.stringify(assertions.map(identity).sort())===JSON.stringify(roster.entries.map(identity).sort()),selected=assertions.filter(a=>a.fullName===roster.selectedFullName),filtered=assertions.filter(a=>a.fullName!==roster.selectedFullName),suiteErrors=report?.testResults.filter(s=>s.message||s.testExecError)??[];
const exactSelection=exactNames&&selected.length===1&&['passed','failed'].includes(selected[0].status)&&filtered.length===23&&filtered.every(a=>['pending','skipped'].includes(a.status)&&a.failureMessages.length===0)&&report.numTotalTests===24&&report.numPendingTests===23&&report.numPassedTests+report.numFailedTests===1;
const noTopErrors=!suiteErrors.length&&!report?.numRuntimeErrorTestSuites&&!report?.numUnhandledErrors&&!report?.unhandledErrors?.length;
if(exactSelection){const a=selected[0],passed=a.status==='passed';if(report.success!==passed||status.code!==(passed?0:1)||status.signal||status.spawnError||(passed?a.failureMessages.length!==0:a.failureMessages.length===0))errors.push('Reporter/exit/assertion consistency');}
const callback=records.find(r=>r.phase==='callback'&&r.edge==='settled'),cleanupEnd=records.find(r=>r.phase==='afterEach'&&r.edge==='end'),diagnosticValid=errors.length===0&&exactSelection&&noTopErrors&&status.quiescent&&!status.watchdogActions.length;
write('wide-only/validation.json',{diagnosticValid,errors,exactNames,exactSelection,noTopErrors,status,reporterError,reporterSha256:report&&hash(fs.readFileSync(path.join(dir,'focused.json'))),stdoutSha256:hash(Buffer.from(stdout)),stderrSha256:hash(fs.readFileSync(path.join(dir,'stderr.log'))),total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,filtered:report?.numPendingTests,success:report?.success,suiteErrors,assertions,recordCount:records.length,fulfilledOrdinaryIssues:issued,callbackSettled:Boolean(callback),callbackCompleted:callback?.completed??null,cleanupCompleted:Boolean(cleanupEnd),lastRecord:last,incompletePhases:[...pending.values()].flat(),pairs,cpuAttribution:'Process-aggregate readings; overlapping peer intervals are not exclusive CPU ownership',completionMeaning:'Fulfilled ordinary issues do not prove accounting assertions or whole callback completion',acceptanceClaim:false});
console.log(JSON.stringify({diagnosticValid,total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,filtered:report?.numPendingTests,records:records.length,fulfilledOrdinaryIssues:issued,callbackCompleted:callback?.completed??null,incompletePhases:[...pending.values()].flat().length,errors}));if(!diagnosticValid)process.exitCode=1;
