import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const out=path.dirname(new URL(import.meta.url).pathname),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
if(fs.existsSync(path.join(out,'manifest.sha256')))throw Error('Already sealed');
const result=read('wide-only/validation.json'),custody=read('custody-final.json'),failures=result.assertions.filter(a=>a.status==='failed');if(!result.diagnosticValid||!result.exactNames||!result.exactSelection||result.total!==24||result.passed!==0||result.failed!==1||result.filtered!==23||result.recordCount!==3546||result.fulfilledOrdinaryIssues!==256||result.callbackSettled||!result.cleanupCompleted||result.incompletePhases.length!==4||failures.length!==1||!failures[0].failureMessages[0].startsWith('Error: Test timed out in 70000ms.'))throw Error('Exact diagnostic stop');
if(read('custody-final/status.json').code!==0||read('typecheck-matrix-final/status.json').code!==0||!read('wide-only/status.json').quiescent)throw Error('Final gates');
const execution=read('wide-only/execution-start.json'),pids=[execution.recorderPid,execution.childPid];for(const pid of pids){const r=spawnSync('ps',['-p',String(pid),'-o','pid=,stat='],{encoding:'utf8'});if(![0,1].includes(r.status)||r.stdout.trim())throw Error('Owned process still active');}
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]),statuses=walk(out).filter(f=>path.basename(f)==='status.json').sort().map(f=>({file:path.relative(out,f),...JSON.parse(fs.readFileSync(f))})),nonzero=statuses.filter(s=>(s.status??s.code)!==0).map(s=>({file:s.file,status:s.status??s.code}));
const expected=[{file:'diagnostic-runtime/status.json',status:1},{file:'equivalence/status.json',status:1},{file:'typecheck-final/status.json',status:1},{file:'typecheck/status.json',status:1},{file:'wide-only/status.json',status:1}];if(JSON.stringify(nonzero)!==JSON.stringify(expected))throw Error('Unexpected status inventory '+JSON.stringify(nonzero));
write('command-status-inventory.json',statuses);write('seal-summary.json',{stopped:true,diagnosticValid:true,semanticPass:false,parentClosed:false,sourceHead:custody.head,sourceSha256:custody.testHashes['tests/phase-6b-d110c-0c1f5b-integration-red.test.ts'],total:24,passed:0,failed:1,filtered:23,reporterSha256:result.reporterSha256,records:result.recordCount,fulfilledOrdinaryIssues:result.fulfilledOrdinaryIssues,callbackSettled:false,cleanupCompleted:true,incompletePhases:result.incompletePhases,commands:statuses.length,nonzero,noRetry:true,noFull45:true,noIsolation:true,wholeProgramStaticPass:false,externalSnapshotDiagnostics:3,gridAndFourRegistryW0FailuresRemainOpen:true,custody:'custody-final.json',effectiveHashes:85,stashes:27,protectedPaths:86522,parentPatchSha256:custody.patchSha256,ownedRuntimePidsAbsent:pids});
const files=walk(out).sort(),manifest=files.map(f=>hash(fs.readFileSync(f))+'  '+path.relative(out,f)).join('\n')+'\n';fs.writeFileSync(path.join(out,'manifest.sha256'),manifest,{flag:'wx'});console.log(JSON.stringify({entries:files.length,manifestSha256:hash(manifest),commands:statuses.length,nonzero,stopped:true,diagnosticValid:true,semanticPass:false}));
