import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
const root=fs.realpathSync('/tmp/d110c-f5b-green-transport-static-z5iavL/checkout'),out=path.dirname(new URL(import.meta.url).pathname),parent=path.dirname(out),file='tests/phase-3a1b-p3-live-transport-red.test.ts',head='c5b5f36a3d3201633ae7bab1d9959ab52fa14526',hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),mainRoster=JSON.parse(fs.readFileSync(path.join(parent,'runtime-roster.json')));
function custody(){if(execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim()!==head)throw Error('HEAD drift');const c=read('custody-before.json');for(const[f,d]of Object.entries(c.sourceHashes))if(hash(fs.readFileSync(path.join(root,f)))!==d)throw Error('Source drift '+f);for(const[f,d]of Object.entries(c.runtimes))if(hash(fs.readFileSync(path.join(root,f)))!==d.sha256)throw Error('Runtime drift '+f);if(hash(fs.readFileSync(path.join(root,file)))!==mainRoster.testSha256)throw Error('Signed test drift');}
if(process.argv[2]==='freeze'){
 for(const label of ['install','custody-prepared','native-preparation-corrected','native-prebuild','native-addon-import','build','node-root-import','compiler-green','custody-before','graph-comparison'])if(read(label+'/status.json').code!==0)throw Error('Required isolated gate '+label);
 custody();const identity=read('program-identity.json');if(read('diagnostics.json').diagnosticCount!==0||identity.sources.find(s=>s.file===path.join(root,file))?.sha256!==mainRoster.testSha256||!read('graph-comparison.json').valid)throw Error('Compiler input proof');
 const command=[...mainRoster.command];command[command.length-1]='--outputFile='+path.join(out,'focused.json');write('runtime-roster.json',{...mainRoster,head,root,command,independentSourceBuilt:true,ownFrozenInstall:true,mainRosterSha256:hash(fs.readFileSync(path.join(parent,'runtime-roster.json')))});console.log(JSON.stringify({frozen:true,cases:24,sourceSha256:mainRoster.testSha256}));
}else if(process.argv[2]==='run'){
 custody();const roster=read('runtime-roster.json');write('execution-start.json',{head,pid:process.pid,startedAt:new Date().toISOString()});write('command.json',{cwd:root,command:roster.command});console.log(JSON.stringify({recorderPid:process.pid,soleIsolatedRuntime:true,cases:24}));
 const stdout=fs.openSync(path.join(out,'stdout.log'),'wx'),stderr=fs.openSync(path.join(out,'stderr.log'),'wx'),result=spawnSync(roster.command[0],roster.command.slice(1),{cwd:root,env:process.env,stdio:['ignore',stdout,stderr]});fs.closeSync(stdout);fs.closeSync(stderr);write('status.json',{status:result.status,signal:result.signal,error:result.error?.message,endedAt:new Date().toISOString()});
 const report=read('focused.json'),assertions=report.testResults.flatMap(s=>s.assertionResults.map(a=>({file:path.relative(root,s.name),...a}))),actual=assertions.map(a=>a.file+'\0'+[...a.ancestorTitles,a.title].join(' > ')).sort(),expected=roster.entries.map(a=>file+'\0'+[...a.ancestorTitles,a.title].join(' > ')).sort(),exactNames=JSON.stringify(actual)===JSON.stringify(expected),exactFiles=report.testResults.length===1&&path.relative(root,report.testResults[0].name)===file;
 const valid=result.status===0&&report.success===true&&exactNames&&exactFiles&&report.numTotalTests===24&&report.numPassedTests===24&&report.numFailedTests===0&&report.numPendingTests===0&&!report.numRuntimeErrorTestSuites&&!report.numUnhandledErrors&&!(report.unhandledErrors?.length)&&report.testResults.every(s=>!s.message&&!s.testExecError)&&assertions.every(a=>a.status==='passed'&&a.failureMessages.length===0);
 write('validation.json',{valid,exactNames,exactFiles,success:report.success,total:report.numTotalTests,passed:report.numPassedTests,failed:report.numFailedTests,skipped:report.numPendingTests,numRuntimeErrorTestSuites:report.numRuntimeErrorTestSuites??null,numUnhandledErrors:report.numUnhandledErrors??null,unhandledErrors:report.unhandledErrors??[],suites:report.testResults.map(s=>({file:s.name,message:s.message,testExecError:s.testExecError??null})),assertions,reporterSha256:hash(fs.readFileSync(path.join(out,'focused.json')))});console.log(JSON.stringify({valid,total:report.numTotalTests,passed:report.numPassedTests,failed:report.numFailedTests,skipped:report.numPendingTests}));if(!valid)process.exitCode=1;
}else throw Error('Unknown mode');
