import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import ts from '/Users/aristotle/Documents/Projects/ts-drp-1/node_modules/typescript/lib/typescript.js';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),fixtures=['creator-adoption-contract.ts','creator-successor-product-contract.ts'],file=n=>path.join(root,'tests/fixtures/phase-6a-v3',n),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),parse=(s,n='fixture.ts')=>ts.createSourceFile(n,s,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS),walk=n=>{const rows=[n];ts.forEachChild(n,c=>{rows.push(...walk(c))});return rows},tokens=s=>{const scan=ts.createScanner(ts.ScriptTarget.Latest,true,ts.LanguageVariant.Standard,s),rows=[];for(let k=scan.scan();k!==ts.SyntaxKind.EndOfFileToken;k=scan.scan())rows.push([k,scan.getTokenText()]);return rows},equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b),remove=(text,spans)=>spans.sort((a,b)=>b.start-a.start).reduce((s,p)=>s.slice(0,p.start)+s.slice(p.end),text);
const before=fixtures.map(n=>fs.readFileSync(path.join(out,n+'.before'),'utf8')),after=fixtures.map(n=>fs.readFileSync(file(n),'utf8')),parsed=parse(after[0]),nodes=walk(parsed),genericCalls=nodes.filter(n=>ts.isCallExpression(n)&&n.expression.getText(parsed)==='Object.freeze'&&n.typeArguments?.length),genericNames=genericCalls.map(n=>n.typeArguments[0].getText(parsed));
const expectedGenericNames=['AheDurableStore','SnapshotQuarantineStore<SnapshotVerificationReceipt>','SnapshotQuarantineScope<SnapshotVerificationReceipt>','SnapshotVerificationQuarantine','SnapshotQuarantinePort','DurableIssuanceStore','DurableLiveJournalStore'];if(!equal(genericNames,expectedGenericNames))throw Error('Seven exact contexts');
const newTypeNames=['SnapshotQuarantinePort','SnapshotVerificationQuarantine'],imports=nodes.filter(n=>ts.isImportSpecifier(n)&&newTypeNames.includes(n.name.text));if(imports.length!==2||imports.some(n=>!n.parent.parent.isTypeOnly))throw Error('Two type-only imports');
const delegates=nodes.filter(n=>ts.isPropertyAssignment(n)&&['readSettlementPlan','transactWriteSettlementPlan'].includes(n.name.getText(parsed)));if(delegates.length!==2)throw Error('Two delegates');
for(const d of delegates){const arrow=d.initializer,call=arrow.body,name=d.name.getText(parsed),expectedParameter=name==='readSettlementPlan'?'scope':'input';if(!ts.isArrowFunction(arrow)||arrow.parameters.length!==1||arrow.parameters[0].name.getText(parsed)!==expectedParameter||!ts.isCallExpression(call)||call.expression.getText(parsed)!=='rawIssuanceStore.'+name||call.arguments.length!==1||call.arguments[0].getText(parsed)!==expectedParameter||arrow.modifiers?.length)throw Error('Delegate must directly return actual receiver call with original argument');const owner=d.parent.parent.parent;if(!ts.isVariableDeclaration(owner)||owner.name.getText(parsed)!=='baseIssuanceStore')throw Error('Wrong delegate owner');}
const propertySpan=d=>({start:d.getFullStart(),end:d.end+(after[0][d.end]===','?1:0)}),delegateSpans=delegates.map(propertySpan),typeSpans=genericCalls.map(n=>({start:n.expression.end,end:n.typeArguments.end+1})),importSpans=imports.map(n=>({start:n.getFullStart(),end:n.end+(after[0][n.end]===','?1:0)}));
const assertions=nodes.filter(n=>ts.isAsExpression(n)&&n.expression.getText(parsed)==='Math.max(0, base.revision - 1)'&&n.type.getText(parsed)==='typeof base.revision');if(assertions.length!==1)throw Error('Exactly one localized brand assertion');
const stripped=remove(after[0],[...delegateSpans,...typeSpans,...importSpans,{start:assertions[0].expression.end,end:assertions[0].end}]);if(!equal(tokens(stripped),tokens(before[0])))throw Error('Adoption source outside authorized spans changed');
const oldIdentifier='return value !== undefined && ts.isIdentifier(unwrapExpression(value)) && unwrapExpression(value).text === name;',newIdentifier='const expression = value === undefined ? undefined : unwrapExpression(value);\n\treturn expression !== undefined && ts.isIdentifier(expression) && expression.text === name;',guard='\t\t\t\tts.isVariableDeclarationList(statement.initializer) &&\n';
if(after[1].split(newIdentifier).length!==2||after[1].split(guard).length!==2)throw Error('Exact two AST seams');const reverted=after[1].replace(newIdentifier,oldIdentifier).replace(guard,'');if(reverted!==before[1])throw Error('Product oracle outside two seams changed');
const options={...JSON.parse(fs.readFileSync(path.join(out,'diagnostics.json'))).options,noEmit:false,removeComments:true,sourceMap:false,inlineSourceMap:false,declaration:false,declarationMap:false};
const emit=s=>ts.transpileModule(s,{compilerOptions:options}).outputText,emittedBefore=before.map(emit),emittedAfter=after.map(emit),adoptionNoDelegates=emit(remove(after[0],delegateSpans));
const parenthesized='(Math.max(0, base.revision - 1))',parentheses=adoptionNoDelegates.split(parenthesized).length-1;if(parentheses>1)throw Error('Broad parenthesis normalization');const normalized=adoptionNoDelegates.replace(parenthesized,'Math.max(0, base.revision - 1)');if(!equal(tokens(normalized),tokens(emittedBefore[0]))||!equal(tokens(emit(reverted)),tokens(emittedBefore[1])))throw Error('Emitted behavior outside exact exceptions changed');
const revisionCases=[0,1,2,9,Number.MAX_SAFE_INTEGER].map(revision=>{const actual=Function('base','return '+assertions[0].expression.getText(parsed))({revision}),expected=Math.max(0,revision-1);if(actual!==expected)throw Error('Malformed numeric value changed');return{baseRevision:revision,actual,expected}});
const compiler=JSON.parse(fs.readFileSync(path.join(out,'program-identity.json'))),compiled=compiler.sources.find(s=>s.file===file(fixtures[0])),comment='\t\t\t\t\t\t// Preserve the intentionally invalid predecessor revision, including zero.\n',compiledComment='\t\t\t\t\t\t\t// Preserve the intentionally invalid predecessor revision, including zero.\n',reconstructed=after[0].replace(comment,'').replace('\t\t\t\t\t\t\t: { revision: Math.max(0, base.revision - 1) as typeof base.revision }),',compiledComment+'\t\t\t\t\t\t\t: { revision: Math.max(0, base.revision - 1) as typeof base.revision }),');if(hash(reconstructed)!==compiled.sha256||!equal(tokens(reconstructed),tokens(after[0])))throw Error('Postcompiler comment-only custody');
const require=createRequire(file(fixtures[1])),module={exports:{}},executable=ts.transpileModule(after[1].replace('import.meta.dirname',JSON.stringify(path.dirname(file(fixtures[1])))),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;Function('require','module','exports',executable)(require,module,module.exports);const inspect=module.exports.d108e5SourceOwnership,room=fs.readFileSync(path.join(root,'examples/v3-room/src/index.ts'),'utf8'),loop='for (const field of CREATOR_INVITE_BYTE_FIELDS)';if(room.split(loop).length!==2)throw Error('Unique declaration loop');const original=inspect(room),assignment=inspect(room.replace(loop,'for (field of CREATOR_INVITE_BYTE_FIELDS)'));if(original.migrationInviteBoundOwnsEveryEncode!==true||assignment.migrationInviteBoundOwnsEveryEncode!==false)throw Error('Real exported loop boundary');
const replaceOnce=(source,a,b)=>{if(source.split(a).length!==2)throw Error('Mutant seam');return source.replace(a,b)},mutants=[
 ['dead-snapshot',replaceOnce(room,'\t\treturn boundedMigrationCreatorInvite(value);','\t\tconst ignoredBoundedInvite = (): unknown => boundedMigrationCreatorInvite(value);\n\t\tvoid ignoredBoundedInvite;\n\t\treturn value;')],
 ['dead-rehearsal',replaceOnce(room,'\t\tconst targetMaterial = decodeCreatorInvite(boundedMigrationCreatorInvite(targetInviteValue));','\t\tconst ignoredBoundedInvite = (): unknown =>\n\t\t\tdecodeCreatorInvite(boundedMigrationCreatorInvite(targetInviteValue));\n\t\tvoid ignoredBoundedInvite;\n\t\tconst targetMaterial = decodeCreatorInvite(targetInviteValue);')],
 ['alternate-activation',replaceOnce(room,'\t\tconst targetCreatorInvite = decodeCreatorInvite(boundedMigrationCreatorInvite(targetInviteValue));','\t\tconst targetCreatorInvite = true\n\t\t\t? decodeCreatorInvite(boundedMigrationCreatorInvite(targetInviteValue))\n\t\t\t: decodeCreatorInvite(targetInviteValue);')],
 ['dead-metadata',replaceOnce(replaceOnce(room,'\t\tconst fields = exactRecord(value, CREATOR_INVITE_MATERIAL_KEYS);','\t\tconst ignoredExactRecord = (): unknown => exactRecord(value, CREATOR_INVITE_MATERIAL_KEYS);\n\t\tvoid ignoredExactRecord;\n\t\tconst fields = value as Readonly<Record<string, unknown>>;'),'\t\t\t\tbyteLength = Reflect.apply(INTRINSIC_TYPED_ARRAY_BYTE_LENGTH_GETTER, fieldValue, []);','\t\t\t\tconst ignoredByteLength = (): unknown =>\n\t\t\t\t\tReflect.apply(INTRINSIC_TYPED_ARRAY_BYTE_LENGTH_GETTER, fieldValue, []);\n\t\t\t\tvoid ignoredByteLength;\n\t\t\t\tbyteLength = 1;')]
].map(([name,source])=>({name,result:inspect(source)}));if(mutants.some(m=>m.result.migrationInviteBoundOwnsEveryEncode!==false))throw Error('Existing migration mutant accepted');
const result={valid:true,files:fixtures.map((n,i)=>({file:file(n),beforeSha256:hash(before[i]),afterSha256:hash(after[i]),emittedBeforeSha256:hash(emittedBefore[i]),emittedAfterSha256:hash(emittedAfter[i])})),contextArguments:genericNames,newTypeImports:newTypeNames,directDelegates:delegates.map(d=>({name:d.name.getText(parsed),exactSource:d.getText(parsed),originalArgumentAndReturnedCallResult:true,receiver:'rawIssuanceStore',noAddedHooks:true})),localizedRevisionCases:revisionCases,adoptionUnaffectedEmittedTokensExact:true,productUnaffectedEmittedTokensExact:true,normalizedOnlyMalformedRevisionParentheses:parentheses,compilerInputCommentRelocationOnly:true,originalDeclarationLoop:original,assignmentLoop:assignment,existingMigrationMutants:mutants,realExportedInspector:true,onlyImportMetaDirectorySubstitutedForCommonJsEvaluation:true,noRoomOrStoreRuntimeInvoked:true,blanketExecutableEquivalence:false};
fs.writeFileSync(path.join(out,'equivalence.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({valid:true,contexts:7,directDelegates:2,zeroRevisionPreserved:revisionCases[0].actual===0,declarationAccepted:true,assignmentRejected:true,migrationMutantsRejected:mutants.length}));
