import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync,execFileSync} from 'node:child_process';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),read=f=>JSON.parse(fs.readFileSync(f)),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),write=(f,v)=>fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n',{flag:'wx'}),head='393eda6762b8f1df44c346fe7a17ccd5db6ab3be',rosterSource=path.join(root,'.logs/d110c-0c1f5b-red-adoption-static-f17a180e/future-combined-roster.json');
if(process.argv[2]==='freeze'){
 const prior=read(rosterSource),before=read(path.join(out,'custody-before.json')),equivalence=read(path.join(out,'equivalence-final.json'));if(!equivalence.valid||prior.files!==12||prior.total!==78||prior.entries.length!==78)throw Error('Frozen roster');
 const files=prior.sourceFiles.map(v=>v.file);for(const r of prior.sourceFiles)if(hash(fs.readFileSync(path.join(root,r.file)))!==r.sha256)throw Error('Consumer drift '+r.file);
 const fixtureHashes=Object.fromEntries(equivalence.files.map(v=>[path.relative(root,v.file),v.afterSha256]));
 const command=['pnpm','exec','vitest','run',...files,'--no-file-parallelism','--coverage.enabled=false','--reporter=default','--reporter=json','--outputFile='+path.join(out,'main-78','focused.json')];
 write(path.join(out,'runtime-roster.json'),{head,source:rosterSource,sourceSha256:hash(fs.readFileSync(rosterSource)),files,entries:prior.entries,expected:{total:78,passed:78,failed:0,skipped:0},command,ownerHashes:before.ownerHashes,built:before.built,testHashes:before.testHashes,fixtureHashes,consumerHashes:Object.fromEntries(prior.sourceFiles.map(v=>[v.file,v.sha256])),expectedObservations:read(path.join(root,'.logs/d110c-0c1f5b-green-room-guard-db8a8615/focused-13/observations.json')).expected,noCollection:true});console.log(JSON.stringify({frozen:true,files:12,total:78}));
}else if(process.argv[2]==='run'){
 const roster=read(path.join(out,'runtime-roster.json'));if(execFileSync('git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).trim()!==head)throw Error('HEAD drift');
 for(const label of ['compiler-green','fixture-format-final','fixture-lint-final','fixture-diff','emitted-equivalence-final'])if(read(path.join(out,label,'status.json')).status!==0)throw Error('Static gate '+label);
 for(const records of [roster.ownerHashes,roster.built,{...roster.testHashes,...roster.fixtureHashes,...roster.consumerHashes}])for(const[f,h]of Object.entries(records))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Custody drift '+f);
 const dir=path.join(out,'main-78');fs.mkdirSync(dir);write(path.join(dir,'command.json'),{cwd:root,command:roster.command});write(path.join(dir,'execution-start.json'),{head,recorderPid:process.pid,startedAt:new Date().toISOString(),executionCount:1});console.log(JSON.stringify({label:'main-78',recorderPid:process.pid}));
 const stdout=fs.openSync(path.join(dir,'stdout.log'),'wx'),stderr=fs.openSync(path.join(dir,'stderr.log'),'wx'),r=spawnSync(roster.command[0],roster.command.slice(1),{cwd:root,env:process.env,stdio:['ignore',stdout,stderr]});fs.closeSync(stdout);fs.closeSync(stderr);write(path.join(dir,'status.json'),{status:r.status,signal:r.signal,error:r.error?.message,endedAt:new Date().toISOString()});
 const report=fs.existsSync(path.join(dir,'focused.json'))?read(path.join(dir,'focused.json')):null,assertions=report?.testResults.flatMap(s=>s.assertionResults.map(a=>({file:path.relative(root,s.name),...a})))??[],key=a=>a.file+'\0'+[...a.ancestorTitles,a.title].join(' > '),actual=assertions.map(key).sort(),expected=roster.entries.map(key).sort(),exactNames=JSON.stringify(actual)===JSON.stringify(expected),exactFiles=JSON.stringify(report?.testResults.map(s=>path.relative(root,s.name)).sort())===JSON.stringify([...roster.files].sort());
 const lines=fs.readFileSync(path.join(dir,'stdout.log'),'utf8').split('\n').map(l=>l.trim()).filter(l=>l.startsWith('{"kind":"F5B_ROOM_GUARD_OBSERVATIONS"')),observations=lines.length===1?JSON.parse(lines[0]).observations:[],observationsValid=lines.length===1&&JSON.stringify(observations)===JSON.stringify(roster.expectedObservations);
 const valid=r.status===0&&!r.signal&&report?.success===true&&exactNames&&exactFiles&&report.numTotalTests===78&&report.numPassedTests===78&&report.numFailedTests===0&&report.numPendingTests===0&&!report.numRuntimeErrorTestSuites&&!report.numUnhandledErrors&&!(report.unhandledErrors?.length)&&report.testResults.every(s=>!s.message&&!s.testExecError)&&assertions.every(a=>a.status==='passed'&&a.failureMessages.length===0)&&observationsValid;
 write(path.join(dir,'validation.json'),{valid,exactNames,exactFiles,observationsValid,rawObservationCount:lines.length,observations,success:report?.success,total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,skipped:report?.numPendingTests,numRuntimeErrorTestSuites:report?.numRuntimeErrorTestSuites??null,numUnhandledErrors:report?.numUnhandledErrors??null,unhandledErrors:report?.unhandledErrors??[],suites:report?.testResults.map(s=>({file:s.name,message:s.message,testExecError:s.testExecError??null})),assertions,reporterSha256:report?hash(fs.readFileSync(path.join(dir,'focused.json'))):null});console.log(JSON.stringify({valid,total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,skipped:report?.numPendingTests,observationsValid}));if(!valid)process.exitCode=1;
}else throw Error('Unknown mode');
