import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import ts from 'typescript';
import YAML from 'yaml';
const cwd=process.argv[2];
const git=(...args)=>execFileSync('git',['-C',cwd,...args],{encoding:'utf8'});
const read=p=>readFileSync(`${cwd}/${p}`,'utf8');
const hash=s=>createHash('sha256').update(s).digest('hex');
const baseline='9876d733';
const paths=['examples/v3-room/package.json','examples/v3-room/src/index.ts','packages/issuance-store/src/conformance.ts','packages/issuance-store/src/contract.ts','packages/issuance-store/src/types.ts','packages/node/src/v3-live.ts','packages/storage-browser/src/internal/browser-issuance-store.ts','packages/storage-node/src/internal/node-issuance-store.ts','pnpm-lock.yaml'];
assert.deepEqual(git('diff','--name-only',baseline).trim().split('\n').sort(),paths.toSorted());
const printer=ts.createPrinter({removeComments:true});
function publicShapes(p,source) {
 const file=ts.createSourceFile(p,source,ts.ScriptTarget.Latest,true);
 return file.statements.filter(s=>s.modifiers?.some(m=>m.kind===ts.SyntaxKind.ExportKeyword)).map(s=>{
  const selected=ts.isFunctionDeclaration(s) ? ts.factory.updateFunctionDeclaration(s,s.modifiers,s.asteriskToken,s.name,s.typeParameters,s.parameters,s.type,undefined) : s;
  return printer.printNode(ts.EmitHint.Unspecified,selected,file);
 });
}
for(const p of ['packages/node/src/v3-live.ts','examples/v3-room/src/index.ts']) assert.deepEqual(publicShapes(p,read(p)),publicShapes(p,git('show',`${baseline}:${p}`)),`public surface changed ${p}`);
const before=YAML.parse(git('show',`${baseline}:pnpm-lock.yaml`));
const after=YAML.parse(read('pnpm-lock.yaml'));
assert.deepEqual(after.importers['examples/v3-room'].dependencies['@ts-drp/issuance-store'],{specifier:'workspace:*',version:'link:../../packages/issuance-store'});
delete after.importers['examples/v3-room'].dependencies['@ts-drp/issuance-store'];
assert.deepEqual(after,before);
const room=read('examples/v3-room/src/index.ts');
const recovery=room.slice(room.indexOf('const recoverSettlementOwner ='),room.indexOf('const issueSettlement ='));
assert(!recovery.includes('enqueueLifetimeTransition'));
assert(recovery.indexOf('predecessor.deactivate()')<recovery.indexOf('recoverStartupPlane()'));
assert(recovery.indexOf('bindCurrentCreatorClose?.(activeHandle)')<recovery.indexOf('predecessorClose.stop()'));
const rebase=room.slice(room.indexOf('const rebasePromise ='),room.indexOf('void rebasePromise.catch'));
assert.equal(rebase.split('enqueueLifetimeTransition(').length-1,1);
assert(rebase.includes('await shutdown()'));
assert(!room.includes('progress-advanced'));
const replay=room.slice(room.indexOf('startupReplay = [];'),room.indexOf('if (input.creatorFinalitySigner !== undefined && input.successorSnapshotDeclaration === undefined)',room.indexOf('startupReplay = [];')));
assert(replay.indexOf('successorAuthority(')<replay.indexOf('await commit(replay)'));
assert(replay.indexOf('sameBytes(projectedStateBytes, exactCanonicalApplicationStateBytes)')<replay.indexOf('await commit(replay)'));
const node=read('packages/node/src/v3-live.ts');
const delivery=node.slice(node.indexOf('const deliveries = creatorSuccessorRecoveredDeliveries.get'),node.indexOf('if (!installCreatorSuccessorHandleAlias'));
assert(delivery.indexOf('await bindings.onAdmittedVertex')<delivery.indexOf('material.terminalizeSource()'));
assert(delivery.includes('await Promise.resolve(activated.handle.deactivate())'));
for(const p of paths.filter(p=>p.includes('internal/'))) assert(read(p).includes('JSON.stringify(cloneSettlementPlan(plan)) !== JSON.stringify(cloneSettlementPlan(expectedPlan))'));
const stashes=git('stash','list','--format=%H');
assert.equal(stashes.trim().split('\n').length,27);
const tests=['tests/phase-6b-d110c-0c1f5b0t-settlement-progress-red.test.ts','tests/phase-6b-d110c-0c1f5b0c-room-red.test.ts','tests/phase-6b-d110c-0c1f5b0u-store-red.test.ts','tests/phase-6b-d110c-0c1f5b0u-room-runtime-red.test.ts','tests/phase-6b-d110c-0c1f5b0u-successor-replay-red.test.ts'];
for(const p of tests) assert.equal(read(p),git('show',`${baseline}:${p}`));
console.log(JSON.stringify({baseline,head:git('rev-parse','HEAD').trim(),paths:Object.fromEntries(paths.map(p=>[p,hash(read(p))])),tests:Object.fromEntries(tests.map(p=>[p,hash(read(p))])),publicShapes:'unchanged Node/room',lockfile:'only authorized workspace importer',sourceShape:'passed',stashCount:27,stashHash:hash(stashes)},null,2));
