import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import ts from '/Users/aristotle/Documents/Projects/ts-drp-1/node_modules/typescript/lib/typescript.js';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),file='tests/phase-3a1b-p3-live-transport-red.test.ts',red=path.join(root,'.logs/d110c-0c1f5b-red-transport-static-63e42eef'),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),write=(f,v)=>fs.writeFileSync(path.join(out,f),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const before=fs.readFileSync(path.join(out,path.basename(file)+'.before'),'utf8'),after=fs.readFileSync(path.join(root,file),'utf8'),frozen=JSON.parse(fs.readFileSync(path.join(red,'frozen-oracles.json')));
const parse=s=>{const u=ts.createSourceFile(file,s,ts.ScriptTarget.Latest,true);if(u.parseDiagnostics.length)throw Error('Parse diagnostics');return u},old=parse(before),unit=parse(after),visit=(n,f)=>{f(n);ts.forEachChild(n,c=>visit(c,f))},tokens=(n,u)=>{const a=[];function walk(c){const kids=c.getChildren(u);if(kids.length===0)a.push([c.kind,c.getText(u)]);else kids.forEach(walk)}walk(n);return JSON.stringify(a)},equal=(a,b,label)=>{if(JSON.stringify(a)!==JSON.stringify(b))throw Error(label)};
equal(hash(before),frozen.testSha256,'Original frozen source');
const edits=[],erasures=new Map(),casts=[],callbacks=[],rejectors=[],guardText='node.initializer !== undefined &&',methodCounts={activateV3LivePlane:0,routeV3Ingress:0};
const tupleType='readonly[NonNullable<Parameters<DurableIssuanceStore["readOutboxPage"]>[0]>]|undefined',query='../packages/node/src/internal/v3-topic.js?d108e2c-hostile-text-encoder';
visit(unit,n=>{
 if(ts.isAsExpression(n)){
  const type=n.type.getText(unit).replace(/\s/gu,'').replace(/^\|/u,''),expr=n.expression.getText(unit),method=/^surface\.(activateV3LivePlane|routeV3Ingress)$/u.exec(expr);
  let accepted=false;
  if(method&&type===`NonNullable<typeofsurface.${method[1]}>`){methodCounts[method[1]]++;accepted=true;}
  if(/^readOutboxPage\.mock\.calls\[[01]\]$/u.test(expr)&&type===tupleType)accepted=true;
  if(ts.isStringLiteral(n.expression)&&n.expression.text===query&&n.type.kind===ts.SyntaxKind.StringKeyword)accepted=true;
  if(accepted){const owner=ts.isParenthesizedExpression(n.parent)?n.parent:n;erasures.set(owner,n.expression);edits.push({start:owner.getStart(unit),end:owner.end,text:expr,kind:'type-cast'});casts.push({expression:expr,type:n.type.getText(unit),start:owner.getStart(unit)});}
 }
 if(ts.isArrowFunction(n)&&n.type?.kind===ts.SyntaxKind.NumberKeyword&&ts.isCallExpression(n.body)&&n.body.expression.getText(unit)==='effects.push'&&['"queue.subscribe"','"queue.close"'].includes(n.body.arguments[0]?.getText(unit))){edits.push({start:n.type.getStart(unit),end:n.type.end,text:'void',kind:'return-type'});callbacks.push(n.getText(unit));}
 if(ts.isPropertyAssignment(n)&&['readSettlementPlan','transactWriteSettlementPlan','installEpochAnchor'].includes(n.name.getText(unit))){rejectors.push(n);let end=n.end;while(/\s/u.test(after[end]??''))end++;if(after[end]!==',')throw Error('Rejector comma');edits.push({start:n.getStart(unit),end:end+1,text:'',kind:'rejector'});}
});
equal(methodCounts,{activateV3LivePlane:4,routeV3Ingress:1},'Five method casts');equal(casts.length,8,'Exactly eight authorized casts');equal(callbacks.length,2,'Two return annotations');equal(rejectors.map(n=>n.name.getText(unit)).sort(),['installEpochAnchor','readSettlementPlan','transactWriteSettlementPlan'],'Three rejectors');
const guard=after.indexOf(guardText);if(guard<0||after.indexOf(guardText,guard+1)!==-1)throw Error('Single initializer guard');edits.push({start:guard,end:guard+guardText.length,text:'',kind:'initializer-guard'});
let restored=after;for(const e of [...edits].sort((a,b)=>b.start-a.start))restored=restored.slice(0,e.start)+e.text+restored.slice(e.end);
equal(tokens(parse(restored),parse(restored)),tokens(old,old),'Exact full source outside frozen spans');
const runtimeEdits=edits.filter(e=>e.kind==='rejector'||e.kind==='initializer-guard');let erased=after;for(const e of [...runtimeEdits].sort((a,b)=>b.start-a.start))erased=erased.slice(0,e.start)+e.text+erased.slice(e.end);
const emit=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText,oldJS=emit(before),newJS=emit(erased),actualJS=emit(after);
const oldJSUnit=parse(oldJS),newJSUnit=parse(newJS);equal(tokens(oldJSUnit,oldJSUnit),tokens(newJSUnit,newJSUnit),'Emitted executable identity outside three rejectors and guard');
write('emitted-before.js',oldJS);write('emitted-after.js',actualJS);
function tree(n,u){if(erasures.has(n))return tree(erasures.get(n),u);const kids=n.getChildren(u);return {kind:ts.SyntaxKind[n.kind],text:kids.length===0?n.getText(u):undefined,children:kids.map(c=>tree(c,u))};}
const assertion=n=>ts.isExpressionStatement(n)&&/^(?:await )?expect(?:\(|ClosedFrozenActivationFailure\()/u.test(n.getText(n.getSourceFile())),collect=u=>{const all=[],subset=[],titles=[];visit(u,n=>{if(assertion(n))all.push(tree(n,u));if(ts.isCallExpression(n)&&ts.isIdentifier(n.expression)&&n.expression.text==='it'&&ts.isStringLiteral(n.arguments[0])){titles.push(n.arguments[0].text);if(frozen.acceptedRuntimeSubsetTitles.includes(n.arguments[0].text))visit(n.arguments[1].body,c=>{if(assertion(c))subset.push(tree(c,u))});}});return{all,subset,titles};};
const a=collect(old),b=collect(unit);equal(a.all,frozen.allAssertions.map(n=>n.tree),'Frozen full assertion trees');equal(a.all,b.all,'295 semantic assertions');equal(a.subset,b.subset,'123 semantic subset');equal(a.titles,b.titles,'24 titles');equal([b.all.length,b.subset.length,b.titles.length],[295,123,24],'Frozen exact counts');
const require=createRequire(fs.realpathSync(path.join(root,'node_modules/vitest/package.json'))),spyPath=require.resolve('@vitest/spy'),{fn}=await import(pathToFileURL(spyPath).href),vi={fn};
const evaluate=(s,names,values)=>new Function(...names,'return ('+emit('const evaluated = '+s).replace(/^const evaluated = /u,'').trim().replace(/;$/u,'')+');')(...values);
const rejections=[];for(const p of rejectors){const name=p.name.getText(unit),mock=evaluate(p.initializer.getText(unit),['vi'],[vi]);let error;try{await mock()}catch(e){error=e}if(!(error instanceof Error)||error.message!==`unexpected ${name} in transport fixture`||mock.mock.calls.length!==1)throw Error('Rejector '+name);rejections.push({method:name,error:error.message,calls:1});}
const declarations=Object.fromEntries(unit.statements.filter(ts.isFunctionDeclaration).map(n=>[n.name.text,n]));
const issuance=evaluate(declarations.fakeIssuanceStore.getText(unit),['vi'],[vi]);const overrideRead=fn(()=>Promise.reject(new Error('override read'))),overrideWrite=fn(()=>Promise.reject(new Error('override write'))),overridden=issuance({readSettlementPlan:overrideRead,transactWriteSettlementPlan:overrideWrite});if(overridden.readSettlementPlan!==overrideRead||overridden.transactWriteSettlementPlan!==overrideWrite)throw Error('Override identity');
for(const[name,expected]of [['readSettlementPlan','override read'],['transactWriteSettlementPlan','override write']]){let error;try{await overridden[name]()}catch(e){error=e}if(error?.message!==expected)throw Error('Override precedence');}
const helperCode=['topLevelFunction','activationOrderingEvidence'].map(n=>declarations[n].getText(unit)).join('\n'),helpers=ts.transpileModule(helperCode,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,inspect=new Function('ts',helpers+'\nreturn activationOrderingEvidence;')(ts);
const initializerControls=[];for(const[declaration,expected]of [['const {capability} = input;', ['capability']],['let uninitialized;',[]],['const {capability} = other;',[]]]){const input=`function activateV3LivePlane(input) { ${declaration} const recovered = consumeRecoveredV3Live(input); }`,result=inspect(input);equal(result.outerCapturedKeys,expected,'Initializer nonmatch');initializerControls.push({declaration,outerCapturedKeys:result.outerCapturedKeys});}
const live=fs.readFileSync(path.join(root,'packages/node/src/v3-live.ts'),'utf8'),actualInspection=inspect(live);if(actualInspection.consumeCount!==1)throw Error('Actual source inspection');
const optionalControls=[];for(const c of casts.filter(c=>c.expression.startsWith('readOutboxPage.'))){const castNode=[...erasures].find(([n])=>n.getStart(unit)===c.start)[0];let outer=castNode;while(outer.parent&&(ts.isElementAccessExpression(outer.parent)||ts.isPropertyAccessExpression(outer.parent)))outer=outer.parent;const source=outer.getText(unit),execute=evaluate('(readOutboxPage) => '+source,[],[]),index=c.expression.includes('[0]')?0:1;
 for(const[kind,tuple]of [['absent',undefined],['empty',[]],['missing',[undefined]],['valid',[{scope:'scope-value'}]]]){const calls=[];calls[index]=tuple;let result,error;try{result=execute({mock:{calls}})}catch(e){error=e.name}if(kind==='absent'&&(result!==undefined||error)||['empty','missing'].includes(kind)&&error!=='TypeError'||kind==='valid'&&(result!=='scope-value'||error))throw Error('Optional-chain behavior');optionalControls.push({index,kind,result,error});}}
const receiverControls=[];for(const c of casts.filter(c=>c.expression.startsWith('surface.'))){const method=c.expression.slice(8),castNode=[...erasures].find(([n])=>n.getStart(unit)===c.start)[0],call=castNode.parent;if(!ts.isCallExpression(call)||call.expression!==castNode)throw Error('Call receiver shape');let gets=0,calls=0;const surface={get [method](){gets++;return function(...args){calls++;if(this!==surface||args.length!==2||args[0]!=='a'||args[1]!=='b')throw Error('Receiver/args');return 'result';}}};const invoke=evaluate('(surface) => '+castNode.getText(unit)+'("a", "b")',[],[]);if(invoke(surface)!=='result'||gets!==1||calls!==1)throw Error('Getter receiver');receiverControls.push({method,getterReads:gets,calls,originalReceiver:true});}
write('equivalence.json',{valid:true,beforeSha256:hash(before),afterSha256:hash(after),exactSourceOutsideFrozenSpans:true,emittedOutsideThreeRejectorsAndGuardEqual:true,allSemanticAssertions:295,acceptedSubset:123,titles:24,casts,callbacks,rejections,overridesLastAndExact:true,spyModule:{file:spyPath,sha256:hash(fs.readFileSync(spyPath))},initializerControls,actualInspection,liveSourceSha256:hash(live),optionalControls,receiverControls,initialTypeOnlySyntaxStopPreserved:true});
console.log(JSON.stringify({valid:true,assertions:295,subset:123,titles:24,rejectors:3,receiverControls:5,optionalControls:8}));
