import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),dir=path.join(out,'main-24'),file='tests/phase-3a1b-p3-live-transport-red.test.ts',head='9ae0b4a88d789c2d8a01ac5b155611da09529869',hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:128*1024*1024}).trim();
function custody(){if(git('rev-parse','HEAD')!==head||git('log','-1','--format=%G?')!=='G')throw Error('Signed release drift');const c=read('custody-before.json');for(const map of [c.ownerHashes,c.built,c.testHashes])for(const[f,d]of Object.entries(map))if(f!==file&&hash(fs.readFileSync(path.join(root,f)))!==d)throw Error('Source/runtime drift '+f);const patch=execFileSync('git',['diff','--binary','--full-index','--',...Object.keys(c.ownerHashes)],{cwd:root,maxBuffer:128*1024*1024});if(hash(patch)!==c.patchSha256)throw Error('Patch drift');if(hash(fs.readFileSync(path.join(root,file)))!==read('equivalence.json').afterSha256||hash(fs.readFileSync(path.join(root,file)))!==read('query-transform.json').sourceSha256)throw Error('Target proof drift');}
if(process.argv[2]==='freeze'){
 custody();for(const label of ['format-corrected','lint-corrected','diff-corrected','compiler-corrected','equivalence','query-transform'])if(read(label+'/status.json').code!==0)throw Error('Gate failed '+label);
 const compiler=read('corrected/program-identity.json'),current=hash(fs.readFileSync(path.join(root,file)));if(compiler.sources.find(s=>s.file===path.join(root,file))?.sha256!==current||read('corrected/diagnostics.json').diagnosticCount!==0)throw Error('Final compiler identity');
 const frozen=JSON.parse(fs.readFileSync(path.join(root,'.logs/d110c-0c1f5b-red-transport-static-63e42eef/frozen-oracles.json')));if(frozen.entries.length!==24)throw Error('Frozen roster');fs.mkdirSync(dir);
 write('runtime-roster.json',{head,file,testSha256:current,entries:frozen.entries,allAssertions:295,subsetAssertions:123,collectionRepeated:false,expected:{total:24,passed:24,failed:0,skipped:0},command:['pnpm','exec','vitest','run',file,'--no-file-parallelism','--coverage.enabled=false','--reporter=default','--reporter=json','--outputFile='+path.join(dir,'focused.json')]});console.log(JSON.stringify({frozen:true,files:1,cases:24,sourceSha256:current}));
}else if(process.argv[2]==='run'){
 custody();const roster=read('runtime-roster.json');if(hash(fs.readFileSync(path.join(root,file)))!==roster.testSha256)throw Error('Frozen target drift');write('main-24/execution-start.json',{head,pid:process.pid,startedAt:new Date().toISOString()});write('main-24/command.json',{cwd:root,command:roster.command});console.log(JSON.stringify({recorderPid:process.pid,soleRuntime:true,cases:24}));
 const stdout=fs.openSync(path.join(dir,'stdout.log'),'wx'),stderr=fs.openSync(path.join(dir,'stderr.log'),'wx'),result=spawnSync(roster.command[0],roster.command.slice(1),{cwd:root,env:process.env,stdio:['ignore',stdout,stderr]});fs.closeSync(stdout);fs.closeSync(stderr);write('main-24/status.json',{status:result.status,signal:result.signal,error:result.error?.message,endedAt:new Date().toISOString()});
 const report=read('main-24/focused.json'),assertions=report.testResults.flatMap(s=>s.assertionResults.map(a=>({file:path.relative(root,s.name),...a}))),actual=assertions.map(a=>a.file+'\0'+[...a.ancestorTitles,a.title].join(' > ')).sort(),expected=roster.entries.map(a=>file+'\0'+[...a.ancestorTitles,a.title].join(' > ')).sort();
 const exactNames=JSON.stringify(actual)===JSON.stringify(expected),exactFiles=report.testResults.length===1&&path.relative(root,report.testResults[0].name)===file,valid=result.status===0&&report.success===true&&exactNames&&exactFiles&&report.numTotalTests===24&&report.numPassedTests===24&&report.numFailedTests===0&&report.numPendingTests===0&&!report.numRuntimeErrorTestSuites&&!report.numUnhandledErrors&&!(report.unhandledErrors?.length)&&report.testResults.every(s=>!s.message&&!s.testExecError)&&assertions.every(a=>a.status==='passed'&&a.failureMessages.length===0);
 write('main-24/validation.json',{valid,exactNames,exactFiles,success:report.success,total:report.numTotalTests,passed:report.numPassedTests,failed:report.numFailedTests,skipped:report.numPendingTests,numRuntimeErrorTestSuites:report.numRuntimeErrorTestSuites??null,numUnhandledErrors:report.numUnhandledErrors??null,unhandledErrors:report.unhandledErrors??[],suites:report.testResults.map(s=>({file:s.name,message:s.message,testExecError:s.testExecError??null})),assertions,reporterSha256:hash(fs.readFileSync(path.join(dir,'focused.json')))});console.log(JSON.stringify({valid,total:report.numTotalTests,passed:report.numPassedTests,failed:report.numFailedTests,skipped:report.numPendingTests}));if(!valid)process.exitCode=1;
}else throw Error('Unknown mode');
