import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import ts from '/private/tmp/d110c-f5b-green-replay-budget-zIt6Xr/checkout/node_modules/typescript/lib/typescript.js';
const root='/private/tmp/d110c-f5b-green-replay-budget-zIt6Xr/checkout',out=path.dirname(new URL(import.meta.url).pathname),file='tests/phase-5d-pacemaker-red.test.ts',title='replays every checked trace through the genuine voter, pacemaker, and fake-IDB store',hash=b=>crypto.createHash('sha256').update(b).digest('hex'),before=fs.readFileSync(path.join(path.dirname(out),'source-before.ts'),'utf8'),after=fs.readFileSync(path.join(root,file),'utf8');
function inspect(text){const unit=ts.createSourceFile(file,text,ts.ScriptTarget.Latest,true),calls=[],bodies=[];function scan(n){if(ts.isCallExpression(n)&&n.arguments[0]&&ts.isStringLiteral(n.arguments[0])&&n.arguments[0].text===title)calls.push(n);if(ts.isFunctionLike(n)&&n.body)bodies.push({start:n.body.pos,end:n.body.end,text:n.body.getText(unit)});ts.forEachChild(n,scan)}scan(unit);if(calls.length!==1)throw Error('Unique registration');return{unit,call:calls[0],bodies:bodies.filter(b=>!(b.start<calls[0].pos&&b.end>calls[0].end)).map(b=>b.text)}}
const a=inspect(before),b=inspect(after);if(a.call.arguments.length!==2||b.call.arguments.length!==3||b.call.arguments[2].getText(b.unit)!=='20_000')throw Error('Only third scalar');
for(let i=0;i<2;i++)if(a.call.arguments[i].getText(a.unit)!==b.call.arguments[i].getText(b.unit))throw Error('Original args');
if(a.call.expression.getText(a.unit)!==b.call.expression.getText(b.unit)||JSON.stringify(a.bodies)!==JSON.stringify(b.bodies))throw Error('Bodies/predicate');
const bodySha256=hash(a.call.arguments[1].body.getText(a.unit));if(bodySha256!=='f3c51b5f029dff7d496528157f04b1b5bc550b5a149dadd35aaba530675c0e41')throw Error('Accepted callback hash');
const added=after.slice(b.call.arguments[1].end,b.call.arguments[2].end);if(!/^,\s*20_000$/u.test(added)||after.slice(0,b.call.arguments[1].end)+after.slice(b.call.arguments[2].end)!==before)throw Error('Whole source outside added scalar differs');
const data={valid:true,files:[{file,beforeSha256:hash(before),afterSha256:hash(after)}],soleExecutableDifference:'third test-local timeout argument 20_000',callbackBodySha256:bodySha256,allNonAncestorFunctionBodiesByteIdentical:true,ancestorBodyOnlyAuthorizedArgumentChange:true,functionBodies:a.bodies.length,wholeRemainingSourceByteIdentical:true,globalTimeoutAndProductTimersUnchanged:true};fs.writeFileSync(path.join(out,'equivalence.json'),JSON.stringify(data,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(data));
