import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync,execFileSync} from 'node:child_process';
const root=process.cwd(),out=path.dirname(new URL(import.meta.url).pathname);
const read=name=>JSON.parse(fs.readFileSync(path.join(out,name),'utf8'));
const write=(name,data)=>fs.writeFileSync(path.join(out,name),JSON.stringify(data,null,2)+'\n',{flag:'wx'});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const git=(...args)=>execFileSync('git',args,{encoding:'utf8'}).trim();
if(fs.existsSync(path.join(out,'execution-start.json')))throw Error('Sole execution consumed');
const matrix=read('matrix.json'),frozen=read('focused-command.json'),head=git('rev-parse','HEAD');
const remote=git('ls-remote','https://github.com/Faolain/ts-drp-1','refs/heads/codex/phase3a1b-p6-golden-path').split(/\s+/u)[0];
if(head!=='bc7d615b40c5125ed5b48ff90d0be64dcdca4b15'||remote!==head||git('log','-1','--format=%G?')!=='G'||git('diff','--name-only')||git('diff','--cached','--name-only')||frozen.cwd!==root)throw Error('Signed pushed clean identity differs');
for(const[file,d]of Object.entries(matrix.fileHashes))if(hash(fs.readFileSync(file))!==d)throw Error('Frozen source drift');
const command=['pnpm','exec','vitest','run',...matrix.files,'--no-file-parallelism','--coverage.enabled=false','--reporter=json','--outputFile='+path.join(out,'focused.json')];
if(JSON.stringify(command)!==JSON.stringify(frozen.command))throw Error('Frozen command drift');
write('execution-start.json',{head,remote,signature:'G',command,matrixSha256:hash(fs.readFileSync(path.join(out,'matrix.json'))),executionCount:1,startedAt:new Date().toISOString()});
const result=spawnSync(command[0],command.slice(1),{encoding:'utf8',maxBuffer:32*1024*1024});
fs.writeFileSync(path.join(out,'stdout.log'),result.stdout??'',{flag:'wx'});fs.writeFileSync(path.join(out,'stderr.log'),result.stderr??'',{flag:'wx'});
const report=fs.existsSync(path.join(out,'focused.json'))?read('focused.json'):null;
const outcomes=report?.testResults.flatMap(s=>s.assertionResults.map(r=>({file:path.relative(root,s.name),name:[...r.ancestorTitles,r.title].join(' > '),status:r.status,duration:r.duration,failureMessages:r.failureMessages??[]})))??[];
const expected=matrix.entries.map(r=>({file:r.file,name:r.name})).sort((a,b)=>a.name.localeCompare(b.name)),actual=outcomes.map(r=>({file:r.file,name:r.name})).sort((a,b)=>a.name.localeCompare(b.name));
const topLevel=[...(report?.unhandledErrors??[]),...(report?.testResults.flatMap(s=>[s.message,s.testExecError].filter(Boolean))??[])],violations=[];
if(result.status!==0||result.signal||report?.success!==true||report?.testResults.length!==1||report?.numTotalTests!==19||report?.numPassedTests!==19||report?.numFailedTests!==0||outcomes.length!==19||outcomes.some(r=>r.status!=='passed'||r.failureMessages.length)||topLevel.length||JSON.stringify(expected)!==JSON.stringify(actual))violations.push('Exact19 baseline matrix mismatch');
write('result.json',{classification:violations.length?'UNEXPECTED_MATRIX_STOP_NO_RERUN':'ACCEPTED_RETAINED_COUNTER_BASELINE',executionCount:1,head,runnerStatus:result.status,signal:result.signal,total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,intentionallyFiltered:outcomes.filter(r=>r.status==='pending'||r.status==='skipped').length,topLevel,violations,outcomes,finishedAt:new Date().toISOString(),notNewCausalRed:true,noParentRuntimeRun:true,pendingGreenGateStillRequired:true});
console.log(JSON.stringify({classification:violations.length?'UNEXPECTED_MATRIX_STOP_NO_RERUN':'ACCEPTED_RETAINED_COUNTER_BASELINE',passed:report?.numPassedTests,failed:report?.numFailedTests,violations}));
process.exitCode=violations.length?2:0;
