import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
const root = import.meta.dirname;
const json = name => JSON.parse(readFileSync(join(root, name), "utf8"));
const redCapture = json("red-result.json"), red = JSON.parse(redCapture.output);
assert.equal(redCapture.exit_code, 1);
assert.equal(red.success, false);
assert.equal(red.testResults.length, 1);
assert.equal(red.numFailedTests, 1);
assert.equal(red.numPendingTests, 11);
const failed = red.testResults[0].assertionResults.filter(value => value.status === "failed");
assert.equal(failed.length, 1);
assert.equal(failed[0].title, "tracks the returned operands of assignment, comma and logical assignment expressions");
const exactMutants = ["safe = capability", "(safe, capability)", "safe &&= capability", "safe ||= capability", "safe ??= capability", "capability &&= safe", "capability ||= safe", "capability ??= safe", "safe = (other, { capability })"];
assert.deepEqual(failed[0].failureMessages.map(value => value.split("\n")[0]), exactMutants.map(value => `AssertionError: ${value}: expected true to be false // Object.is equality`));
assert.equal(red.testResults[0].message, "");
const green = json("green-reporter.json");
assert.equal(green.success, true);
assert.equal(green.testResults.length, 1);
assert.equal(green.numPassedTests, 5);
assert.equal(green.numFailedTests, 0);
assert.equal(green.numPendingTests, 7);
assert.equal(green.numTotalTests, 12);
assert.equal(green.numTodoTests, 0);
assert.equal(green.testResults[0].message, "");
assert.deepEqual(green.unhandledErrors ?? [], []);
const passed = green.testResults[0].assertionResults.filter(value => value.status === "passed");
assert.equal(passed.length, 5);
for (const value of green.testResults[0].assertionResults) assert.deepEqual(value.failureMessages, []);
const list = readFileSync(join(root, "list.stdout"), "utf8").trim().split("\n");
assert.deepEqual(list, passed.map(value => "tests/phase-6a-creator-successor-product-red.test.ts > " + [...value.ancestorTitles, value.title].join(" > ")));
assert.equal(list.some(value => /campaign/i.test(value)), false);
const commands = json("commands.json");
assert.deepEqual(commands.map(value => value.name), ["format", "lint", "diff", "list", "green"]);
for (const value of commands) { assert.equal(value.status, 0); assert.equal(value.signal, null); }
const before = json("main-before.json"), after = json("main-after.json");
assert.equal(before.trackedStatus, ""); assert.equal(after.trackedStatus, "");
assert.equal(before.stashCount, 27); assert.equal(after.stashCount, 27);
assert.equal(after.stashHash, before.stashHash);
assert.deepEqual(after.protectedEntries, before.protectedEntries);
assert.equal(json("source-check.json").exit_code, 0);
const result = { status: "PASS", commit: after.commit, signature: after.signature, pushedRef: after.pushedRef, red: { selectedFiles: 1, failedTests: 1, exactSoftFailures: exactMutants, filtered: 11 }, green: { selectedFiles: 1, passedTests: 5, failedTests: 0, filtered: 7, selectedNames: passed.map(value => value.fullName) }, stashCount: 27, protectedEntries: Object.keys(after.protectedEntries).length, productionChanges: 0, validatedAt: new Date().toISOString() };
writeFileSync(join(root, "validation.json"), JSON.stringify(result, null, 2) + "\n", { flag: "wx" });
const hash = bytes => createHash("sha256").update(bytes).digest("hex");
const names = readdirSync(root).filter(name => name !== "manifest.sha256").sort();
const manifest = names.map(name => `${hash(readFileSync(join(root, name)))}  ${name}`).join("\n") + "\n";
writeFileSync(join(root, "manifest.sha256"), manifest, { flag: "wx" });
console.log(JSON.stringify({ ...result, manifestFiles: names.length, manifestSha256: hash(manifest) }, null, 2));
