import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import ts from 'typescript';
const root=process.argv[2],baseline='b5d94193aa34819f1f8706b4ee4f0ac966baffb9',path='packages/node/src/v3-live.ts';
const git=(...a)=>execFileSync('git',['-C',root,...a],{encoding:'utf8'});
const hash=s=>createHash('sha256').update(s).digest('hex');
const before=git('show',`${baseline}:${path}`),after=readFileSync(resolve(root,path),'utf8');
const old=' * Rejection fails the current session closed; failure, crash or cold reopen may replay notifications.\n';
const next=' * Successor-recovery callback rejection rejects and deactivates activation.\n * Ordinary authenticated ingress and local issue retain legacy log-and-continue behavior on rejection.\n * Failure, crash or cold reopen may replay notifications.\n';
if(before.split(old).length!==2||before.replace(old,next)!==after)throw Error('not the exact sole comment replacement');
const parse=s=>ts.createSourceFile(path,s,ts.ScriptTarget.Latest,true);
const print=s=>ts.createPrinter({removeComments:true}).printFile(parse(s));
const tokens=s=>{const source=parse(s),out=[];const visit=n=>{if(n.kind===ts.SyntaxKind.JSDocComment)return;const children=n.getChildren(source);if(!children.length&&n.kind>=ts.SyntaxKind.FirstToken&&n.kind<=ts.SyntaxKind.LastToken)out.push([n.kind,n.getText(source)]);else children.forEach(visit)};visit(source);return JSON.stringify(out)};
if(print(before)!==print(after)||tokens(before)!==tokens(after))throw Error('runtime AST/token change');
const untouched=['examples/v3-room/src/index.ts','tests/phase-6b-d110c-0c1f5b0u-successor-replay-red.test.ts','tests/phase-6b-d110c-0c1f5b0v-callback-contract.test.ts','pnpm-lock.yaml'];
for(const p of untouched)if(git('show',`${baseline}:${p}`)!==readFileSync(resolve(root,p),'utf8'))throw Error(`unexpected change ${p}`);
console.log(JSON.stringify({baseline,path,before:hash(before),after:hash(after),astHash:hash(print(after)),tokenHash:hash(tokens(after)),exactSoleComment:true,astEqual:true,tokensEqual:true,untouched:Object.fromEntries(untouched.map(p=>[p,hash(readFileSync(resolve(root,p)))]))},null,2));
