import assert from "node:assert/strict";
import { test } from "node:test";

import { assertDirectObservations, assertRecoveryObservations } from "./observation-oracle.js";
import type { Case } from "./roster.js";
import type { Effects, ProbeReport, RecoveryCase, RecoveryReport, SetupReport, Trace } from "./types.js";

// Fabricated controller DTOs only. These do not invoke observers or native owners,
// and are NEVER native instrumentation/precondition or product recovery evidence.
// The model is handwritten from the two-preloaded-chunk fixture protocol, not
// generated by recoverySchedule and not copied from an observed recovery report.
const id = "a".repeat(64),
	oldId = "b".repeat(64);
const setup = JSON.parse(
	JSON.stringify({
		bootstrap: {
			expectedPreviousRoomHead: {
				objectId: "creator:" + "c".repeat(32),
				epoch: 0,
				currentAnchorDigest: "d".repeat(64),
			},
		},
		oracle: {
			lookupScope: {
				objectId: "creator:" + "c".repeat(32),
				epoch: 0,
				anchor: "d".repeat(64),
				manifestDigest: "e".repeat(64),
			},
			competingScope: {
				objectId: "creator:" + "c".repeat(32),
				epoch: 3,
				anchor: "d".repeat(64),
				manifestDigest: "f".repeat(64),
			},
			proposedHead: { generationId: oldId },
			intendedPublicationHead: { generationId: id },
			preparedCandidates: [{ generationId: id, closureDigest: "1".repeat(64), role: "intended", state: "Complete" }],
			snapshotChunks: { count: 2, indices: [0, 1], allPreloaded: true },
		},
	})
) as SetupReport;
const scoped = new Set([
	"lookup",
	"native-lookup",
	"native-lookup-outcome",
	"native-lookup-refusal",
	"acquire",
	"native-acquire",
	"complete",
	"lookup-race-applied",
	"acquisition-race-applied",
]);
function event(site: string, values: Partial<Trace> = {}): Trace {
	return { site, candidate: id, ...(scoped.has(site) ? { scope: { ...setup.oracle.lookupScope } } : {}), ...values };
}
function model(mode: RecoveryCase, diagnostic = false): { report: RecoveryReport; scenario: Case } {
	const race = mode === "delete-after-lookup",
		casFault = ["lost-cas", "failed-cas", "reread-failed"].includes(mode),
		published = !race && !casFault;
	const traces: Trace[] = [event("read-head", { candidate: null }), event("lineage", { candidate: null })];
	if (!published) traces.push(event("closure-load", { candidate: oldId, ok: true }));
	traces.push(
		...[
			"closure-load",
			"genesis-trust",
			"successor-trust",
			"authenticated-previous",
			"authenticated-next",
			"pre-transition",
		].map((site) => event(site, { ok: true }))
	);
	const narrow = mode === "narrow-store",
		missing = mode === "missing-metadata",
		corrupt = mode === "missing-chunk",
		legacy = mode === "legacy-open";
	if (!diagnostic) {
		traces.push(event("lookup-property-access"));
		if (!narrow)
			traces.push(
				event("lookup"),
				event("native-lookup"),
				event(
					"native-lookup-outcome",
					missing
						? { kind: "missing" }
						: {
								kind: "present",
								state: legacy ? "open" : "verified",
								retention: legacy ? "legacy-unclassified" : "recovery",
							}
				)
			);
		if (race) traces.push(event("lookup-race-applied", { ok: true }));
	}
	const reaches = !narrow && !missing;
	if (reaches) {
		traces.push(event("acquire"), event("native-acquire"), event("native-read"));
		if (!corrupt) traces.push(event("native-read"));
		if (legacy) traces.push(event("complete"), event("native-mutation-refusal", { code: "migration-required" }));
		traces.push(event("snapshot-result", { ok: !corrupt && !race && !legacy }));
		if (!corrupt && !race && !legacy)
			traces.push(
				...[
					"snapshot-payload",
					"catalog-result",
					"projection-payload",
					"parameters",
					"acl-selection",
					"acl-result",
					"settlement-repeat",
				].map((site) => event(site, { ok: true }))
			);
	}
	if (casFault) {
		traces.push(event("cas"));
		if (mode === "lost-cas") traces.push(event("lost-cas-response-applied", { ok: true }));
		if (mode === "failed-cas") traces.push(event("failed-cas-applied", { ok: true }));
		traces.push(event("active-reread"));
		if (mode === "reread-failed") traces.push(event("reread-failure-applied", { ok: true }));
	}
	const effects: Effects = {
		traces,
		accesses: diagnostic ? 0 : 1,
		lookups: diagnostic || narrow ? 0 : 1,
		nativeLookups: diagnostic || narrow ? 0 : 1,
		acquisitions: reaches ? 1 : 0,
		nativeAcquisitions: reaches ? 1 : 0,
		reads: reaches ? (corrupt ? 1 : 2) : 0,
		completes: legacy ? 1 : 0,
		swaps: casFault ? [id] : [],
		rereads: casFault ? 1 : 0,
		mutations: mode === "verified" || narrow || casFault ? 0 : 1,
	};
	return {
		scenario: { id: "CONTROLLER_ONLY_" + mode, epoch: 1, published, mode },
		report: {
			mode,
			classification: "REACHED",
			result: { ok: mode === "verified", kind: "pending-missing" },
			effects,
			durableBefore: null,
			durableAfter: null,
		},
	};
}
function comparison(value: ReturnType<typeof model>, diagnostic = false): void {
	assertRecoveryObservations(value.report, setup, value.scenario, diagnostic);
}
for (const mode of [
	"verified",
	"missing-chunk",
	"delete-after-lookup",
	"missing-metadata",
	"narrow-store",
	"legacy-open",
] as const)
	void test("CONTROLLER SELF-CONTROL ONLY: exact handwritten schedule accepts " + mode, () => comparison(model(mode)));
void test("CONTROLLER SELF-CONTROL ONLY: legacy dialect lookup0 is distinct from product lookup1", () => {
	comparison(model("verified", true), true);
	assert.throws(() => comparison(model("verified", true)), /exact observation\/gate event count/u);
});
const mutations: { name: string; mode: RecoveryCase; change(value: ReturnType<typeof model>): void }[] = [
	{
		name: "zero-I/O pending-missing",
		mode: "missing-chunk",
		change({ report }): void {
			report.effects = {
				...report.effects,
				traces: [],
				accesses: 0,
				lookups: 0,
				nativeLookups: 0,
				acquisitions: 0,
				nativeAcquisitions: 0,
				reads: 0,
			};
		},
	},
	{
		name: "duplicate native read",
		mode: "missing-chunk",
		change({ report }): void {
			report.effects.reads++;
			report.effects.traces.splice(-1, 0, event("native-read"));
		},
	},
	{
		name: "duplicate lookup",
		mode: "missing-chunk",
		change({ report }): void {
			report.effects.lookups++;
			report.effects.traces.splice(9, 0, event("lookup"));
		},
	},
	{
		name: "wrong candidate native read",
		mode: "missing-chunk",
		change({ report }): void {
			const read = report.effects.traces.find((trace) => trace.site === "native-read");
			assert.ok(read);
			read.candidate = oldId;
		},
	},
	{
		name: "race omitted but setup mutation retained",
		mode: "delete-after-lookup",
		change({ report }): void {
			report.effects.traces = report.effects.traces.filter((trace) => trace.site !== "lookup-race-applied");
		},
	},
	{
		name: "gate omitted",
		mode: "missing-chunk",
		change({ report }): void {
			report.effects.traces = report.effects.traces.filter((trace) => trace.site !== "pre-transition");
		},
	},
	{
		name: "gate result inverted",
		mode: "missing-chunk",
		change({ report }): void {
			const gate = report.effects.traces.find((trace) => trace.site === "snapshot-result");
			assert.ok(gate);
			gate.ok = true;
		},
	},
	{
		name: "native scope omitted",
		mode: "missing-chunk",
		change({ report }): void {
			const lookup = report.effects.traces.find((trace) => trace.site === "native-lookup");
			assert.ok(lookup);
			delete lookup.scope;
		},
	},
	{
		name: "metadata miss substituted for missing capability",
		mode: "narrow-store",
		change(value): void {
			value.report.effects = model("missing-metadata").report.effects;
		},
	},
	{
		name: "completion omitted on legacy refusal",
		mode: "legacy-open",
		change({ report }): void {
			report.effects.completes = 0;
			report.effects.traces = report.effects.traces.filter((trace) => trace.site !== "complete");
		},
	},
	{
		name: "native migration refusal provenance omitted",
		mode: "legacy-open",
		change({ report }): void {
			report.effects.traces = report.effects.traces.filter((trace) => trace.site !== "native-mutation-refusal");
		},
	},
	...(["lost-cas", "failed-cas", "reread-failed"] as const).map((mode) => ({
		name: mode + " intentional fault omitted despite unchanged counts/result",
		mode,
		change({ report }: ReturnType<typeof model>): void {
			report.effects.traces = report.effects.traces.filter(
				(trace) => !["lost-cas-response-applied", "failed-cas-applied", "reread-failure-applied"].includes(trace.site)
			);
		},
	})),
];
for (const mutation of mutations)
	void test("CONTROLLER SELF-CONTROL ONLY: comparator rejects " + mutation.name, () => {
		const value = model(mutation.mode);
		comparison(value); // The independent unmutated DTO must actually pass first.
		mutation.change(value);
		let captured: unknown;
		try {
			comparison(value);
		} catch (error) {
			captured = error;
		}
		assert.ok(captured instanceof assert.AssertionError, "same controller comparator actually threw");
		console.log(
			JSON.stringify({
				lane: "CONTROLLER_SELF_CONTROL_ONLY_NOT_NATIVE_MUTANT",
				mutation: mutation.name,
				captured: captured.message,
			})
		);
	});
for (const binding of ["trusted previous triple", "distinct competing triple"] as const)
	void test("CONTROLLER SELF-CONTROL ONLY: comparator rejects wrong " + binding, () => {
		const value = model("verified");
		comparison(value);
		const changed = structuredClone(setup);
		if (binding === "trusted previous triple")
			changed.bootstrap.expectedPreviousRoomHead.currentAnchorDigest = "9".repeat(64);
		else changed.oracle.competingScope = { ...changed.oracle.lookupScope };
		let captured: unknown;
		try {
			assertRecoveryObservations(value.report, changed, value.scenario, false);
		} catch (error) {
			captured = error;
		}
		assert.ok(captured instanceof assert.AssertionError);
		console.log(
			JSON.stringify({
				lane: "CONTROLLER_SELF_CONTROL_ONLY_NOT_NATIVE_MUTANT",
				mutation: binding,
				captured: captured.message,
			})
		);
	});
void test("CONTROLLER SELF-CONTROL ONLY: direct primitive exact competing+target and missing read fail closed", () => {
	const effects = model("missing-chunk").report.effects;
	effects.traces = effects.traces
		.filter(
			(trace) =>
				![
					"read-head",
					"lineage",
					"closure-load",
					"genesis-trust",
					"successor-trust",
					"authenticated-previous",
					"authenticated-next",
					"pre-transition",
					"snapshot-result",
				].includes(trace.site)
		)
		.map((trace) => ({ ...trace, candidate: null }));
	effects.traces.unshift(
		event("native-lookup", { candidate: null, scope: setup.oracle.competingScope }),
		event("native-lookup-outcome", {
			candidate: null,
			scope: setup.oracle.competingScope,
			kind: "present",
			state: "verified",
			retention: "temporary",
		})
	);
	effects.nativeLookups = 2;
	const report: ProbeReport = {
		mode: "missing-chunk",
		effects,
		competing: true,
		acquired: true,
		verified: false,
		bytes: 0,
	};
	assertDirectObservations(report, setup, "missing-chunk");
	const competingOutcome = effects.traces[1];
	assert.ok(competingOutcome);
	competingOutcome.retention = "recovery";
	let retentionFailure: unknown;
	try {
		assertDirectObservations(report, setup, "missing-chunk");
	} catch (error) {
		retentionFailure = error;
	}
	assert.ok(retentionFailure instanceof assert.AssertionError, "same comparator rejects wrong competing retention");
	console.log(
		JSON.stringify({
			lane: "CONTROLLER_SELF_CONTROL_ONLY_NOT_NATIVE_MUTANT",
			mutation: "wrong competing retention",
			captured: retentionFailure.message,
		})
	);
	competingOutcome.retention = "temporary";
	effects.reads = 0;
	effects.traces = effects.traces.filter((trace) => trace.site !== "native-read");
	assert.throws(() => assertDirectObservations(report, setup, "missing-chunk"), /exact observation\/gate event count/u);
});
