import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,s)=>fs.writeFileSync(path.join(out,f),s,{flag:'wx'});
const result=read('main-49/validation.json'),custody=read('custody-after.json'),eq=read('equivalence.json');if(!result.valid||!read('matrix-validation.json').valid)throw Error('Main gates not accepted');
const patch=execFileSync('git',['diff','--binary','--full-index','--','tests/phase-5d-pacemaker-red.test.ts'],{cwd:root});write('fixture-only.patch',patch);
const data={readyForRootSourceSigning:true,sourceHead:custody.head,sourceFiles:eq.files,patchSha256:hash(patch),parentPatchSha256:custody.patchSha256,main:{total:result.total,passed:result.passed,failed:result.failed,skipped:result.skipped,reporterSha256:result.reporterSha256},compiler:'exit 1, exact unchanged grid-only diagnostic; matrix 0; not whole-program typecheck pass',isolation:'pending separately signed source and root release',diagnosticErrors:['Initial equivalence compared enclosing describe callback, which necessarily contains the scalar change; distinct corrected checker proves every other byte unchanged.','Initial readiness recorder ran before lint status existed; failed before runtime; after lint 0 the distinct readiness capture passed.'],effectiveCustody:'custody-after.json testHashes is the complete effective 85-entry map'};
write('main-handoff.json',JSON.stringify(data,null,2)+'\n');write('assessment.md','# Same-batch replay-budget GREEN — main handoff\n\nOnly the authorized third registration argument `20_000` changes executable source. The callback body retains SHA-256 `'+eq.callbackBodySha256+'`; the title, readiness predicate, all assertions, global 10-second default, model invocations and product timers are unchanged. This is a test-harness budget, not a product latency result.\n\nThe sole main four-file gate passed 49/49 with no skips, soft failures or suite errors. Exact-owner lint, format, diff and corrected source equivalence pass. The same strict compiler retains exactly the existing grid diagnostic (exit 1 / matrix 0), not a whole-program static pass.\n\nTwo recorder-only errors are preserved: the first equivalence included the enclosing describe body; the first readiness capture preceded lint completion. Distinct corrected checks passed without source changes or runtime repetition.\n\nEight pending production owners and seven built owners remain unchanged; effective 85 test/shared identities, 27 stashes, 86,522 protected paths and prior manifests are preserved. Root owns signing the one-file source and releasing the fresh isolated acceptance gate. Earlier failed isolated 48/49 remains immutable and is not relabeled as passing.\n');console.log(JSON.stringify(data));
