import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const out=path.dirname(new URL(import.meta.url).pathname),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
if(fs.existsSync(path.join(out,'manifest.sha256')))throw Error('Already sealed');
const main=read('main-49/validation.json'),isolated=read('isolated/runtime-49/validation.json'),custody=read('custody-final.json');
if(!main.valid||!isolated.exactNames||!isolated.exactFiles||isolated.total!==49)throw Error('Incomplete matrix');
for(const f of ['custody-final/status.json','isolated/custody-after/status.json'])if(read(f).code!==0)throw Error('Final custody');
for(const f of ['main-49/execution-start.json','isolated/runtime-49/execution-start.json']){const pid=read(f).pid,r=spawnSync('ps',['-p',String(pid),'-o','pid=,stat='],{encoding:'utf8'});if(![0,1].includes(r.status)||r.stdout.trim())throw Error('Runtime recorder remains active');}
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]),statuses=walk(out).filter(f=>path.basename(f)==='status.json').sort().map(f=>({file:path.relative(out,f),...JSON.parse(fs.readFileSync(f))})),nonzero=statuses.filter(s=>(s.status??s.code)!==0).map(s=>({file:s.file,status:s.status??s.code}));
const allowed=['compiler-green/status.json','equivalence/status.json','freeze-runtime/status.json','isolated/compiler-green/status.json',...(!isolated.valid?['isolated/runtime-49/status.json']:[])].sort();if(JSON.stringify(nonzero.map(s=>s.file).sort())!==JSON.stringify(allowed)||nonzero.some(s=>s.status!==1))throw Error('Unexpected command status');
const title='replays every checked trace through the genuine voter, pacemaker, and fake-IDB store',timings={main:main.assertions.find(a=>a.title===title)?.duration,isolated:isolated.assertions.find(a=>a.title===title)?.duration};
const summary={stopped:!isolated.valid,main:{total:main.total,passed:main.passed,failed:main.failed,skipped:main.skipped,reporterSha256:main.reporterSha256},isolated:{total:isolated.total,passed:isolated.passed,failed:isolated.failed,skipped:isolated.skipped,reporterSha256:isolated.reporterSha256},sourceHead:custody.head,sourceSha256:custody.testHashes['tests/phase-5d-pacemaker-red.test.ts'],parentPatchSha256:custody.patchSha256,commands:statuses.length,nonzero,selectedTestDurationsMs:timings,compiler:'Both exit1 / matrix0, exact unchanged grid-only diagnostic; not a whole-program typecheck pass',effectiveCustody:'custody-final.json contains the complete effective 85-entry testHashes map',noRuntimeRetry:true,noActiveRuntimeRecorder:true,parentClosed:false,rootAcceptancePending:true};
write('command-status-inventory.json',statuses);write('seal-summary.json',summary);
const text='# Authorized replay-budget amendment — final GREEN evidence\n\nSigned source `967da628cc8522cf468c20488a2e071eb84e59ee` adds only the third test-local registration argument `20_000`. Callback SHA-256 remains `f3c51b5f029dff7d496528157f04b1b5bc550b5a149dadd35aaba530675c0e41`; every remaining source byte is identical after removing this argument. All assertions, readiness, traces, model commands, global 10-second default and product timers remain unchanged. This is an explicitly authorized harness budget, not a product latency claim.\n\nMain: '+main.passed+'/49 passed. Fresh isolated: '+isolated.passed+'/49 passed, '+isolated.failed+' failed, '+isolated.skipped+' skipped. Exact file/title/ancestor/fullName multisets and complete error states are retained. Selected replay durations were '+timings.main+' ms main and '+timings.isolated+' ms isolated; these observations do not establish a performance contract. '+(isolated.valid?'Both complete reporters have no failures, skips, soft failures or suite errors.':'The isolated failure remains an open acceptance stop; no retry or source change followed.')+'\n\nOwn offline frozen ignore-scripts install, locked official native download into a fresh cache, direct native import, fresh package source build and fresh Node-root import succeeded. The isolated checkout is `/private/tmp/d110c-f5b-green-replay-budget-zIt6Xr/checkout`. All 93 source identities and seven freshly emitted runtime owners match main. The main compiler graph has 1,309 sources versus 928 isolated: exactly 381 main-only ancestor ambient declarations, no common-source hash differences, and every isolated source physically inside the checkout. Both strict compilers retain only the exact grid TS2345 diagnostic (exit 1 / matrix 0); no blanket static pass is claimed. Exact-owner lint/format/diff and source equivalence pass.\n\nPreserved recorder errors: initial equivalence mistakenly included the enclosing describe body; the corrected checker preserves every remaining byte and all nonancestor bodies. Initial readiness ran before lint completion and failed before runtime; distinct readiness after lint 0 succeeded. No source correction, compiler repetition or runtime retry was used for either diagnostic mistake.\n\nThe signed prior 223-entry stopped root and its 48-pass/one-timeout report remain immutable. The new final custody preserves eight pending production owners, seven main built owners, effective 85 test/shared hashes, 27 stashes, 86,522 protected paths and prior manifests. Parent patch remains `'+custody.patchSha256+'`. No agent commit or plan edit occurred. Root owns evidence signing and acceptance; combined parent gates, grid composition, four original runtime failures and final review remain separate open obligations.\n';
fs.writeFileSync(path.join(out,'final-assessment.md'),text,{flag:'wx'});
const files=walk(out).sort(),manifest=files.map(f=>hash(fs.readFileSync(f))+'  '+path.relative(out,f)).join('\n')+'\n';fs.writeFileSync(path.join(out,'manifest.sha256'),manifest,{flag:'wx'});console.log(JSON.stringify({entries:files.length,manifestSha256:hash(manifest),commands:statuses.length,nonzero,isolated:summary.isolated,stopped:!isolated.valid}));
