import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import ts from '/Users/aristotle/Documents/Projects/ts-drp-1/node_modules/typescript/lib/typescript.js';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),red=path.join(root,'.logs/d110c-0c1f5b-red-fixture-exit-5aa22117'),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),baseline=JSON.parse(fs.readFileSync(path.join(red,'frozen-baseline.json'))),added=[];
const owners=['tests/fixtures/phase-3b-v3/certified-genesis-contract.ts','tests/phase-3g-v3-room-rebase-red.test.ts','tests/genesis-profile.test.ts','tests/phase-5d-pacemaker-red.test.ts'];
for(const row of baseline.sources){const bytes=fs.readFileSync(path.join(root,row.file)),snapshot=fs.readFileSync(path.join(red,row.snapshot));if(hash(bytes)!==row.sha256||!bytes.equals(snapshot))throw Error('Signed RED snapshot drift '+row.file);const unit=ts.createSourceFile(row.file,bytes.toString(),ts.ScriptTarget.Latest,true);function visit(n){
 if(row.file==='tests/genesis-profile.test.ts'&&ts.isCallExpression(n)&&n.expression.getText(unit)==='ed25519.verify'&&n.arguments[2]?.getText(unit)==='row.publicKey'){const a=n.arguments[2];added.push({file:row.file,owner:'single genuine certificate verify public-key argument',start:a.getStart(unit),end:a.end,text:a.getText(unit),replacement:'Uint8Array.from(Buffer.from(row.publicKey, "hex"))',runtimeCorrection:true});}
 if(row.file==='tests/phase-5d-pacemaker-red.test.ts'&&ts.isVariableDeclaration(n)&&n.name.getText(unit)==='mutant'&&n.initializer?.getText(unit)==='structuredClone(trace)'){const a=n.initializer;added.push({file:row.file,owner:'detached mutable cloned trace states type only',start:a.getStart(unit),end:a.end,text:a.getText(unit),replacement:'structuredClone(trace) as Omit<ItfTrace, "states"> & { readonly states: ItfTrace["states"][number][] }',runtimeCorrection:false});}
 ts.forEachChild(n,visit)}visit(unit);}
if(added.length!==2||baseline.authorizedSpans.length!==3)throw Error('Five exact source spans');
const spans=[...baseline.authorizedSpans,...added],outside=baseline.sources.map(row=>{let text=fs.readFileSync(path.join(root,row.file),'utf8');for(const s of spans.filter(s=>s.file===row.file).sort((a,b)=>b.start-a.start))text=text.slice(0,s.start)+'<AUTHORIZED_SPAN>'+text.slice(s.end);return{file:row.file,sha256:row.sha256,outsideFiveSpansSha256:hash(text)}});
fs.writeFileSync(path.join(out,'frozen-scope.json'),JSON.stringify({signedRed:'f8ec9daf82c230b48ef615073979dcab7b14f149',baselineRoot:path.relative(root,red),baselineSha256:hash(fs.readFileSync(path.join(red,'frozen-baseline.json'))),owners,spans,outside,entries:baseline.entries,sourceRows:baseline.sources,files:4,total:49,noRuntimeOrCollection:true},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({frozen:true,sourceOwners:4,spans:5,sourceSnapshots:6,historicalCases:49}));
