import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const out=path.dirname(new URL(import.meta.url).pathname),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
if(fs.existsSync(path.join(out,'manifest.sha256')))throw Error('Already sealed');
const main=read('main-49/validation.json'),isolated=read('isolated/runtime-49/validation.json'),attribution=read('timeout-attribution.json');if(!main.valid||main.total!==49||main.passed!==49||isolated.valid||!isolated.exactNames||!isolated.exactFiles||isolated.total!==49||isolated.passed!==48||isolated.failed!==1||isolated.skipped!==0||!attribution.stopped||!attribution.noRetry)throw Error('Expected honest stopped matrix');
for(const f of ['custody-final/status.json','isolated/custody-after/status.json','timeout-attribution-corrected/status.json'])if(read(f).code!==0)throw Error('Final custody/attribution');
for(const pid of [read('main-49/execution-start.json').pid,read('isolated/runtime-49/execution-start.json').pid]){const r=spawnSync('ps',['-p',String(pid),'-o','pid=,stat='],{encoding:'utf8'});if(![0,1].includes(r.status)||r.stdout.trim())throw Error('Runtime recorder still active');}
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]),statuses=walk(out).filter(f=>path.basename(f)==='status.json').sort().map(f=>({file:path.relative(out,f),...JSON.parse(fs.readFileSync(f))})),nonzero=statuses.filter(s=>(s.status??s.code)!==0).map(s=>({file:s.file,status:s.status??s.code}));
const expected=['compiler-green/status.json','isolated/compiler-green/status.json','isolated/runtime-49/status.json','timeout-attribution/status.json'].sort();if(JSON.stringify(nonzero.map(s=>s.file).sort())!==JSON.stringify(expected)||nonzero.some(s=>s.status!==1))throw Error('Unexpected nonzero command set');
write('command-status-inventory.json',statuses);write('seal-summary.json',{stopped:true,main:{total:49,passed:49,failed:0,skipped:0,rawSha256:main.reporterSha256},isolated:{total:49,passed:48,failed:1,skipped:0,rawSha256:isolated.reporterSha256},compilerDisposition:'Both exit1 exact unchanged grid-only diagnostic; both matrix0; nine fixture diagnostics removed',commands:statuses.length,nonzero,latestCustody:'custody-final.json',effectiveTestHashCount:Object.keys(read('custody-final.json').testHashes).length,sourceHead:'8336eb777e775263d4983a76ffea8a699b8faf60',parentPatchSha256:read('custody-final.json').patchSha256,noActiveRuntimeRecorder:true,noRuntimeRetry:true,parentClosed:false,fixtureBatchClosed:false});
const files=walk(out).sort(),manifest=files.map(f=>hash(fs.readFileSync(f))+'  '+path.relative(out,f)).join('\n')+'\n';fs.writeFileSync(path.join(out,'manifest.sha256'),manifest,{flag:'wx'});console.log(JSON.stringify({entries:files.length,manifestSha256:hash(manifest),commands:statuses.length,nonzero,stopped:true}));
