import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),read=n=>JSON.parse(fs.readFileSync(path.join(out,n),'utf8')),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),actual=read('diagnostics.json'),identity=read('program-identity.json'),status=read('compiler-red/status.json');
const priorFiles=['.logs/d110c-0c1f5b-retained-finality-867d7f09/typecheck.json','.logs/d110c-0c1f5b-retained-room-mocks-e384a40c/typecheck.json'],priors=priorFiles.map(f=>({file:f,sha256:hash(fs.readFileSync(path.join(root,f))),value:JSON.parse(fs.readFileSync(path.join(root,f)))})),known=priors.flatMap(p=>[...p.value.targetDiagnostics,...p.value.externalDiagnostics]),compact=d=>({file:d.file,code:d.code,line:d.line,message:d.message}),remaining=actual.diagnostics.map((d,index)=>({index,row:compact(d)})),matches=[],missing=[];
for(const expected of known){const at=remaining.findIndex(v=>JSON.stringify(v.row)===JSON.stringify(expected));if(at<0)missing.push(expected);else matches.push({expected,actualIndex:remaining.splice(at,1)[0].index})}
const additions=remaining.map(v=>actual.diagnostics[v.index]),groups=actual.diagnostics.reduce((m,d)=>{const k=d.file+' TS'+d.code;m[k]=(m[k]??0)+1;return m},{});
const valid=status.code===1&&!status.signal&&!status.spawnError&&actual.programExecutions===1&&identity.programExecutions===1&&!actual.typecheckPassed&&missing.length===0&&additions.length===0&&JSON.stringify(actual.options)===JSON.stringify(identity.relocatedOptions);
const data={classification:valid?'COMPILER_RED_KNOWN7_FIXTURE_PLUS1_GRID':'STOP_ADDITIONAL_OR_CHANGED_DIAGNOSTICS',matrixValid:valid,compilerTerminalExit:status.code,matrixValidatorExit:valid?0:1,typecheckPassed:false,programExecutions:actual.programExecutions,diagnosticCount:actual.diagnosticCount,knownFixtureCount:matches.filter(m=>m.expected.file.startsWith('tests/')).length,knownGridCount:matches.filter(m=>m.expected.file==='examples/grid/src/v3-zone.ts').length,additionalCount:additions.length,missingCount:missing.length,knownMatches:matches,additionalDiagnostics:additions,missingKnownDiagnostics:missing,groups,priorEvidence:priors,comparison:'Exact file/code/line/full-message multiset against all recorded fields; new full positions/owners/tokens captured in diagnostics.json',sourceInputs:identity.sources.length,readInputs:identity.readInputs.length,resolvedModules:identity.resolvedModules.length,resolvedTypeReferences:identity.resolvedTypeReferences.length,runtimeExecutions:0};
fs.writeFileSync(path.join(out,'matrix-validation.json'),JSON.stringify(data,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({classification:data.classification,diagnostics:data.diagnosticCount,knownFixture:data.knownFixtureCount,knownGrid:data.knownGridCount,additional:data.additionalCount,missing:data.missingCount,groups}));
process.exitCode=valid?0:1;
