import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import ts from '/Users/aristotle/Documents/Projects/ts-drp-1/node_modules/typescript/lib/typescript.js';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),file='tests/phase-6b-d110c-0c1f5b-integration-red.test.ts',title='composes 64 active writers with universal plan fence and exact state accounting across three transitions',hash=b=>crypto.createHash('sha256').update(b).digest('hex'),before=fs.readFileSync(path.join(out,'source-before.ts'),'utf8'),after=fs.readFileSync(path.join(root,file),'utf8');
function inspect(text){const unit=ts.createSourceFile(file,text,ts.ScriptTarget.Latest,true),calls=[],bodies=[];function scan(n){if(ts.isCallExpression(n)&&n.arguments[0]&&ts.isStringLiteral(n.arguments[0])&&n.arguments[0].text===title)calls.push(n);if(ts.isFunctionDeclaration(n)&&n.name?.text==='sixtyFourWriterGoldenPath')bodies.push(n.body.getText(unit));ts.forEachChild(n,scan)}scan(unit);if(calls.length!==1||bodies.length!==1)throw Error('Unique callback/registration');return{unit,call:calls[0],body:bodies[0]}}
const a=inspect(before),b=inspect(after);if(a.call.arguments.length!==3||b.call.arguments.length!==3||a.call.arguments[2].getText(a.unit)!=='70_000'||b.call.arguments[2].getText(b.unit)!=='90_000'||a.call.expression.getText(a.unit)!==b.call.expression.getText(b.unit))throw Error('Registration delta');for(let i=0;i<2;i++)if(a.call.arguments[i].getText(a.unit)!==b.call.arguments[i].getText(b.unit))throw Error('Original args');
if(hash(before)!=='c63f9cb4c8bfda07a631de56382180147af01e9c062b7099a39a4632d9f16f0e'||a.body!==b.body||hash(a.body)!=='0003ed91240734eafb114c9aa160bc8c4f66f5153084ea7fab480b53974c17f9')throw Error('Accepted source/body');
const comment='// The authorized 90s runner watchdog belongs only to the fixed 64-writer';if(after.split(comment).length!==2)throw Error('Unique comment');const restored=(after.slice(0,b.call.arguments[2].getStart(b.unit))+'70_000'+after.slice(b.call.arguments[2].end)).replace(comment,'// The authorized 70s runner watchdog belongs only to the fixed 64-writer');if(restored!==before)throw Error('Entire file outside exact two replacements');
const data={valid:true,files:[{file,beforeSha256:hash(before),afterSha256:hash(after)}],callbackBodySha256:hash(a.body),callbackByteIdentical:true,wholeFileRestoredByOnlyTwoExactReplacements:true,soleExecutableDelta:'Selected registration 70_000 -> 90_000',soleNonExecutableDelta:'Adjacent authorized 70s -> authorized 90s comment',allAssertionsWorkloadAndProductTimersUnchanged:true};fs.writeFileSync(path.join(out,'equivalence.json'),JSON.stringify(data,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(data));
