import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync,spawn,spawnSync} from 'node:child_process';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),dir=path.join(out,'wide-only'),file='tests/phase-6b-d110c-0c1f5b-integration-red.test.ts',fullName='D.110c-0c1f5b parent genuine settlement composition composes 64 active writers with universal plan fence and exact state accounting across three transitions',hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:128*1024*1024}).trim();
function custody(){const c=read('custody-after.json'),signed=read('signed-source.json');if(git('rev-parse','HEAD')!==signed.head||git('log','-1','--format=%G?')!=='G'||git('diff','--cached','--name-only'))throw Error('Signed HEAD/index drift');for(const map of [c.ownerHashes,c.built,c.testHashes])for(const[f,h]of Object.entries(map))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Identity drift '+f);if(hash(execFileSync('git',['diff','--binary','--full-index','--',...Object.keys(c.ownerHashes)],{cwd:root,maxBuffer:128*1024*1024}))!==c.patchSha256)throw Error('Production patch drift');return c;}
function environmentAndPorts(){const inherited=process.env.NODE_OPTIONS??'',profiling=/--(?:cpu[-_]prof|heap[-_]prof|prof(?:\b|[-_]))/u.test(inherited)||process.execArgv.some(a=>/--(?:cpu[-_]prof|heap[-_]prof|prof(?:\b|[-_]))/u.test(a));if(profiling||process.env.NODE_V8_COVERAGE)throw Error('Inherited profiling environment rejected');const ports=[];for(const port of [4174,4175,51000,51002]){const r=spawnSync('lsof',['-nP','-i:'+port,'-t'],{encoding:'utf8'});if(![0,1].includes(r.status))throw Error('Fixed-port query');const pids=r.stdout.trim().split(/\s/u).filter(s=>/^\d+$/u.test(s)).map(Number);ports.push({port,pids,unoccupied:pids.length===0});if(pids.length)throw Error('Fixed port occupied '+port);}return{profilingNodeOptionsRejected:true,inheritedProfilingDetected:false,nodeOptionsPresent:Boolean(inherited),nodeV8CoverageAbsent:true,diagnosticVariableExplicitlyUnsetForChild:true,sourceLoggingOptInRemainsUnchanged:true,ports,selectedFixtureUsesFakeNetworkAndNoFixedPortBinding:true};}
function processes(){const r=spawnSync('pgrep',['-f','(vitest|quint|apalache|heap-prof|cpu-prof)'],{encoding:'utf8'});if(![0,1].includes(r.status))throw Error('PID query');const rows=[];for(const pid of r.stdout.trim().split(/\s/u).filter(s=>/^\d+$/u.test(s)).map(Number).filter(p=>p!==process.pid&&p!==process.ppid)){const s=spawnSync('ps',['-p',String(pid),'-o','pid=,ppid=,stat='],{encoding:'utf8'});if(s.status===1)continue;if(s.status!==0)throw Error('PID status');const cwd=spawnSync('lsof',['-a','-p',String(pid),'-d','cwd','-Fn'],{encoding:'utf8'}),relevant=cwd.stdout.split('\n').filter(v=>v.startsWith('n')).some(v=>v.slice(1)===root||v.slice(1).startsWith(root+'/')||/^\/(?:private\/)?tmp\/d110c-f5b-/u.test(v.slice(1)));rows.push({pid,status:s.stdout.trim(),taskRelevantCwd:relevant});if(relevant)throw Error('Competing task runtime PID '+pid);}return{numericOnly:true,noArgvOrComm:true,candidates:rows,taskCompetitors:0,unrelatedProcessesDoNotBlock:true};}
if(process.argv[2]==='freeze'){
 const c=custody();for(const label of ['format','lint','diff','equivalence','typecheck-matrix','signed-source'])if(read(label+'/status.json').code!==0)throw Error('Static gate '+label);if(!read('typecheck-matrix.json').valid)throw Error('Static matrix');
 const node=fs.realpathSync(process.execPath),vitest=fs.realpathSync(path.join(root,'node_modules/vitest/vitest.mjs'));write('launch-identity.json',{node,nodeVersion:process.version,nodeSha256:hash(fs.readFileSync(node)),vitest,vitestSha256:hash(fs.readFileSync(vitest)),cpuProfiling:false});write('environment-port-readiness.json',environmentAndPorts());
 const baselinePath=path.join(root,'.logs/d110c-0c1f5b-green-wide-budget-48f6877d/main-45/focused.json'),baseline=JSON.parse(fs.readFileSync(baselinePath)),suite=baseline.testResults.find(s=>path.relative(root,s.name)===file),entries=suite.assertionResults.map(a=>({file,title:a.title,ancestorTitles:a.ancestorTitles,fullName:a.fullName}));if(entries.length!==24||entries.filter(a=>a.fullName===fullName).length!==1)throw Error('Exact 24/1 roster');const pattern='^'+fullName.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$';
 fs.mkdirSync(dir);write('process-readiness.json',processes());write('runtime-roster.json',{head:read('signed-source.json').head,files:[file],entries,selectedFullName:fullName,testHashes:c.testHashes,baselinePath,baselineSha256:hash(fs.readFileSync(baselinePath)),collectionRepeated:false,expected:{total:24,active:1,filtered:23},environmentUnset:['TS_DRP_F5B_WIDE_DIAGNOSTIC'],testWatchdogMs:90000,outerContainmentMs:180000,sigtermGraceMs:5000,recordCap:4096,command:[node,vitest,'run',file,'--testNamePattern='+pattern,'--no-file-parallelism','--coverage.enabled=false','--reporter=default','--reporter=json','--outputFile='+path.join(dir,'focused.json')]});console.log(JSON.stringify({frozen:true,files:1,active:1,filtered:23,sourceSha256:c.testHashes[file],runtimeNotExecuted:true}));
}else if(process.argv[2]==='run'){
 custody();const roster=read('runtime-roster.json'),launch=read('launch-identity.json');for(const [f,h]of [[launch.node,launch.nodeSha256],[launch.vitest,launch.vitestSha256]])if(hash(fs.readFileSync(f))!==h)throw Error('Launcher identity drift');write('environment-port-readiness-at-run.json',environmentAndPorts());const childEnvironment={...process.env};delete childEnvironment.TS_DRP_F5B_WIDE_DIAGNOSTIC;write('process-readiness-at-run.json',processes());const started=process.hrtime.bigint(),events=[],stdout=fs.openSync(path.join(dir,'stdout.log'),'wx'),stderr=fs.openSync(path.join(dir,'stderr.log'),'wx');write('wide-only/command.json',{cwd:root,command:roster.command,environmentUnset:roster.environmentUnset,outerContainmentMs:180000,sigtermGraceMs:5000});
 const child=spawn(roster.command[0],roster.command.slice(1),{cwd:root,env:childEnvironment,detached:true,stdio:['ignore','pipe','pipe']});write('wide-only/execution-start.json',{head:roster.head,recorderPid:process.pid,childPid:child.pid,ownedProcessGroup:child.pid,startedAt:new Date().toISOString()});console.log(JSON.stringify({recorderPid:process.pid,childPid:child.pid,ownedProcessGroup:child.pid,active:1,filtered:23}));
 child.stdout.on('data',b=>fs.writeSync(stdout,b));child.stderr.on('data',b=>fs.writeSync(stderr,b));let closed=false,result,spawnError,finished=false;
 const elapsed=()=>Number(process.hrtime.bigint()-started)/1e6;
 const members=()=>{const r=spawnSync('ps',['-axo','pid=,ppid=,pgid=,stat='],{encoding:'utf8'});if(r.status!==0)throw Error('Numeric process-group snapshot');return r.stdout.trim().split('\n').map(s=>s.trim().split(/\s+/u)).filter(a=>Number(a[2])===child.pid).map(a=>({pid:Number(a[0]),ppid:Number(a[1]),pgid:Number(a[2]),status:a[3]}));};
 const signalOwned=signal=>{const rows=members();events.push({action:signal,elapsedMs:elapsed(),members:rows});if(rows.length){try{process.kill(-child.pid,signal)}catch(e){if(e.code!=='ESRCH')throw e;}}};
 const term=setTimeout(()=>signalOwned('SIGTERM'),180000),kill=setTimeout(()=>signalOwned('SIGKILL'),185000),last=setTimeout(()=>{events.push({action:'post-SIGKILL-quiescence-check',elapsedMs:elapsed(),members:members()});finish(false);},187000);
 const poll=setInterval(()=>{if(closed&&members().length===0)finish();},250);
 child.on('error',e=>{spawnError=String(e)});child.on('close',(code,signal)=>{closed=true;result={code,signal};if(members().length===0)finish();});
 function finish(quiescent=true){if(finished)return;finished=true;clearTimeout(term);clearTimeout(kill);clearTimeout(last);clearInterval(poll);fs.closeSync(stdout);fs.closeSync(stderr);write('wide-only/status.json',{...result,spawnError,elapsedMs:elapsed(),endedAt:new Date().toISOString(),watchdogActions:events,ownedProcessGroup:child.pid,quiescent});console.log(JSON.stringify({terminal:true,...result,elapsedMs:elapsed(),watchdogActions:events.length,quiescent}));if(!quiescent)process.exit(1);process.exitCode=result?.code??1;}
}else throw Error('Mode');
