import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const out=path.dirname(new URL(import.meta.url).pathname),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
if(fs.existsSync(path.join(out,'manifest.sha256')))throw Error('Already sealed');const result=read('wide-only/validation.json'),custody=read('custody-final.json'),signed=read('signed-source.json');if(!result.valid||!result.exactNames||!result.exactFiles||result.total!==24||result.passed!==1||result.failed!==0||result.filtered!==23||!result.noDiagnosticRecords||result.selected.length!==1||result.selected[0].duration!==69154.209667||!result.status.quiescent||result.status.watchdogActions.length)throw Error('Exact focused GREEN');
if(read('custody-final/status.json').code!==0||read('typecheck-matrix/status.json').code!==0||custody.head!==signed.head||custody.testHashes[signed.file]!==signed.sha256)throw Error('Final source/static custody');const execution=read('wide-only/execution-start.json'),pids=[execution.recorderPid,execution.childPid];for(const pid of pids){const p=spawnSync('ps',['-p',String(pid),'-o','pid=,stat='],{encoding:'utf8'});if(![0,1].includes(p.status)||p.stdout.trim())throw Error('Owned runtime active');}
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]),statuses=walk(out).filter(f=>path.basename(f)==='status.json').sort().map(f=>({file:path.relative(out,f),...JSON.parse(fs.readFileSync(f))})),nonzero=statuses.filter(s=>(s.status??s.code)!==0).map(s=>({file:s.file,status:s.status??s.code}));if(JSON.stringify(nonzero)!==JSON.stringify([{file:'typecheck/status.json',status:1}]))throw Error('Unexpected captured status');
write('command-status-inventory.json',statuses);write('seal-summary.json',{focusedGreen:true,parentClosed:false,sourceHead:signed.head,sourceSha256:signed.sha256,total:24,passed:1,failed:0,filtered:23,selectedDurationMs:result.selected[0].duration,reporterSha256:result.reporterSha256,runtimeValidationSha256:hash(fs.readFileSync(path.join(out,'wide-only/validation.json'))),runtimeStatusSha256:hash(fs.readFileSync(path.join(out,'wide-only/status.json'))),rosterSha256:hash(fs.readFileSync(path.join(out,'runtime-roster.json'))),capturedStatuses:statuses.length,nonzero,soleFocusedInvocation:true,noDiagnosticRecords:true,noProfiling:true,noCombinedOrIsolatedRun:true,wholeProgramStaticPass:false,externalSnapshotDiagnostics:3,gridAndFourRegistryW0FailuresRemainOpen:true,custody:'custody-final.json',effectiveHashes:85,stashes:27,protectedPaths:86522,parentPatchSha256:custody.patchSha256,ownedRuntimePidsAbsent:pids});
const files=walk(out).sort(),manifest=files.map(f=>hash(fs.readFileSync(f))+'  '+path.relative(out,f)).join('\n')+'\n';fs.writeFileSync(path.join(out,'manifest.sha256'),manifest,{flag:'wx'});console.log(JSON.stringify({entries:files.length,manifestSha256:hash(manifest),capturedStatuses:statuses.length,nonzero,focusedGreen:true,parentClosed:false}));
