import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),roster=read('runtime-roster.json'),status=read('wide-only/status.json');let report,reporterError,assertions=[];
try{report=read('wide-only/focused.json');assertions=report.testResults.flatMap(s=>s.assertionResults.map(a=>({file:path.relative(root,s.name),...a})));}catch(e){reporterError=String(e);}
const identity=a=>JSON.stringify([a.file,a.title,a.ancestorTitles,a.fullName]),exactNames=JSON.stringify(assertions.map(identity).sort())===JSON.stringify(roster.entries.map(identity).sort()),exactFiles=report?.testResults.length===1&&path.relative(root,report.testResults[0].name)===roster.files[0],selected=assertions.filter(a=>a.fullName===roster.selectedFullName),filtered=assertions.filter(a=>a.fullName!==roster.selectedFullName),suiteErrors=report?.testResults.filter(s=>s.message||s.testExecError||s.status!=='passed')??[],noTopErrors=!suiteErrors.length&&!report?.numRuntimeErrorTestSuites&&!report?.numUnhandledErrors&&!report?.unhandledErrors?.length,snapshot=report?.snapshot,snapshotUnchanged=snapshot?.failure===false&&snapshot.added===0&&snapshot.updated===0&&snapshot.unmatched===0&&snapshot.filesAdded===0&&snapshot.filesRemoved===0&&snapshot.filesUpdated===0;
const stdout=fs.readFileSync(path.join(out,'wide-only/stdout.log')),stderr=fs.readFileSync(path.join(out,'wide-only/stderr.log')),noDiagnosticRecords=!stdout.includes('F5B_WIDE_DIAGNOSTIC')&&!stderr.includes('F5B_WIDE_DIAGNOSTIC');
const valid=status.code===0&&!status.signal&&!status.spawnError&&status.quiescent&&status.watchdogActions.length===0&&report?.success===true&&exactNames&&exactFiles&&report.numTotalTests===24&&report.numPassedTests===1&&report.numFailedTests===0&&report.numPendingTests===23&&report.numTodoTests===0&&selected.length===1&&selected[0].status==='passed'&&selected[0].failureMessages.length===0&&filtered.length===23&&filtered.every(a=>['pending','skipped'].includes(a.status)&&a.failureMessages.length===0)&&noTopErrors&&snapshotUnchanged&&noDiagnosticRecords;
write('wide-only/validation.json',{valid,status,reporterError,exactNames,exactFiles,success:report?.success,total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,filtered:report?.numPendingTests,todo:report?.numTodoTests,noTopErrors,suiteErrors,snapshot,snapshotUnchanged,noDiagnosticRecords,selected,assertions,reporterSha256:report&&hash(fs.readFileSync(path.join(out,'wide-only/focused.json'))),stdoutSha256:hash(stdout),stderrSha256:hash(stderr),parentClosed:false});console.log(JSON.stringify({valid,total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,filtered:report?.numPendingTests,selectedDuration:selected[0]?.duration,noDiagnosticRecords,reporterError}));if(!valid)process.exitCode=1;
