export const CIRCUIT_RELAY_V2_HOP_PROTOCOL = "/libp2p/circuit/relay/0.2.0/hop";

export const RELAY_RESERVATION_STATUS = {
	CONNECTION_FAILED: 203,
	MALFORMED_MESSAGE: 400,
	NO_RESERVATION: 204,
	OK: 100,
	PERMISSION_DENIED: 202,
	RESERVATION_REFUSED: 200,
	RESOURCE_LIMIT_EXCEEDED: 201,
	UNEXPECTED_MESSAGE: 401,
} as const;
