import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import ts from '/Users/aristotle/Documents/Projects/ts-drp-1/node_modules/typescript/lib/typescript.js';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),stage=process.argv[2],file='tests/phase-6a-creator-successor-product-red.test.ts',baseHead='61a793d38a9fa1eafd9639aa41de2335f9891695';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>fs.readFileSync(path.join(root,f)),git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8'}).trim();
const baseline=JSON.parse(read('.logs/d110c-0c1f5b-green-57834387/custody-before.json')),prior=JSON.parse(read('.logs/d110c-0c1f5b-green-transport-e122e280/custody-after.json'));
for(const[f,d]of Object.entries(prior.ownerHashes))if(hash(read(f))!==d)throw Error('Production drift '+f);
const patch=execFileSync('git',['diff','--binary','--full-index','--',...Object.keys(prior.ownerHashes)],{cwd:root});
if(hash(patch)!==prior.patchSha256||hash(patch)!=='245c2b251c5dfc9389c9732319c8e1b474cf2740252dff3d107320121e6564ed')throw Error('Patch drift');
if(git('stash','list','--format=%H %gd %s')!==baseline.stashes.trim())throw Error('Stashes');
for(const f of baseline.untracked)if(!fs.existsSync(path.join(root,f)))throw Error('Protected missing '+f);
const immutable=[];for(const dir of [...Object.keys(prior.manifests),'.logs/d110c-0c1f5b-green-transport-e122e280','.logs/d110c-0c1f5b-red-room-guard-da874b52']){const m=read(dir+'/manifest.sha256').toString();for(const line of m.trim().split('\n')){const[,d,f]=line.match(/^([a-f0-9]{64})\s+(.+)$/u);if(hash(read(dir+'/'+f))!==d)throw Error('Immutable drift '+dir+'/'+f)}immutable.push({dir,entries:m.trim().split('\n').length,sha256:hash(m)})}
const retainedHashes={};for(const[f,d]of Object.entries(prior.testHashes)){if(f===file)continue;if(hash(read(f))!==d)throw Error('Retained drift '+f);retainedHashes[f]=d}
const oldBuilt=JSON.parse(read('.logs/d110c-0c1f5b-green-ab98cce6/runtime-test-custody-after.json')).built,built={};for(const[f,r]of Object.entries(oldBuilt)){if(hash(read(f))!==r.sha256)throw Error('Built drift '+f);built[f]=r.sha256}
const previous=execFileSync('git',['show',baseHead+':'+file],{cwd:root,encoding:'utf8'}),current=read(file).toString();
function scope(text){const unit=ts.createSourceFile(file,text,ts.ScriptTarget.Latest,true),statements=unit.statements.filter(n=>!ts.isImportDeclaration(n)),titles=[],bodies=[];function visit(n){if(ts.isCallExpression(n)&&ts.isIdentifier(n.expression)&&n.expression.text==='it'&&ts.isStringLiteral(n.arguments[0])){titles.push(n.arguments[0].text);bodies.push(n.arguments[1].getText(unit))}ts.forEachChild(n,visit)}visit(unit);if(unit.parseDiagnostics.length)throw Error('Syntax');return{statements:statements.map(n=>n.getFullText(unit)),titles,bodies}}
const labelBase=execFileSync('git',['show','435bb0ef753b3d62729e776e476a22f26ba73c9f:'+file],{cwd:root,encoding:'utf8'});if(labelBase.split('createV3ChatApplication("guard")').length!==2||labelBase.replace('createV3ChatApplication("guard")','createV3ChatApplication("alice")')!==current)throw Error('Outside sole label changed');
const stoppedIsolation=JSON.parse(read('.logs/d110c-0c1f5b-red-room-guard-da874b52/isolation-after.json'));for(const[f,d]of Object.entries(stoppedIsolation.sourceHashes))if(hash(fs.readFileSync(path.join(stoppedIsolation.root,f)))!==d)throw Error('Stopped source drift');for(const[f,d]of Object.entries(stoppedIsolation.runtimes))if(hash(fs.readFileSync(path.join(stoppedIsolation.root,f)))!==d.sha256)throw Error('Stopped runtime drift');
const a=scope(previous),b=scope(current);if(a.titles.length!==12||b.titles.length!==13||b.statements.length!==a.statements.length+2||JSON.stringify(a.statements)!==JSON.stringify(b.statements.slice(0,a.statements.length))||JSON.stringify(a.bodies)!==JSON.stringify(b.bodies.slice(0,12))||JSON.stringify(a.titles)!==JSON.stringify(b.titles.slice(0,12)))throw Error('Original scope drift');
if(git('rev-parse','HEAD')!=='ba15bb894d324bb8d8a0d8a7da3f3e61042a0283'||git('log','-1','--format=%G?')!=='G')throw Error('Signed test identity');
const source='examples/v3-room/src/index.ts',signed=execFileSync('git',['show','ba15bb894d324bb8d8a0d8a7da3f3e61042a0283:'+source],{cwd:root,encoding:'utf8'}),dirty=read(source).toString();
const excerpts={};for(const[name,text]of Object.entries({signed,dirty})){const start=text.indexOf('async function createV3RoomSessionOwned');excerpts[name]=text.slice(start,start+6500)}
const data={stage,head:git('rev-parse','HEAD'),signature:'G',productionHashes:prior.ownerHashes,partialPatchSha256:hash(patch),retainedHashes,built,stashCount:27,stashesSha256:hash(baseline.stashes),protectedPaths:baseline.untracked.length,allProtectedPathsExist:true,immutable,originalTitles:a.titles,titles:b.titles,originalBodyHashes:a.bodies.map(hash),allOriginalNonImportBytesIdentical:true,syntaxDiagnostics:0,appendedStatements:2,soleLabelChange:true,stoppedCheckoutPreserved:true,testSha256:hash(current),sourceAttribution:{source,signedSha256:hash(signed),dirtySha256:hash(dirty),excerpts,bootstrapBeforeGuardInBoth:true,notSignerAcceptanceOrActivationProof:true,designCompatibility:'Legacy refusal retained; settlement creator cold reopen remains permitted; genuine integration owns authentication.'},trackedStatus:git('status','--short','--untracked-files=no')};
fs.writeFileSync(path.join(out,'custody-'+stage+'.json'),JSON.stringify(data,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({stage,head:data.head,originalBodies:12,totalTitles:13,productionOwners:8,built:7,retainedUnchanged:Object.keys(retainedHashes).length,protectedPaths:data.protectedPaths,stashCount:27}));
