import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
const root=fs.realpathSync('/tmp/d110c-f5b-red-room-guard-label-yqm8r2/checkout'),out=path.dirname(new URL(import.meta.url).pathname),cache='/tmp/d110c-f5b-red-room-guard-label-yqm8r2/npm-cache';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),write=(n,d)=>fs.writeFileSync(path.join(out,n),JSON.stringify(d,null,2)+'\n',{flag:'wx'});
if(fs.existsSync(path.join(out,'native-target.json'))||fs.existsSync(cache))throw Error('Native preparation/cache already exists');
const pkgDir=fs.realpathSync(path.join(root,'node_modules/.pnpm/node-datachannel@0.32.3/node_modules/node-datachannel')),pkgFile=path.join(pkgDir,'package.json'),pkg=JSON.parse(fs.readFileSync(pkgFile)),localRequire=createRequire(pkgFile),installer=fs.realpathSync(localRequire.resolve('prebuild-install/bin.js')),installerDir=path.dirname(installer),installerPkg=JSON.parse(fs.readFileSync(path.join(installerDir,'package.json')));
if(!pkgDir.startsWith(root+'/')||!installer.startsWith(root+'/')||pkg.name!=='node-datachannel'||pkg.version!=='0.32.3'||installerPkg.version!=='7.1.3')throw Error('Locked independent package identity differs');
const lock=fs.readFileSync(path.join(root,'pnpm-lock.yaml'),'utf8');
if(!lock.includes('  node-datachannel@0.32.3:')||!lock.includes('  prebuild-install@7.1.3:'))throw Error('Lock identity differs');
const native=path.join(pkgDir,'build/Release/node_datachannel.node');
if(fs.existsSync(native))throw Error('Native binary existed before independent fetch');
const forbidden=Object.keys(process.env).filter(k=>/^(?:prebuild_install_|npm_config_(?:node_datachannel_(?:binary_host(?:_mirror)?|local_prebuilds)|download|build_from_source|target|runtime|arch|platform|libc|debug|force|local_prebuilds)$|LIBC$|NODE_OPTIONS$)/iu.test(k)&&process.env[k]);
if(forbidden.length)throw Error('Unexpected native override keys present: '+forbidden.join(','));
process.env.npm_config_cache=cache;
const args=[installer,'-r','napi','--nolocal','--verbose'],priorArgv=process.argv;process.argv=[process.execPath,...args];
const rc=localRequire(path.join(installerDir,'rc.js'))(pkg);process.argv=priorArgv;
const util=localRequire(path.join(installerDir,'util.js')),opts={...rc,pkg},url=util.getDownloadUrl(opts);
const expected='https://github.com/murat-dogan/node-datachannel/releases/download/v0.32.3/node-datachannel-v0.32.3-napi-v8-'+process.platform+'-'+process.arch+'.tar.gz';
if(pkg.repository?.url!=='git+https://github.com/murat-dogan/node-datachannel.git'||pkg.binary?.napi_versions?.join(',')!=='8'||rc.runtime!=='napi'||Number(rc.target)!==8||Number(rc.abi)!==8||Number(process.versions.napi)<8||rc.platform!==process.platform||rc.arch!==process.arch||rc.libc!==''||rc.path!==pkgDir||rc.nolocal!==true||rc.verbose!==true||rc.buildFromSource||rc.force||rc.debug||rc.download||rc.token||rc['tag-prefix']!=='v'||url!==expected||util.prebuildCache()!==path.join(cache,'_prebuilds'))throw Error('Native resolved public target or unsafe override differs');
const inputFiles=[pkgFile,...['bin.js','package.json','rc.js','util.js','download.js'].map(f=>path.join(installerDir,f))],inputHashes=Object.fromEntries(inputFiles.map(f=>[path.relative(root,f),hash(fs.readFileSync(f))]));
const archive=util.cachedPrebuild(url);
write('native-target.json',{root,pkgDir,packageVersion:pkg.version,installer,installerVersion:installerPkg.version,inputHashes,lockSha256:hash(lock),url,expectedUrl:expected,target:Number(rc.target),abi:Number(rc.abi),runtime:rc.runtime,platform:rc.platform,arch:rc.arch,hostNapi:Number(process.versions.napi),hostNode:process.version,command:[process.execPath,...args],cwd:pkgDir,cache,archive,native,nativeInitiallyAbsent:true,freshCache:true,overrideValuesNotDisclosed:true,unexpectedOverrides:false,noNpxAcquisition:true,noFallback:true,configSourceCount:Array.isArray(rc.configs)?rc.configs.length:0});
console.log(JSON.stringify({stage:'native-target-verified',url,target:Number(rc.target),platform:rc.platform,arch:rc.arch,hostNapi:Number(process.versions.napi),installerVersion:installerPkg.version,freshCache:true}));
const status=await new Promise(resolve=>{const child=spawn(process.execPath,[path.join(out,'run.mjs'),'native-prebuild',pkgDir,process.execPath,...args],{stdio:'inherit',env:process.env});child.on('error',()=>resolve(1));child.on('close',code=>resolve(code??1))});
if(status!==0)throw Error('Native prebuild failed; no retry or fallback');
if(!fs.existsSync(archive)||!fs.existsSync(native)||!fs.realpathSync(native).startsWith(root+'/'))throw Error('Downloaded archive/native binary absent or outside checkout');
for(const[f,d]of Object.entries(inputHashes))if(hash(fs.readFileSync(path.join(root,f)))!==d)throw Error('Installer/package inputs changed');
fs.mkdirSync(path.join(out,'artifacts'));
const artifacts={};for(const [name,file]of [['node-datachannel-v0.32.3-napi-v8-'+process.platform+'-'+process.arch+'.tar.gz',archive],['node_datachannel.node',native]]){const dest=path.join(out,'artifacts',name);fs.copyFileSync(file,dest,fs.constants.COPYFILE_EXCL);artifacts[name]={source:file,bytes:fs.statSync(file).size,sha256:hash(fs.readFileSync(file)),retained:path.relative(out,dest)}}
write('native-artifacts.json',{url,artifacts,fromFreshDownload:true,noSharedNativeBinary:true,installerInputHashesUnchanged:true});
console.log(JSON.stringify({stage:'native-prebuild-complete',artifacts}));
