import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const report=JSON.parse(fs.readFileSync(path.join(out,'browser-collection/stdout'))),entries=[];
function visit(s){for(const spec of s.specs??[])for(const t of spec.tests)entries.push({file:spec.file,title:spec.title,project:t.projectName,timeout:t.timeout});for(const next of s.suites??[])visit(next);}for(const s of report.suites)visit(s);
const paths=['packages/storage-browser/playwright.phase-6a-creator-successor-activation.config.ts','packages/storage-browser/tests/phase-6a-creator-successor-activation.pw.ts','packages/storage-browser/tests/phase-6a-creator-successor-activation-global-setup.ts','packages/storage-browser/tests/phase-4c-browser-server.ts','packages/storage-browser/tests/assets/phase-6a-creator-successor-activation-entry.ts','packages/storage-browser/tests/assets/phase-6a-creator-successor-activation-worker.ts','tests/fixtures/phase-6a-v3/creator-adoption-contract.ts','tests/fixtures/phase-6a-v3/creator-successor-activation-contract.ts'];
const result={owner:'root',collectionOnly:true,testExecutions:0,plannedCases:24,entries,command:['pnpm','exec','playwright','test','--config','packages/storage-browser/playwright.phase-6a-creator-successor-activation.config.ts','--reporter=line,json','--output=<new owned evidence browser-output>'],environment:{PLAYWRIGHT_JSON_OUTPUT_FILE:'<new owned evidence browser-result.json>'},projects:['chromium','firefox','webkit'],workers:1,retries:0,globalTimeout:300000,server:{launcher:'startPhase4cBrowserServer',source:'packages/storage-browser/tests/phase-4c-browser-server.ts',bundleWrite:false,listen:{port:0,host:'127.0.0.1'},externalServerCommand:null},shim:{root:'tests/fixtures/node_modules/@ts-drp',parent:'tests/fixtures/node_modules',rootAbsentNow:!fs.existsSync(path.join(root,'tests/fixtures/node_modules/@ts-drp')),parentAbsentNow:!fs.existsSync(path.join(root,'tests/fixtures/node_modules')),requirePreAndPostAbsence:true,neverRemoveCallerOwnedShim:true},dynamicHelperPath:'browser beforeAll imports creator-adoption-contract.ts and creator-successor-activation-contract.ts using pathToFileURL(resolve(REPOSITORY_ROOT,...)); omission retains legacy profile exactly',sourceHashes:Object.fromEntries(paths.map(f=>[f,hash(fs.readFileSync(path.join(root,f)))])),freshSource:{pattern:'.logs/d110c-0c1f5b-snapshot-fixture-green-dc2f8dc2/isolated',installation:['pnpm','install','--offline','--frozen-lockfile','--ignore-scripts'],nativeRunner:'isolated/native-prepare.mjs adapted to a unique checkout and fresh npm-cache (locked node-datachannel 0.32.3,prebuild-install7.1.3,NAPI8); no shared native or node_modules/dist',build:['pnpm','build:packages'],compilerRoots:JSON.parse(fs.readFileSync(path.join(out,'program-identity-final.json'))).files,focusedAndRetained:'Repeat exactly runtime-roster.json in independent source-built checkout with preserved production overlay; never build main protected artifacts'}};
if(entries.length!==24||report.errors.length)throw Error('Browser list mismatch');fs.writeFileSync(path.join(out,'browser-handoff.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({plannedCases:entries.length,projects:result.projects,shim:result.shim}));
