import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname);
function environmentAndPorts(){const inherited=process.env.NODE_OPTIONS??'',profiling=/--(?:cpu[-_]prof|heap[-_]prof|prof(?:\b|[-_]))/u.test(inherited)||process.execArgv.some(a=>/--(?:cpu[-_]prof|heap[-_]prof|prof(?:\b|[-_]))/u.test(a));if(profiling||process.env.NODE_V8_COVERAGE)throw Error('Inherited profiling environment rejected');const ports=[];for(const port of [4174,4175,51000,51002]){const r=spawnSync('lsof',['-nP','-iTCP:'+port,'-sTCP:LISTEN','-t'],{encoding:'utf8'});if(![0,1].includes(r.status))throw Error('Fixed-port query');const pids=r.stdout.trim().split(/\s/u).filter(s=>/^\d+$/u.test(s)).map(Number);ports.push({port,pids,noTcpListener:pids.length===0});if(pids.length)throw Error('Fixed server port occupied '+port);}return{profilingNodeOptionsRejected:true,inheritedProfilingDetected:false,nodeOptionsPresent:Boolean(inherited),nodeV8CoverageAbsent:true,diagnosticVariableExplicitlyUnsetForChild:true,sourceLoggingOptInRemainsUnchanged:true,ports,listenerRefinement:'Root approved after unrelated established outbound socket was observed; no process killed; actual bind failures remain gate failures.'};}
function processes(){const r=spawnSync('pgrep',['-f','(vitest|quint|apalache|heap-prof|cpu-prof)'],{encoding:'utf8'});if(![0,1].includes(r.status))throw Error('PID query');const rows=[];for(const pid of r.stdout.trim().split(/\s/u).filter(s=>/^\d+$/u.test(s)).map(Number).filter(p=>p!==process.pid&&p!==process.ppid)){const s=spawnSync('ps',['-p',String(pid),'-o','pid=,ppid=,stat='],{encoding:'utf8'});if(s.status===1)continue;if(s.status!==0)throw Error('PID status');const cwd=spawnSync('lsof',['-a','-p',String(pid),'-d','cwd','-Fn'],{encoding:'utf8'}),relevant=cwd.stdout.split('\n').filter(v=>v.startsWith('n')).some(v=>v.slice(1)===root||v.slice(1).startsWith(root+'/')||/^\/(?:private\/)?tmp\/d110c-f5b-/u.test(v.slice(1)));rows.push({pid,status:s.stdout.trim(),taskRelevantCwd:relevant});if(relevant)throw Error('Competing task runtime PID '+pid);}return{numericOnly:true,noArgvOrComm:true,candidates:rows,taskCompetitors:0,unrelatedProcessesDoNotBlock:true};}


const groups=[12948,23475,24907,34006],ps=spawnSync('ps',['-axo','pid=,ppid=,pgid=,stat='],{encoding:'utf8'});if(ps.status!==0)throw Error('Numeric process query failed');const members=ps.stdout.trim().split('\n').map(s=>s.trim().split(/\s+/u)).filter(a=>groups.includes(Number(a[2])));if(members.length)throw Error('Owned completed process group not empty');const result={environment:environmentAndPorts(),processes:processes(),completedRuntimeGroups:groups,allGroupsEmpty:true,sourceIndexAndParentArtifactsNotMutated:true};fs.writeFileSync(path.join(out,'quiescence-final.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result));
