import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),read=n=>JSON.parse(fs.readFileSync(path.join(out,n),'utf8')),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),actual=read('diagnostics.json'),prior=JSON.parse(fs.readFileSync(path.join(root,'.logs/d110c-0c1f5b-green-room-guard-db8a8615/typecheck-final.json'),'utf8')),status=read('compiler-red/status.json'),identity=read('program-identity.json');
const groups=actual.diagnostics.reduce((m,d)=>{const k=d.file+' TS'+d.code;m[k]=(m[k]??0)+1;return m},{}),expected={'tests/fixtures/phase-6a-v3/creator-adoption-contract.ts TS7006':34,'tests/fixtures/phase-6a-v3/creator-adoption-contract.ts TS2322':1,'tests/fixtures/phase-6a-v3/creator-adoption-contract.ts TS2739':1,'tests/fixtures/phase-6a-v3/creator-successor-product-contract.ts TS2339':5};
const same=JSON.stringify(actual.diagnostics)===JSON.stringify(prior.current),sameOptions=JSON.stringify(actual.options)===JSON.stringify(prior.options);
if(status.code!==1||status.signal||status.spawnError||actual.programExecutions!==1||identity.programExecutions!==1||actual.typecheckPassed||actual.diagnosticCount!==41||!same||!sameOptions||JSON.stringify(groups)!==JSON.stringify(expected))throw Error('Unexpected compiler RED matrix');
for(const s of identity.sources)if(hash(fs.readFileSync(s.file))!==s.onDiskSha256)throw Error('Program source drift '+s.file);
fs.writeFileSync(path.join(out,'matrix-validation.json'),JSON.stringify({classification:'CAUSAL_COMPILER_RED_EXACT41',matrixValid:true,compilerTerminalExit:1,matrixValidatorExit:0,typecheckPassed:false,programExecutions:1,diagnosticCount:41,exactCompleteRows:true,effectiveOptionsIdentical:true,compilerVersion:actual.compilerVersion,groups,targetDiagnostics:0,productionDiagnostics:0,sourceInputs:identity.sources.length,readInputs:identity.readInputs.length,resolvedModules:identity.resolvedModules.length,resolvedTypeReferences:identity.resolvedTypeReferences.length,diagnosticsSha256:hash(fs.readFileSync(path.join(out,'diagnostics.json'))),acceptedCurrentDiagnostics:prior.current},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({matrixValid:true,compilerTerminalExit:1,matrixValidatorExit:0,diagnosticCount:41,target:0,production:0,groups}));
