import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import ts from '/Users/aristotle/Documents/Projects/ts-drp-1/node_modules/typescript/lib/typescript.js';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),file='tests/phase-6b-d110c-0c1f5b-snapshot-fixture-contract-red.test.ts';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>fs.readFileSync(path.resolve(root,f)),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const source=read(file).toString(),unit=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true),tests=[],assertions=[],recoveries=[],imports=[];
assert.equal(unit.parseDiagnostics.length,0);
function visit(n){if(ts.isImportDeclaration(n))imports.push(n.moduleSpecifier.text);if(ts.isCallExpression(n)){if(n.expression.getText(unit)==='it')tests.push(n);if(n.expression.getText(unit)==='expect')assertions.push({start:n.getStart(unit),line:unit.getLineAndCharacterOfPosition(n.getStart(unit)).line+1,text:n.getText(unit)});if(n.expression.getText(unit)==='recoverV3LiveReplica')recoveries.push(n);}ts.forEachChild(n,visit);}visit(unit);
assert.equal(tests.length,1);assert.equal(tests[0].arguments.length,2);assert.equal(recoveries.length,1);
const title=tests[0].arguments[0].text,token='F5B_SNAPSHOT_FIXTURE_SUCCESSOR_INSTALL_REJECTS_WITHOUT_MUTATION';
assert.equal(assertions.filter(a=>a.text.includes(token)).length,1);assert.ok(assertions.at(-1).text.includes(token));assert.ok(recoveries[0].getStart(unit)<assertions.at(-1).start);
assert.ok(source.includes('typeof bindings.journal.installEpochAnchor === "function"'));assert.ok(source.includes('kind: "missing-required-rejection"'));assert.ok(!source.includes('vi.mock('));
const program=JSON.parse(read(path.join(out,'program-identity.json')));for(const s of program.sources)assert.equal(hash(fs.readFileSync(s.file)),s.sha256,s.file);
const protectedSources=['tests/fixtures/phase-4b-v3/live-snapshot.ts','tests/fixtures/phase-3a1b-p3/live-fixture.ts','packages/live-journal/src/types.ts','packages/issuance-store/src/types.ts'];
const protectedHashes=Object.fromEntries(protectedSources.map(f=>[f,hash(read(f))]));
for(const f of protectedSources)assert.deepEqual(read(f),execFileSync('git',['show','03acb4ac:'+f],{cwd:root,maxBuffer:32*1024*1024}),f);
const configFiles=['tsconfig.json','vite.config.mts','pnpm-lock.yaml','.npmrc','package.json','node_modules/typescript/package.json','node_modules/vitest/package.json','node_modules/vite/package.json'];
const configHashes=Object.fromEntries(configFiles.map(f=>[f,{physical:fs.realpathSync(path.join(root,f)),sha256:hash(read(f))}]));
const command=['pnpm','exec','vitest','run',file,'--no-file-parallelism','--coverage.enabled=false','--reporter=default','--reporter=json','--outputFile='+path.join(out,'focused.json')];
write('source-freeze.json',{file,sha256:hash(source),syntaxDiagnostics:0,title,fullName:'D.110c-0c1f5b live snapshot fixture contract '+title,tests:1,assertionCount:assertions.length,assertions,recoveryCalls:1,recoveryBeforeFinalOutcome:true,protectedHashes,configHashes,node:{version:process.version,path:process.execPath,sha256:hash(fs.readFileSync(process.execPath))},typescript:ts.version,command,expected:{total:1,passed:0,failed:1,skipped:0,token,actualObservation:'missing-required-rejection'},runtimeExecuted:false});
fs.writeFileSync(path.join(out,'test-source.ts'),source,{flag:'wx'});
console.log(JSON.stringify({syntaxDiagnostics:0,tests:1,assertions:assertions.length,recoveryCalls:1,sha256:hash(source),runtimeExecuted:false}));
