import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync,execFileSync} from 'node:child_process';
const root=fs.realpathSync('/tmp/d110c-f5b-green-adoption-static-Eqj4VS/checkout'),out=path.dirname(new URL(import.meta.url).pathname),parent=path.dirname(out),read=f=>JSON.parse(fs.readFileSync(f)),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),mainRoster=read(path.join(parent,'runtime-roster.json')),head='210fecb0bec1ac1d61b0325e2c72d8c42c251572';
if(process.argv[2]==='freeze'){
 const command=['pnpm','exec','vitest','run',...mainRoster.files,'--no-file-parallelism','--coverage.enabled=false','--reporter=default','--reporter=json','--outputFile='+path.join(out,'focused.json')];
 write('runtime-roster.json',{...mainRoster,head,command,mainRosterSha256:hash(fs.readFileSync(path.join(parent,'runtime-roster.json'))),isolatedRoot:root,selectionUnchanged:true});console.log(JSON.stringify({frozen:true,files:mainRoster.files.length,total:mainRoster.entries.length}));
}else if(process.argv[2]==='run'){
 if(fs.existsSync(path.join(out,'execution-start.json')))throw Error('Sole isolated runtime consumed');const roster=read(path.join(out,'runtime-roster.json'));
 if(execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim()!==head)throw Error('Signed identity drift');
 for(const label of ['clone','sparse','checkout','patch-check','patch-apply','install','custody-prepared','native-preparation','native-prebuild','native-addon-import','build','node-root-import','compiler-green','custody-before'])if(read(path.join(out,label,'status.json')).code!==0)throw Error('Prerequisite '+label);
 const custody=read(path.join(out,'custody-before.json'));for(const[f,h]of Object.entries(custody.sourceHashes))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Source drift '+f);for(const[f,r]of Object.entries(custody.runtimes))if(hash(fs.readFileSync(path.join(root,f)))!==r.sha256)throw Error('Runtime drift '+f);
 write('command.json',{cwd:root,command:roster.command});write('execution-start.json',{head,recorderPid:process.pid,startedAt:new Date().toISOString(),executionCount:1,sourceCustodySha256:hash(fs.readFileSync(path.join(out,'custody-before.json')))});console.log(JSON.stringify({label:'isolated-78',recorderPid:process.pid}));
 const stdout=fs.openSync(path.join(out,'stdout.log'),'wx'),stderr=fs.openSync(path.join(out,'stderr.log'),'wx'),r=spawnSync(roster.command[0],roster.command.slice(1),{cwd:root,env:process.env,stdio:['ignore',stdout,stderr]});fs.closeSync(stdout);fs.closeSync(stderr);write('status.json',{status:r.status,signal:r.signal,error:r.error?.message,endedAt:new Date().toISOString()});
 const report=fs.existsSync(path.join(out,'focused.json'))?read(path.join(out,'focused.json')):null,assertions=report?.testResults.flatMap(s=>s.assertionResults.map(a=>({file:path.relative(root,s.name),...a})))??[],key=a=>a.file+'\0'+[...a.ancestorTitles,a.title].join(' > '),actual=assertions.map(key).sort(),expected=roster.entries.map(key).sort(),exactNames=JSON.stringify(actual)===JSON.stringify(expected),exactFiles=JSON.stringify(report?.testResults.map(s=>path.relative(root,s.name)).sort())===JSON.stringify([...roster.files].sort());
 const lines=fs.readFileSync(path.join(out,'stdout.log'),'utf8').split('\n').map(l=>l.trim()).filter(l=>l.startsWith('{"kind":"F5B_ROOM_GUARD_OBSERVATIONS"')),observations=lines.length===1?JSON.parse(lines[0]).observations:[],observationsValid=lines.length===1&&JSON.stringify(observations)===JSON.stringify(roster.expectedObservations);
 const valid=r.status===0&&!r.signal&&report?.success===true&&exactNames&&exactFiles&&report.numTotalTests===78&&report.numPassedTests===78&&report.numFailedTests===0&&report.numPendingTests===0&&!report.numRuntimeErrorTestSuites&&!report.numUnhandledErrors&&!(report.unhandledErrors?.length)&&report.testResults.every(s=>!s.message&&!s.testExecError)&&assertions.every(a=>a.status==='passed'&&a.failureMessages.length===0)&&observationsValid;
 write('validation.json',{valid,exactNames,exactFiles,observationsValid,rawObservationCount:lines.length,observations,success:report?.success,total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,skipped:report?.numPendingTests,numRuntimeErrorTestSuites:report?.numRuntimeErrorTestSuites??null,numUnhandledErrors:report?.numUnhandledErrors??null,unhandledErrors:report?.unhandledErrors??[],suites:report?.testResults.map(s=>({file:s.name,message:s.message,testExecError:s.testExecError??null})),assertions,reporterSha256:report?hash(fs.readFileSync(path.join(out,'focused.json'))):null});console.log(JSON.stringify({valid,total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,skipped:report?.numPendingTests,observationsValid}));if(!valid)process.exitCode=1;
}else throw Error('Unknown mode');
