import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync,execFileSync} from 'node:child_process';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),read=f=>JSON.parse(fs.readFileSync(f)),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),write=(f,v)=>fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n',{flag:'wx'}),mode=process.argv[2],head='b75e75ed8a0cc944139929c501eea684cde4e715';
if(mode==='freeze'){
 const accepted=read(path.join(root,'.logs/d110c-0c1f5b-red-room-guard-reporters-5f6fb6c0/matrix.json'));
 const gates=[{label:'focused-13',files:accepted.files,total:13,entries:accepted.entries.map(e=>({...e,expectedStatus:'passed'}))}];
 for(const[label,n,total]of [['bootstrap-3',52,3],['rebase-20',10,20]]){const report=read(path.join(root,'.logs/d110c-0c1f5b-green-ab98cce6/retained-'+n+'/result.json'));const entries=report.testResults.flatMap(s=>s.assertionResults.map(a=>({file:path.relative(root,s.name),name:[...a.ancestorTitles,a.title].join(' > '),expectedStatus:'passed'})));if(entries.length!==total)throw Error('Retained count');gates.push({label,files:[...new Set(entries.map(e=>e.file))],total,entries});}
 const observations=[];for(const profileId of ['creator-trusted-v1','creator-trusted-settlement-v1'])for(const composition of ['factory','rebase','signer','declaration-only']){const permitted=composition==='declaration-only'||composition==='signer'&&profileId==='creator-trusted-settlement-v1';observations.push({profileId,composition,detail:permitted?'D.108e2b application authority was read':'v3 room successor authority composition is unsupported',reads:{application:permitted?1:0,signer:0,store:0,transport:0}});}
 for(const g of gates)g.command=['pnpm','exec','vitest','run',...g.files,'--no-file-parallelism','--coverage.enabled=false',...(g.label==='focused-13'?['--reporter=default']:[]),'--reporter=json','--outputFile='+path.join(out,g.label,'focused.json')];
 write(path.join(out,'runtime-roster.json'),{head,gates,expectedObservations:observations,sourceCheckSha256:hash(fs.readFileSync(path.join(out,'source-check.json'))),collectionRepeated:false});console.log(JSON.stringify({gates:gates.map(g=>({label:g.label,total:g.total})),frozen:true}));
}else if(mode==='freeze-final'){
 const prior=read(path.join(out,'runtime-roster.json'));write(path.join(out,'runtime-roster-final.json'),{...prior,sourceCheckSha256:hash(fs.readFileSync(path.join(out,'source-check-final.json'))),supersedes:'runtime-roster.json',reason:'Explicit private return annotation formatting only; all frozen commands and selections unchanged.'});console.log(JSON.stringify({finalSourceBound:true,commandsAndSelectionsUnchanged:true}));
}else{
 const frozen=read(path.join(out,'runtime-roster-final.json')),index=frozen.gates.findIndex(g=>g.label===mode),gate=frozen.gates[index];if(!gate)throw Error('Unknown frozen gate');
 if(execFileSync('git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).trim()!==head)throw Error('HEAD drift');
 for(const label of ['room-lint-final','room-format-final','room-typecheck-final','room-source-check-final','room-diff-check-final'])if(read(path.join(out,label,'status.json')).status!==0)throw Error('Static gate '+label);
 if(index>0&&!read(path.join(out,frozen.gates[index-1].label,'validation.json')).valid)throw Error('Prior runtime not green');
 if(hash(fs.readFileSync(path.join(out,'source-check-final.json')))!==frozen.sourceCheckSha256)throw Error('Source check drift');
 const identity=read(path.join(out,'source-check-final.json'));for(const records of [identity.ownerHashes,identity.built,identity.testHashes])for(const[f,h]of Object.entries(records))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Source/runtime/test drift '+f);
 const dir=path.join(out,mode);fs.mkdirSync(dir);write(path.join(dir,'command.json'),{cwd:root,command:gate.command});write(path.join(dir,'execution-start.json'),{head,recorderPid:process.pid,startedAt:new Date().toISOString(),executionCount:1});console.log(JSON.stringify({label:mode,recorderPid:process.pid}));
 const stdout=fs.openSync(path.join(dir,'stdout.log'),'wx'),stderr=fs.openSync(path.join(dir,'stderr.log'),'wx'),r=spawnSync(gate.command[0],gate.command.slice(1),{cwd:root,env:process.env,stdio:['ignore',stdout,stderr]});fs.closeSync(stdout);fs.closeSync(stderr);write(path.join(dir,'status.json'),{status:r.status,signal:r.signal,error:r.error?.message,endedAt:new Date().toISOString()});
 const report=fs.existsSync(path.join(dir,'focused.json'))?read(path.join(dir,'focused.json')):null,assertions=report?.testResults.flatMap(s=>s.assertionResults.map(a=>({file:path.relative(root,s.name),...a})))??[],actual=assertions.map(a=>a.file+'\0'+[...a.ancestorTitles,a.title].join(' > ')).sort(),expected=gate.entries.map(e=>e.file+'\0'+e.name).sort();
 const exactNames=JSON.stringify(actual)===JSON.stringify(expected),exactFiles=JSON.stringify(report?.testResults.map(s=>path.relative(root,s.name)).sort())===JSON.stringify([...gate.files].sort());
 let observationsValid=true,observations=[];if(mode==='focused-13'){const lines=fs.readFileSync(path.join(dir,'stdout.log'),'utf8').split('\n').map(l=>l.trim()).filter(l=>l.startsWith('{"kind":"F5B_ROOM_GUARD_OBSERVATIONS"'));observations=lines.length===1?JSON.parse(lines[0]).observations:[];observationsValid=lines.length===1&&JSON.stringify(observations)===JSON.stringify(frozen.expectedObservations);write(path.join(dir,'observations.json'),{rawObservationCount:lines.length,observations,expected:frozen.expectedObservations,valid:observationsValid});}
 const valid=r.status===0&&!r.signal&&report?.success===true&&exactNames&&exactFiles&&report.numTotalTests===gate.total&&report.numPassedTests===gate.total&&report.numFailedTests===0&&report.numPendingTests===0&&!report.numRuntimeErrorTestSuites&&!report.numUnhandledErrors&&!(report.unhandledErrors?.length)&&report.testResults.every(s=>!s.message&&!s.testExecError)&&assertions.every(a=>a.status==='passed'&&a.failureMessages.length===0)&&observationsValid;
 write(path.join(dir,'validation.json'),{valid,exactNames,exactFiles,observationsValid,success:report?.success,total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,skipped:report?.numPendingTests,numRuntimeErrorTestSuites:report?.numRuntimeErrorTestSuites??null,numUnhandledErrors:report?.numUnhandledErrors??null,unhandledErrors:report?.unhandledErrors??[],suites:report?.testResults.map(s=>({file:s.name,message:s.message,testExecError:s.testExecError??null})),assertions,reporterSha256:report?hash(fs.readFileSync(path.join(dir,'focused.json'))):null});
 console.log(JSON.stringify({label:mode,valid,total:report?.numTotalTests,passed:report?.numPassedTests,failed:report?.numFailedTests,observationsValid}));if(!valid)process.exitCode=1;
}
