import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),stage=process.argv[2],target='tests/fixtures/phase-4b-v3/live-snapshot.ts',focused='tests/phase-6b-d110c-0c1f5b-snapshot-fixture-contract-red.test.ts',hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>fs.readFileSync(path.join(root,f)),json=f=>JSON.parse(read(f)),write=(f,v)=>fs.writeFileSync(path.join(out,f),v,{flag:'wx'}),git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:128*1024*1024}).trim();
if(!['before','after','final'].includes(stage))throw Error('stage');const prior=json('.logs/d110c-0c1f5b-green-wide90-fd4140d5/custody-final.json'),original=json('.logs/d110c-0c1f5b-green-57834387/custody-before.json'),head=git('rev-parse','HEAD');if(git('log','-1','--format=%G?')!=='G'||git('ls-remote','origin','refs/heads/codex/phase3a1b-p6-golden-path').split(/\s/u)[0]!==head||git('diff','--cached','--name-only')||(stage==='before'&&head!=='7ee552b59b3123223b19141b9fef1cd5be6cb2b0'))throw Error('HEAD/remote/index');
const testHashes={...prior.testHashes,[focused]:'24b7a57addf2b77ca6987cee6ac5f4d10586b63a23e0ed6c79d4dbdc78d28181'};for(const map of [prior.ownerHashes,prior.built,testHashes])for(const[f,h]of Object.entries(map))if(hash(read(f))!==h)throw Error('Custody '+f);
const intermediateFiles=['tests/fixtures/phase-4d-v3/shadow-driver.ts','tests/fixtures/phase-4d-v3/shadow-runner-driver.ts','tests/fixtures/phase-4d-v3/shadow-telemetry-driver.ts','tests/fixtures/phase-6b-d110c-0c1f5b0b/node-settlement-contract.ts'],fixtureHashes=stage==='before'?Object.fromEntries([target,...intermediateFiles].map(f=>[f,hash(read(f))])):JSON.parse(fs.readFileSync(path.join(out,'custody-before.json'))).fixtureHashes;
if(stage!=='before')fixtureHashes[target]=JSON.parse(fs.readFileSync(path.join(out,'equivalence.json'))).afterSha256;for(const[f,h]of Object.entries(fixtureHashes))if(hash(read(f))!==h)throw Error('Fixture drift '+f);
const patch=execFileSync('git',['diff','--binary','--full-index','--',...Object.keys(prior.ownerHashes)],{cwd:root,maxBuffer:128*1024*1024});if(hash(patch)!==prior.patchSha256)throw Error('Parent patch');if(git('stash','list','--format=%H %gd %gs')!==original.stashes.trim())throw Error('Stashes');for(const f of original.untracked)if(!fs.existsSync(path.join(root,f)))throw Error('Protected '+f);
const manifests={...prior.manifests,'.logs/d110c-0c1f5b-green-wide90-fd4140d5':'0c3a95d596fa74ddf38b8b538b7341944c42539498c12fe152dc82c885404439','.logs/d110c-0c1f5b-snapshot-fixture-red-03acb4ac':'94f6c450f4750041aacd90f7c4bda53879c00863092745eeaa3c22723fc17200'};for(const[dir,h]of Object.entries(manifests)){const m=read(dir+'/manifest.sha256');if(hash(m)!==h)throw Error('Manifest '+dir);for(const line of m.toString().trim().split('\n')){const[,d,f]=line.match(/^([a-f0-9]{64})\s+(.+)$/u);if(hash(read(f.startsWith('.logs/')?f:dir+'/'+f))!==d)throw Error('Evidence '+f)}}
for(const f of git('diff','--name-only').split('\n'))if(!Object.hasOwn(prior.ownerHashes,f)&&!(stage!=='before'&&f===target))throw Error('Dirty '+f);if(stage==='before'&&hash(read(target))!==hash(execFileSync('git',['show',head+':'+target],{cwd:root})))throw Error('Signed helper');
write('helper-'+stage+'.ts',read(target));write('custody-'+stage+'.json',JSON.stringify({stage,head,signature:'G',originExact:true,indexEmpty:true,ownerHashes:prior.ownerHashes,built:prior.built,testHashes,fixtureHashes,patchSha256:hash(patch),manifests,stashCount:27,protectedPaths:original.untracked.length,allProtectedPathsExist:true,trackedStatus:git('status','--short','--untracked-files=no')},null,2)+'\n');console.log(JSON.stringify({stage,owners:8,built:7,tests:Object.keys(testHashes).length,fixtures:Object.keys(fixtureHashes).length,stashes:27,protected:original.untracked.length,patchSha256:hash(patch)}));
