import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import ts from '/Users/aristotle/Documents/Projects/ts-drp-1/node_modules/typescript/lib/typescript.js';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),file='tests/fixtures/phase-4b-v3/live-snapshot.ts',before=fs.readFileSync(path.join(out,'helper-before.ts'),'utf8'),after=fs.readFileSync(path.join(root,file),'utf8'),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const rejector='\t\tinstallEpochAnchor: vi.fn(() =>\n\t\t\tPromise.reject(new Error("unexpected installEpochAnchor in live snapshot fixture"))\n\t\t),\n',annotation='(input: Parameters<DurableIssuanceStore["transactWriteSettlementPlan"]>[0])',construction='const nextPlan: SettlementPlan = Object.freeze({',tail='\t\t\tsettlementPlan = nextPlan;\n\t\t\treturn Promise.resolve(nextPlan);';
function replaceOne(text,a,b){if(text.split(a).length!==2)throw Error('Unique allowed span '+a);return text.replace(a,b)}
let restored=replaceOne(after,rejector,'');restored=replaceOne(restored,annotation,'(input)');restored=replaceOne(restored,construction,'settlementPlan = Object.freeze({');restored=replaceOne(restored,tail,'\t\t\treturn Promise.resolve(settlementPlan);');if(restored!==before)throw Error('Outside authorized spans changed');
const parse=text=>ts.createSourceFile(file,text,ts.ScriptTarget.Latest,true),old=parse(before),current=parse(after),functionText=(u,name)=>u.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name)?.getText(u);if(old.parseDiagnostics.length||current.parseDiagnostics.length)throw Error('Parse diagnostics');
const protectedFunctions=['fakeNetwork','lowerHex','recoveryCarrier','createRecoveryInput','recover','recoverLiveSnapshotPeer'];for(const name of protectedFunctions)if(functionText(old,name)!==functionText(current,name))throw Error('Protected function '+name);
const imports=u=>u.statements.filter(n=>ts.isImportDeclaration(n)||ts.isExportDeclaration(n)).map(n=>n.getText(u));if(JSON.stringify(imports(old))!==JSON.stringify(imports(current)))throw Error('Import/export/module effect');
const emit=text=>ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;let emitted=emit(after);emitted=replaceOne(emitted,'        installEpochAnchor: vi.fn(() => Promise.reject(new Error("unexpected installEpochAnchor in live snapshot fixture"))),\n','');emitted=replaceOne(emitted,'const nextPlan = Object.freeze({','settlementPlan = Object.freeze({');emitted=replaceOne(emitted,'            settlementPlan = nextPlan;\n            return Promise.resolve(nextPlan);','            return Promise.resolve(settlementPlan);');if(emitted!==emit(before))throw Error('Other emitted JS changed');
const production=fs.readFileSync(path.join(root,'packages/node/src/v3-live.ts'),'utf8'),branch='payload.provenance.epoch === 0 ? journal.installGenesis : journal.installEpochAnchor';if(production.split(branch).length!==2)throw Error('Existing epoch-zero dispatch');const shadow=fs.readFileSync(path.join(root,'tests/fixtures/phase-4d-v3/shadow-driver.ts'),'utf8');if(!shadow.includes('Promise.all([recover(fixture, fixture.capability), recover(fixture, second.capability)])'))throw Error('Existing shadow genesis recovery');
const data={valid:true,file,beforeSha256:hash(before),afterSha256:hash(after),entireFileReverseByteEqual:true,otherEmittedJsByteEqual:true,allowedRuntimeDelta:'New unsupported epoch installer rejects asynchronously without mutation; local plan value is assigned and returned unchanged',protectedFunctions:Object.fromEntries(protectedFunctions.map(n=>[n,hash(functionText(current,n))])),importsExportsAndModuleInitializationUnchanged:true,scopeRevisionCasEntryCopiesAndIssuePlanEffectsUnchanged:true,genesisDispatch:{file:'packages/node/src/v3-live.ts',branch,productionSha256:hash(production),epochZeroDoesNotReadAddedMethod:true},shadowBoundary:{unchangedDriver:true,noRuntimeCredit:true,noSynthetic100CloseSetup:true},noNewApiOrAuthority:true};fs.writeFileSync(path.join(out,'equivalence.json'),JSON.stringify(data,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({valid:true,beforeSha256:data.beforeSha256,afterSha256:data.afterSha256,entireFileReverseByteEqual:true,otherEmittedJsByteEqual:true}));
