import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync,spawn,spawnSync} from 'node:child_process';
const root='/Users/aristotle/Documents/Projects/ts-drp-1',out=path.dirname(new URL(import.meta.url).pathname),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(out,f))),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:128*1024*1024}).trim();
function environmentAndPorts(){const inherited=process.env.NODE_OPTIONS??'',profiling=/--(?:cpu[-_]prof|heap[-_]prof|prof(?:\b|[-_]))/u.test(inherited)||process.execArgv.some(a=>/--(?:cpu[-_]prof|heap[-_]prof|prof(?:\b|[-_]))/u.test(a));if(profiling||process.env.NODE_V8_COVERAGE)throw Error('Inherited profiling environment rejected');const ports=[];for(const port of [4174,4175,51000,51002]){const r=spawnSync('lsof',['-nP','-i:'+port,'-t'],{encoding:'utf8'});if(![0,1].includes(r.status))throw Error('Fixed-port query');const pids=r.stdout.trim().split(/\s/u).filter(s=>/^\d+$/u.test(s)).map(Number);ports.push({port,pids,unoccupied:pids.length===0});if(pids.length)throw Error('Fixed port occupied '+port);}return{profilingNodeOptionsRejected:true,inheritedProfilingDetected:false,nodeOptionsPresent:Boolean(inherited),nodeV8CoverageAbsent:true,diagnosticVariableExplicitlyUnsetForChild:true,sourceLoggingOptInRemainsUnchanged:true,ports,selectedFixtureUsesFakeNetworkAndNoFixedPortBinding:true};}
function processes(){const r=spawnSync('pgrep',['-f','(vitest|quint|apalache|heap-prof|cpu-prof)'],{encoding:'utf8'});if(![0,1].includes(r.status))throw Error('PID query');const rows=[];for(const pid of r.stdout.trim().split(/\s/u).filter(s=>/^\d+$/u.test(s)).map(Number).filter(p=>p!==process.pid&&p!==process.ppid)){const s=spawnSync('ps',['-p',String(pid),'-o','pid=,ppid=,stat='],{encoding:'utf8'});if(s.status===1)continue;if(s.status!==0)throw Error('PID status');const cwd=spawnSync('lsof',['-a','-p',String(pid),'-d','cwd','-Fn'],{encoding:'utf8'}),relevant=cwd.stdout.split('\n').filter(v=>v.startsWith('n')).some(v=>v.slice(1)===root||v.slice(1).startsWith(root+'/')||/^\/(?:private\/)?tmp\/d110c-f5b-/u.test(v.slice(1)));rows.push({pid,status:s.stdout.trim(),taskRelevantCwd:relevant});if(relevant)throw Error('Competing task runtime PID '+pid);}return{numericOnly:true,noArgvOrComm:true,candidates:rows,taskCompetitors:0,unrelatedProcessesDoNotBlock:true};}
function custody(){const c=read('custody-after.json'),signed=read('signed-source.json');if(git('rev-parse','HEAD')!==signed.head||git('log','-1','--format=%G?')!=='G'||git('diff','--cached','--name-only'))throw Error('HEAD/index drift');for(const map of [c.ownerHashes,c.built,c.testHashes,c.fixtureHashes])for(const[f,h]of Object.entries(map))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Source/runtime drift '+f);return c;}
if(process.argv[2]==='freeze'){
 const c=custody();for(const label of ['format','lint','diff','typecheck','typecheck-matrix','equivalence','collection','signed-source'])if(read(label+'/status.json').code!==0)throw Error('Ready gate '+label);
 const files=read('selected-files.json'),entries=JSON.parse(fs.readFileSync(path.join(out,'collection/stdout'),'utf8')).map(a=>({file:path.relative(root,a.file),name:a.name})),actualFiles=[...new Set(entries.map(a=>a.file))].sort();if(JSON.stringify(actualFiles)!==JSON.stringify([...files].sort())||entries.filter(a=>a.file===files[0]).length!==1)throw Error('Exact collection files');const node=fs.realpathSync(process.execPath),vitest=fs.realpathSync(path.join(root,'node_modules/vitest/vitest.mjs')),gates=['focused','retained'].map((label,i)=>{const selected=i===0?[files[0]]:files.slice(1),output=path.join(out,label,'result.json');return{label,files:selected,entries:entries.filter(a=>selected.includes(a.file)),command:[node,vitest,'run',...selected.map(f=>path.join(root,f)),'--no-file-parallelism','--coverage.enabled=false','--reporter=default','--reporter=json','--outputFile='+output]};});write('readiness.json',{environment:environmentAndPorts(),processes:processes()});write('runtime-roster.json',{head:read('signed-source.json').head,files,entries,gates,testHashes:Object.fromEntries(files.map(f=>[f,hash(fs.readFileSync(path.join(root,f)))])),node,vitest,nodeSha256:hash(fs.readFileSync(node)),vitestSha256:hash(fs.readFileSync(vitest)),noWideOrShadowAggregate:true});console.log(JSON.stringify({frozen:true,files:files.length,cases:entries.length,gates:gates.map(g=>({label:g.label,files:g.files.length,cases:g.entries.length})),counts:Object.fromEntries(files.map(f=>[f,entries.filter(a=>a.file===f).length]))}));
}else{
 const label=process.argv[2];if(!['focused','retained'].includes(label))throw Error('stage');custody();if(label==='retained'&&!read('focused/validation.json').valid)throw Error('Focused not GREEN');const roster=read('runtime-roster.json'),gate=roster.gates.find(g=>g.label===label),dir=path.join(out,label);for(const[f,h]of Object.entries(roster.testHashes))if(hash(fs.readFileSync(path.join(root,f)))!==h)throw Error('Roster source drift');fs.mkdirSync(dir);write(label+'/readiness.json',{environment:environmentAndPorts(),processes:processes()});write(label+'/command.json',{cwd:root,command:gate.command,environmentUnset:['TS_DRP_F5B_WIDE_DIAGNOSTIC']});const env={...process.env};delete env.TS_DRP_F5B_WIDE_DIAGNOSTIC;const stdout=fs.openSync(path.join(dir,'stdout.log'),'wx'),stderr=fs.openSync(path.join(dir,'stderr.log'),'wx'),started=Date.now(),child=spawn(gate.command[0],gate.command.slice(1),{cwd:root,env,detached:true,stdio:['ignore',stdout,stderr]});write(label+'/execution-start.json',{head:roster.head,recorderPid:process.pid,childPid:child.pid,ownedProcessGroup:child.pid,startedAt:new Date(started).toISOString()});console.log(JSON.stringify({label,childPid:child.pid,ownedProcessGroup:child.pid,cases:gate.entries.length}));let spawnError;child.on('error',e=>spawnError=String(e));child.on('close',(code,signal)=>{fs.closeSync(stdout);fs.closeSync(stderr);const ps=spawnSync('ps',['-axo','pid=,ppid=,pgid=,stat='],{encoding:'utf8'}),members=ps.stdout.trim().split('\n').map(s=>s.trim().split(/\s+/u)).filter(a=>Number(a[2])===child.pid),quiescent=ps.status===0&&members.length===0;write(label+'/status.json',{code,signal,spawnError,quiescent,elapsedMs:Date.now()-started,endedAt:new Date().toISOString()});console.log(JSON.stringify({label,code,signal,quiescent}));process.exitCode=code??1;});
}
