import type { ThresholdSet } from "./schemas.js";

/** The issue #5 decisions whose evidence rules must remain stable for a public campaign. */
export const PUBLIC_DECISION_RULES: ThresholdSet["rules"] = [
	{
		cellDimensions: ["networkCondition"],
		ciMethod: "wilson-95",
		evidencePhase: "phase-09",
		id: "node-dht-cold-bootstrap",
		interpretation: "public-observation",
		latencyThresholdMs: 30_000,
		minimumSampleCount: 100,
		statistic: "observed-rate",
		successThreshold: 0.95,
	},
	{
		cellDimensions: ["browser", "networkCondition"],
		ciMethod: "wilson-95",
		evidencePhase: "phase-09",
		id: "delegated-first-valid-peer",
		interpretation: "public-observation",
		latencyThresholdMs: 20_000,
		minimumSampleCount: 100,
		statistic: "observed-rate",
		successThreshold: 0.95,
	},
	{
		cellDimensions: ["browser"],
		ciMethod: "none",
		evidencePhase: "phase-07",
		id: "gossipsub-mesh-first-sync",
		interpretation: "deterministic-slo",
		latencyThresholdMs: 30_000,
		minimumSampleCount: 5,
		statistic: "all-pass",
		successThreshold: 1,
	},
	{
		cellDimensions: ["browser", "networkCondition", "transportProfile"],
		ciMethod: "wilson-95",
		evidencePhase: "phase-09",
		id: "public-relay-supported-baseline",
		interpretation: "public-observation",
		latencyThresholdMs: 20_000,
		minimumSampleCount: 50,
		statistic: "observed-rate",
		successThreshold: 0.95,
	},
	{
		cellDimensions: ["browser", "networkCondition", "transportProfile"],
		ciMethod: "wilson-95",
		evidencePhase: "phase-09",
		fallbackLatencyThresholdMs: 5_000,
		id: "public-relay-optional-overflow",
		interpretation: "public-observation",
		minimumSampleCount: 50,
		statistic: "observed-rate",
		successThreshold: 0.5,
	},
	{
		cellDimensions: [],
		ciMethod: "none",
		evidencePhase: "phase-09",
		id: "public-relay-diversity",
		interpretation: "public-observation",
		minimumOperatorGroups: 2,
		minimumSampleCount: 600,
		statistic: "minimum-diversity",
	},
	{
		cellDimensions: ["browser"],
		ciMethod: "none",
		evidencePhase: "phase-07",
		id: "controlled-direct-webrtc-upgrade",
		interpretation: "deterministic-slo",
		latencyThresholdMs: 20_000,
		minimumSampleCount: 5,
		statistic: "all-pass",
		successThreshold: 1,
	},
	{
		cellDimensions: ["browser", "networkCondition"],
		ciMethod: "none",
		evidencePhase: "phase-09",
		id: "public-direct-webrtc-canary",
		interpretation: "report-only",
		minimumSampleCount: 1,
		statistic: "report-only",
	},
	{
		cellDimensions: ["scenario"],
		ciMethod: "none",
		evidencePhase: "phase-08",
		id: "relay-registry-loss-recovery",
		interpretation: "deterministic-slo",
		latencyThresholdMs: 60_000,
		minimumSampleCount: 1,
		statistic: "all-pass",
		successThreshold: 1,
	},
	{
		cellDimensions: ["scenario"],
		ciMethod: "none",
		evidencePhase: "phase-08",
		id: "total-outage-terminal-diagnostic",
		interpretation: "deterministic-slo",
		latencyThresholdMs: 30_000,
		minimumSampleCount: 1,
		statistic: "all-pass",
		successThreshold: 1,
	},
];
